// Generated by Archie's scripts/sync-addon-fields.py. Do not edit by hand.
//
// The one table saying what an add-on may contain and how long each part may be. Its source is
// crates/archie-domain/src/addon_fields.rs in the Archie repo, which is also where the installer
// reads its caps, so the number this form stops accepting characters at and the number the app
// rejects at are the same number.
//
// js/submit.js builds all four submission forms from this. Adding a field there is a change here
// and nowhere else.

export const ADDON_SPEC = {
  "integrations": [
    {
      "grants": "Read the calendar, and add, change or remove events.",
      "id": "google_calendar",
      "name": "Google Calendar"
    },
    {
      "grants": "Read the inbox and draft replies. Never sends on its own.",
      "id": "gmail",
      "name": "Gmail"
    },
    {
      "grants": "Read and update the owner's real Todoist list.",
      "id": "todoist",
      "name": "Todoist"
    },
    {
      "grants": "Read and update the owner's Google Tasks list.",
      "id": "google_tasks",
      "name": "Google Tasks"
    },
    {
      "grants": "Turn a video link or file into notes in the knowledge base.",
      "id": "video",
      "name": "Video"
    },
    {
      "grants": "Look up live flight prices and schedules.",
      "id": "flights",
      "name": "Flights"
    },
    {
      "grants": "Read and update contacts, pipelines and conversations in a GoHighLevel account.",
      "id": "gohighlevel",
      "name": "GoHighLevel"
    }
  ],
  "kinds": {
    "personality": {
      "blurb": "A personality changes how the agent talks. It replaces the voice, never the things the agent can do.",
      "label": "Personality",
      "sections": [
        {
          "blurb": "What it is, in the store.",
          "fields": [
            {
              "control": "text",
              "help": "What someone sees on the card and in their list.",
              "key": "name",
              "label": "Name",
              "max": 64,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Inbox Pilot",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "text",
              "help": "Three or four words naming the voice, shown above the description.",
              "key": "tagline",
              "label": "Tagline",
              "max": 120,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Warm, direct, gets to the point",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "text",
              "help": "Say what it is for and what someone says to it. Quote a real phrase.",
              "key": "description",
              "label": "One line",
              "max": 280,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Log spending by chatting (\"$14 lunch\") and ask where your money went",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "textarea",
              "help": "A paragraph, shown when someone opens the card. Say what they get, not how it works.",
              "key": "long_description",
              "label": "The full pitch",
              "max": 2000,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "select",
              "help": "Which shelf of the store it sits on.",
              "key": "category",
              "label": "Category",
              "max": 0,
              "max_items": 0,
              "options": [
                "productivity",
                "communication",
                "finance",
                "research",
                "sales",
                "operations",
                "personal",
                "custom"
              ],
              "placeholder": "",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "number",
              "help": "In cents. 0 is free.",
              "key": "price_cents",
              "label": "Price",
              "max": 0,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Basics"
        },
        {
          "blurb": "A personality changes how the agent talks, never what it can do.",
          "fields": [
            {
              "control": "select",
              "help": "The nearest single word. Used for filtering and for the badge on the card.",
              "key": "tone",
              "label": "Tone",
              "max": 0,
              "max_items": 0,
              "options": [
                "professional",
                "friendly",
                "concise",
                "playful",
                "formal",
                "warm",
                "direct",
                "custom"
              ],
              "placeholder": "",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "prompt",
              "help": "How the agent should sound. Its buyer never sees this text and only adds rules on top of it, so say everything here.",
              "key": "system_prompt_template",
              "label": "The voice itself",
              "max": 10000,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": true,
              "scaffold": "You speak <in this manner>: <two or three concrete habits>.\n\nYou always:\n- <A thing this voice does that others don't.>\n- <Another.>\n\nYou never:\n- <The register this voice must never slip into.>\n- Never claim to have done something you did not do.\n"
            },
            {
              "control": "lines",
              "help": "One habit per line.",
              "key": "style_guidelines",
              "label": "Style rules",
              "max": 200,
              "max_items": 12,
              "options": [],
              "placeholder": "e.g. Short sentences. No corporate hedging.",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "lines",
              "help": "One prohibition per line. The strongest position in the prompt.",
              "key": "guardrails",
              "label": "Never do this",
              "max": 200,
              "max_items": 12,
              "options": [],
              "placeholder": "e.g. Never claim to have done something it did not do.",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "How it sounds"
        },
        {
          "blurb": "A voice nobody can hear before buying does not sell.",
          "fields": [
            {
              "control": "exchanges",
              "help": "What someone types, and what this voice says back. Shown on the card before anyone buys.",
              "key": "preview_exchanges",
              "label": "Sample exchanges",
              "max": 0,
              "max_items": 6,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Show it working"
        }
      ]
    },
    "routine": {
      "blurb": "A routine is a schedule. It sends the agent a message at a set time, so something arrives without anyone asking.",
      "label": "Routine",
      "sections": [
        {
          "blurb": "What it is, in the store.",
          "fields": [
            {
              "control": "text",
              "help": "What someone sees on the card and in their list.",
              "key": "name",
              "label": "Name",
              "max": 64,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Inbox Pilot",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "text",
              "help": "Say what it is for and what someone says to it. Quote a real phrase.",
              "key": "description",
              "label": "One line",
              "max": 280,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Log spending by chatting (\"$14 lunch\") and ask where your money went",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "textarea",
              "help": "A paragraph, shown when someone opens the card. Say what they get, not how it works.",
              "key": "long_description",
              "label": "The full pitch",
              "max": 2000,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "select",
              "help": "Which shelf of the store it sits on.",
              "key": "category",
              "label": "Category",
              "max": 0,
              "max_items": 0,
              "options": [
                "productivity",
                "communication",
                "finance",
                "research",
                "sales",
                "operations",
                "personal",
                "custom"
              ],
              "placeholder": "",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "number",
              "help": "In cents. 0 is free.",
              "key": "price_cents",
              "label": "Price",
              "max": 0,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Basics"
        },
        {
          "blurb": "A routine is a schedule plus a message it sends on that schedule.",
          "fields": [
            {
              "control": "schedule",
              "help": "Every so often, daily, or weekly. Its owner can change this after installing.",
              "key": "default_trigger",
              "label": "When it runs",
              "max": 0,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "text",
              "help": "A routine does not act on its own; it fires a skill. Name that skill's id.",
              "key": "required_skill",
              "label": "The skill it runs",
              "max": 64,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. sports-follow",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "prompt",
              "help": "The message the routine sends the agent each time it fires. Write it as a request.",
              "key": "default_action.prompt",
              "label": "What it sends",
              "max": 4000,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Read my saved teams, check how each did yesterday, and send one line per team.",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "select",
              "help": "Into the owner's chat, or nowhere (for a routine that only files something away).",
              "key": "default_action.delivery",
              "label": "Where the answer goes",
              "max": 0,
              "max_items": 0,
              "options": [
                "notify_telegram",
                "silent"
              ],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "When and what"
        },
        {
          "blurb": "Anything beyond the one skill it runs.",
          "fields": [
            {
              "control": "addons",
              "help": "Name anything it hands work to or reads from, and say why in words that finish \"so it can …\". Left unsaid, it installs looking healthy and does nothing.",
              "key": "required_addons",
              "label": "Other add-ons it needs",
              "max": 0,
              "max_items": 8,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "What it needs"
        },
        {
          "blurb": "",
          "fields": [
            {
              "control": "textarea",
              "help": "One sentence about what lands in their chat. Skip it when the description already says; a routine speaks first, so nobody has to know what to type.",
              "key": "usage_hint",
              "label": "What arrives, and when",
              "max": 400,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. One line per team, in your chat, every morning at 8:15.",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "lines",
              "help": "Only work nothing else can do for them: connect an account, paste a key. Anything declared below is already a button on the panel, so repeating it here makes a chore that can never be ticked. Usually empty.",
              "key": "setup_steps",
              "label": "Setup someone must do by hand",
              "max": 300,
              "max_items": 6,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Once it is installed"
        }
      ]
    },
    "skill": {
      "blurb": "A skill is something the agent can now do: manage a calendar, triage email, track spending. It runs when a message calls for it.",
      "label": "Skill",
      "sections": [
        {
          "blurb": "What it is, in the store.",
          "fields": [
            {
              "control": "text",
              "help": "What someone sees on the card and in their list.",
              "key": "name",
              "label": "Name",
              "max": 64,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Inbox Pilot",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "text",
              "help": "Say what it is for and what someone says to it. Quote a real phrase.",
              "key": "description",
              "label": "One line",
              "max": 280,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Log spending by chatting (\"$14 lunch\") and ask where your money went",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "textarea",
              "help": "A paragraph, shown when someone opens the card. Say what they get, not how it works.",
              "key": "long_description",
              "label": "The full pitch",
              "max": 2000,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "select",
              "help": "Which shelf of the store it sits on.",
              "key": "category",
              "label": "Category",
              "max": 0,
              "max_items": 0,
              "options": [
                "productivity",
                "communication",
                "finance",
                "research",
                "sales",
                "operations",
                "personal",
                "custom"
              ],
              "placeholder": "",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "number",
              "help": "In cents. 0 is free.",
              "key": "price_cents",
              "label": "Price",
              "max": 0,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Basics"
        },
        {
          "blurb": "The prompt is the skill. Everything else is packaging.",
          "fields": [
            {
              "control": "prompt",
              "help": "The prompt the skill runs on. Say what it does, name its tools, then the rules, ending with what it must never do and what to do when something is missing. Skills that skip those last two guess instead of asking.",
              "key": "template_md",
              "label": "Instructions",
              "max": 20000,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": true,
              "scaffold": "What this does, in one line and in your own words.\n\nTools:\n- Name each tool it should use, and when to reach for it.\n\nRules:\n1) When I say \"…\" → do this, in this order.\n2) When I say \"…\" → do this instead.\n3) If something it needs is missing → ask me for it. Never make it up.\n\nNever:\n- Never state something it didn't actually look up.\n- Never say a job finished before it has.\n\nHow it should sound: one line.\n"
            },
            {
              "control": "select",
              "help": "Higher quality costs more per message. Balanced suits most skills.",
              "key": "model.tier",
              "label": "Response quality",
              "max": 0,
              "max_items": 0,
              "options": [
                "fast",
                "balanced",
                "deep"
              ],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "tags",
              "help": "You usually need none. The agent routes by meaning; these only matter if that is briefly unreachable. Overlapping with a sibling skill is fine.",
              "key": "triggers",
              "label": "Backup words",
              "max": 48,
              "max_items": 32,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "What it does"
        },
        {
          "blurb": "Everything here becomes a live control with its own state, never a written chore.",
          "fields": [
            {
              "control": "variables",
              "help": "Each one becomes a field on the Personalize panel and a {{KEY}} in the prompt.",
              "key": "required_variables",
              "label": "What it asks its owner",
              "max": 0,
              "max_items": 16,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "collections",
              "help": "A table created in the agent when the skill installs. Mark the ones the skill READS (teams, medications) as needing a first entry; a list it WRITES as it goes (a journal, a spend log) is meant to start empty.",
              "key": "required_collections",
              "label": "Lists it keeps",
              "max": 0,
              "max_items": 8,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "integrations",
              "help": "Accounts the skill needs, which is what grants it the matching tools.",
              "key": "required_integrations",
              "label": "Connected accounts",
              "max": 0,
              "max_items": 8,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "addons",
              "help": "Name anything it hands work to or reads from, and say why in words that finish \"so it can …\". Left unsaid, it installs looking healthy and does nothing.",
              "key": "required_addons",
              "label": "Other add-ons it needs",
              "max": 0,
              "max_items": 8,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "What it needs"
        },
        {
          "blurb": "",
          "fields": [
            {
              "control": "textarea",
              "help": "The sentence someone types to get something out of it. Not a setup step.",
              "key": "usage_hint",
              "label": "What to say once it works",
              "max": 400,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Add a team or two, then just ask \"how did my teams do.\"",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "lines",
              "help": "Only work nothing else can do for them: connect an account, paste a key. Anything declared below is already a button on the panel, so repeating it here makes a chore that can never be ticked. Usually empty.",
              "key": "setup_steps",
              "label": "Setup someone must do by hand",
              "max": 300,
              "max_items": 6,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Once it is installed"
        }
      ]
    },
    "worker": {
      "blurb": "A worker is a specialist the agent hands a whole task to and waits on: a researcher, a writer, an analyst.",
      "label": "Worker",
      "sections": [
        {
          "blurb": "What it is, in the store.",
          "fields": [
            {
              "control": "text",
              "help": "What someone sees on the card and in their list.",
              "key": "name",
              "label": "Name",
              "max": 64,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Inbox Pilot",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "text",
              "help": "Say what it is for and what someone says to it. Quote a real phrase.",
              "key": "description",
              "label": "One line",
              "max": 280,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Log spending by chatting (\"$14 lunch\") and ask where your money went",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "textarea",
              "help": "A paragraph, shown when someone opens the card. Say what they get, not how it works.",
              "key": "long_description",
              "label": "The full pitch",
              "max": 2000,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "select",
              "help": "Which shelf of the store it sits on.",
              "key": "category",
              "label": "Category",
              "max": 0,
              "max_items": 0,
              "options": [
                "productivity",
                "communication",
                "finance",
                "research",
                "sales",
                "operations",
                "personal",
                "custom"
              ],
              "placeholder": "",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "number",
              "help": "In cents. 0 is free.",
              "key": "price_cents",
              "label": "Price",
              "max": 0,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Basics"
        },
        {
          "blurb": "A worker is a specialist the agent hands a whole task to.",
          "fields": [
            {
              "control": "text",
              "help": "The short label on the worker's row. What it is for, not how it behaves.",
              "key": "role",
              "label": "Its job, in a few words",
              "max": 500,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Finds and summarizes firms worth pitching",
              "required": true,
              "scaffold": ""
            },
            {
              "control": "prompt",
              "help": "The private prompt it runs under: who it is, what it specializes in, how to answer, and what to refuse. Vague instructions give vague results.",
              "key": "instructions",
              "label": "Instructions",
              "max": 20000,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": true,
              "scaffold": "You are a <specialty> specialist for this agent.\n\nWhen you are handed <the kind of task this worker is for>:\n1. <What to establish or check first.>\n2. <How to do the work, in order.>\n3. <What to hand back, and in what shape.>\n\nNever:\n- Never state a finding you did not actually look up.\n- Never take an action outside <this worker's job>.\n"
            },
            {
              "control": "toggle",
              "help": "Lets it search the web for fresh information. It uses the AI account its owner already connected, at about a cent per search.",
              "key": "web_search",
              "label": "Web access",
              "max": 0,
              "max_items": 0,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "select",
              "help": "Higher quality costs more per task.",
              "key": "model.tier",
              "label": "Response quality",
              "max": 0,
              "max_items": 0,
              "options": [
                "fast",
                "balanced",
                "deep"
              ],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "tags",
              "help": "Only a fallback. The agent already hands work to the right worker on its own.",
              "key": "triggers",
              "label": "Backup words",
              "max": 48,
              "max_items": 32,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "What it does"
        },
        {
          "blurb": "",
          "fields": [
            {
              "control": "textarea",
              "help": "Cost, limits, what it is good at. A worker needs no setup, so this is the only note shown after it installs.",
              "key": "usage_hint",
              "label": "What its owner should know",
              "max": 400,
              "max_items": 0,
              "options": [],
              "placeholder": "e.g. Each search costs about a cent, and it runs up to five per task.",
              "required": false,
              "scaffold": ""
            },
            {
              "control": "lines",
              "help": "Only work nothing else can do for them: connect an account, paste a key. Anything declared below is already a button on the panel, so repeating it here makes a chore that can never be ticked. Usually empty.",
              "key": "setup_steps",
              "label": "Setup someone must do by hand",
              "max": 300,
              "max_items": 6,
              "options": [],
              "placeholder": "",
              "required": false,
              "scaffold": ""
            }
          ],
          "title": "Once it is installed"
        }
      ]
    }
  },
  "limits": {
    "description": 280,
    "prompt": 20000,
    "trigger": 48,
    "triggers": 32,
    "user_additions": 2000
  },
  "note": "Generated from crates/archie-domain/src/addon_fields.rs. Do not edit by hand."
};
