// Generated by scripts/gen-catalog-index.mjs.
export const CATALOG_INDEX = [
  {
    "key": "skill:airtable-keeper",
    "name": "Airtable Keeper"
  },
  {
    "key": "routine:application-sweep",
    "name": "Application Sweep"
  },
  {
    "key": "routine:bill-reminders",
    "name": "Bill Reminders"
  },
  {
    "key": "skill:bill-tracker",
    "name": "Bills & Subscriptions"
  },
  {
    "key": "routine:birthday-heads-up",
    "name": "Birthday & Anniversary Heads-Up"
  },
  {
    "key": "skill:birthday-keeper",
    "name": "Birthday & Anniversary Keeper"
  },
  {
    "key": "routine:quarterly-card-categories",
    "name": "Bonus Category Check"
  },
  {
    "key": "skill:booking-watch",
    "name": "Booking Watch"
  },
  {
    "key": "skill:calendar-management",
    "name": "Calendar Manager"
  },
  {
    "key": "personality:calm-anchor",
    "name": "Calm Anchor"
  },
  {
    "key": "routine:campaign-check",
    "name": "Campaign Check"
  },
  {
    "key": "skill:campaign-watch",
    "name": "Campaign Watch"
  },
  {
    "key": "skill:car-keeper",
    "name": "Car Keeper"
  },
  {
    "key": "skill:card-rewards",
    "name": "Card Rewards"
  },
  {
    "key": "skill:circle-back",
    "name": "Circle Back"
  },
  {
    "key": "routine:circle-back-nudge",
    "name": "Circle-Back Nudge"
  },
  {
    "key": "skill:clean-books",
    "name": "Clean Books"
  },
  {
    "key": "skill:commitment-keeper",
    "name": "Commitment Keeper"
  },
  {
    "key": "routine:commitment-sweep",
    "name": "Commitment Sweep"
  },
  {
    "key": "skill:common-questions",
    "name": "Common Questions"
  },
  {
    "key": "personality:concise",
    "name": "Concise"
  },
  {
    "key": "skill:course-companion",
    "name": "Course Companion"
  },
  {
    "key": "personality:creative-muse",
    "name": "Creative Muse"
  },
  {
    "key": "routine:daily-briefing",
    "name": "Daily Briefing"
  },
  {
    "key": "routine:habit-check-in",
    "name": "Daily Habit Check-in"
  },
  {
    "key": "routine:study-review",
    "name": "Daily Study Review"
  },
  {
    "key": "skill:daily-trivia",
    "name": "Daily Trivia"
  },
  {
    "key": "routine:trivia-time",
    "name": "Daily Trivia Question"
  },
  {
    "key": "routine:daily-word",
    "name": "Daily Word"
  },
  {
    "key": "routine:workout-nudge",
    "name": "Daily Workout Nudge"
  },
  {
    "key": "specialist:deep-researcher",
    "name": "Deep Research"
  },
  {
    "key": "personality:dry",
    "name": "Dry"
  },
  {
    "key": "skill:email-manager",
    "name": "Email Manager"
  },
  {
    "key": "routine:evening-reflection",
    "name": "Evening Reflection"
  },
  {
    "key": "personality:exec-concierge",
    "name": "Exec Concierge"
  },
  {
    "key": "skill:find-a-time",
    "name": "Find a Time"
  },
  {
    "key": "skill:form-filler",
    "name": "Form Filler"
  },
  {
    "key": "routine:week-check",
    "name": "Friday Week Check"
  },
  {
    "key": "personality:friendly",
    "name": "Friendly"
  },
  {
    "key": "skill:github-keeper",
    "name": "GitHub Keeper"
  },
  {
    "key": "skill:gitlab-keeper",
    "name": "GitLab Keeper"
  },
  {
    "key": "skill:habit-tracker",
    "name": "Habit Tracker"
  },
  {
    "key": "routine:health-month",
    "name": "Health Month in Review"
  },
  {
    "key": "skill:health-record",
    "name": "Health Record"
  },
  {
    "key": "skill:home-lights",
    "name": "Home Lights"
  },
  {
    "key": "skill:home-maintenance",
    "name": "Home Maintenance"
  },
  {
    "key": "skill:home-workout",
    "name": "Home Workout Coach"
  },
  {
    "key": "personality:house-manager",
    "name": "House Manager"
  },
  {
    "key": "skill:house-watch",
    "name": "House Watch"
  },
  {
    "key": "personality:hype-coach",
    "name": "Hype Coach"
  },
  {
    "key": "skill:inbox-rules",
    "name": "Inbox Rules"
  },
  {
    "key": "routine:inbox-sweep",
    "name": "Inbox Sweep"
  },
  {
    "key": "skill:job-hunt",
    "name": "Job Hunt"
  },
  {
    "key": "personality:language-partner",
    "name": "Language Partner"
  },
  {
    "key": "skill:lead-desk",
    "name": "Lead Desk"
  },
  {
    "key": "routine:lead-sweep",
    "name": "Lead Sweep"
  },
  {
    "key": "skill:learning-coach",
    "name": "Learning Coach"
  },
  {
    "key": "skill:leave-time",
    "name": "Leave Time"
  },
  {
    "key": "skill:linear-keeper",
    "name": "Linear Keeper"
  },
  {
    "key": "skill:lunch-money-keeper",
    "name": "Lunch Money Keeper"
  },
  {
    "key": "skill:market-digest",
    "name": "Market Digest"
  },
  {
    "key": "skill:meal-planner",
    "name": "Meal Planner"
  },
  {
    "key": "skill:medication-reminder",
    "name": "Medication & Refill Reminder"
  },
  {
    "key": "routine:meeting-briefing",
    "name": "Meeting Briefing"
  },
  {
    "key": "skill:fireflies",
    "name": "Meeting Notes"
  },
  {
    "key": "skill:meeting-prep",
    "name": "Meeting Prep"
  },
  {
    "key": "routine:fireflies-sync",
    "name": "Meeting Sync"
  },
  {
    "key": "skill:mercury-watch",
    "name": "Mercury Watch"
  },
  {
    "key": "skill:money-in-out",
    "name": "Money In & Out"
  },
  {
    "key": "routine:morning-brief",
    "name": "Morning Brief"
  },
  {
    "key": "routine:market-morning",
    "name": "Morning Market Digest"
  },
  {
    "key": "routine:med-reminders",
    "name": "Morning Medication Reminder"
  },
  {
    "key": "routine:morning-news",
    "name": "Morning News Briefing"
  },
  {
    "key": "routine:sports-digest",
    "name": "Morning Sports Digest"
  },
  {
    "key": "routine:daily-task-digest",
    "name": "Morning Task Checklist"
  },
  {
    "key": "skill:my-documents",
    "name": "My Documents"
  },
  {
    "key": "personality:new-parent",
    "name": "New Parent"
  },
  {
    "key": "skill:new-teammate-welcome",
    "name": "New Teammate Welcome"
  },
  {
    "key": "routine:next-piece",
    "name": "Next Piece"
  },
  {
    "key": "personality:noir-detective",
    "name": "Noir Detective"
  },
  {
    "key": "skill:notion-keeper",
    "name": "Notion Keeper"
  },
  {
    "key": "personality:one-step-ahead",
    "name": "One Step Ahead"
  },
  {
    "key": "skill:owed-to-customers",
    "name": "Owed to Customers"
  },
  {
    "key": "personality:owner-and-a-date",
    "name": "Owner and a Date"
  },
  {
    "key": "skill:package-tracker",
    "name": "Package Tracker"
  },
  {
    "key": "skill:paperwork",
    "name": "Paperwork"
  },
  {
    "key": "skill:news-briefing",
    "name": "Personal News Briefing"
  },
  {
    "key": "personality:plain-and-patient",
    "name": "Plain and Patient"
  },
  {
    "key": "skill:plant-pet-care",
    "name": "Plant & Pet Care"
  },
  {
    "key": "routine:care-reminders",
    "name": "Plant & Pet Care Reminders"
  },
  {
    "key": "personality:playful-sidekick",
    "name": "Playful Sidekick"
  },
  {
    "key": "skill:price-watch",
    "name": "Price Watch"
  },
  {
    "key": "personality:professional",
    "name": "Professional"
  },
  {
    "key": "routine:question-sweep",
    "name": "Question Sweep"
  },
  {
    "key": "routine:queue-check",
    "name": "Queue Check"
  },
  {
    "key": "skill:reading-list",
    "name": "Reading & Watch List"
  },
  {
    "key": "skill:readwise-keeper",
    "name": "Readwise Keeper"
  },
  {
    "key": "skill:ready-to-post",
    "name": "Ready to Post"
  },
  {
    "key": "routine:receipt-sweep",
    "name": "Receipt Sweep"
  },
  {
    "key": "skill:personal-journal",
    "name": "Reflection"
  },
  {
    "key": "routine:reply-watch",
    "name": "Reply Watch"
  },
  {
    "key": "specialist:researcher",
    "name": "Researcher"
  },
  {
    "key": "routine:return-window-watch",
    "name": "Return Window Watch"
  },
  {
    "key": "routine:revenue-digest",
    "name": "Revenue Digest"
  },
  {
    "key": "skill:revenue-watch",
    "name": "Revenue Watch"
  },
  {
    "key": "skill:savings-goals",
    "name": "Savings Goals"
  },
  {
    "key": "routine:scheduling-watch",
    "name": "Scheduling Watch"
  },
  {
    "key": "skill:school-family",
    "name": "School & Family"
  },
  {
    "key": "routine:school-week",
    "name": "School Week Ahead"
  },
  {
    "key": "personality:second-opinion",
    "name": "Second Opinion"
  },
  {
    "key": "personality:sharp-advisor",
    "name": "Sharp Advisor"
  },
  {
    "key": "skill:splitwise-keeper",
    "name": "Splitwise Keeper"
  },
  {
    "key": "skill:sports-follow",
    "name": "Sports Follow"
  },
  {
    "key": "skill:statement-collector",
    "name": "Statement Collector"
  },
  {
    "key": "routine:statement-round",
    "name": "Statement Round"
  },
  {
    "key": "skill:stay-in-touch",
    "name": "Stay in Touch"
  },
  {
    "key": "personality:study-partner",
    "name": "Study Partner"
  },
  {
    "key": "routine:stay-in-touch-nudge",
    "name": "Sunday Stay-in-Touch Nudge"
  },
  {
    "key": "skill:task-manager",
    "name": "Task Manager"
  },
  {
    "key": "routine:team-standup",
    "name": "Team Standup"
  },
  {
    "key": "personality:terminal",
    "name": "Terminal"
  },
  {
    "key": "skill:text-replies",
    "name": "Text Replies"
  },
  {
    "key": "personality:the-bookkeeper",
    "name": "The Bookkeeper"
  },
  {
    "key": "personality:the-butler",
    "name": "The Butler"
  },
  {
    "key": "personality:the-careful-one",
    "name": "The Careful One"
  },
  {
    "key": "personality:the-cat",
    "name": "The Cat"
  },
  {
    "key": "personality:the-editor",
    "name": "The Editor"
  },
  {
    "key": "personality:the-fixer",
    "name": "The Fixer"
  },
  {
    "key": "personality:the-full-picture",
    "name": "The Full Picture"
  },
  {
    "key": "skill:the-handover",
    "name": "The Handover"
  },
  {
    "key": "personality:the-homie",
    "name": "The Homie"
  },
  {
    "key": "skill:honest-week",
    "name": "The Honest Week"
  },
  {
    "key": "personality:the-journal-keeper",
    "name": "The Journal Keeper"
  },
  {
    "key": "routine:leave-time-morning",
    "name": "The Morning Drive Check"
  },
  {
    "key": "personality:the-morning-show",
    "name": "The Morning Show"
  },
  {
    "key": "routine:nightly-sweep",
    "name": "The Nightly Sweep"
  },
  {
    "key": "personality:the-operator",
    "name": "The Operator"
  },
  {
    "key": "skill:reply-helper",
    "name": "The Right Words"
  },
  {
    "key": "personality:the-sportscaster",
    "name": "The Sportscaster"
  },
  {
    "key": "personality:the-stoic",
    "name": "The Stoic"
  },
  {
    "key": "personality:team-assistant",
    "name": "The Team Assistant"
  },
  {
    "key": "routine:leave-time-traffic",
    "name": "The Traffic Watch"
  },
  {
    "key": "personality:the-travel-agent",
    "name": "The Travel Agent"
  },
  {
    "key": "skill:google-tasks",
    "name": "To-Do List (Google Tasks)"
  },
  {
    "key": "skill:todoist",
    "name": "To-Do List (Todoist)"
  },
  {
    "key": "skill:trip-planner",
    "name": "Trip Planner"
  },
  {
    "key": "skill:video-synthesizer",
    "name": "Video Synthesizer"
  },
  {
    "key": "skill:waiting-on",
    "name": "Waiting On"
  },
  {
    "key": "personality:warm-companion",
    "name": "Warm Companion"
  },
  {
    "key": "skill:warranty-returns",
    "name": "Warranty & Returns"
  },
  {
    "key": "routine:car-checkup",
    "name": "Weekly Car Check"
  },
  {
    "key": "routine:home-checkup",
    "name": "Weekly Home Check"
  },
  {
    "key": "routine:price-check",
    "name": "Weekly Price Check"
  },
  {
    "key": "routine:weekly-review",
    "name": "Weekly Review"
  },
  {
    "key": "skill:whos-got-this",
    "name": "Who's Got This"
  },
  {
    "key": "skill:word-of-the-day",
    "name": "Word of the Day"
  },
  {
    "key": "specialist:writer",
    "name": "Writer"
  },
  {
    "key": "skill:writing-desk",
    "name": "Writing Desk"
  },
  {
    "key": "skill:ynab-keeper",
    "name": "YNAB Keeper"
  },
  {
    "key": "skill:zotero-keeper",
    "name": "Zotero Keeper"
  }
];
