#!/usr/bin/env python3
"""check-figures.py: the visual-first rules in CLAUDE.md, for the parts a script can hold.

Why this exists. The site is moving its arguments out of paragraphs and into drawings,
and a drawing fails differently from a paragraph. Copy is read by everyone who opens
the page; a figure can be read by nobody. It can carry a claim no editor checked
because it is not a sentence, and it can carry its claim only in motion, where a
crawler, an answer engine and a reader with reduced motion turned on all see an empty
box. Both of those already happened here: the glossary shipped "Entries shown: 0" to
the one page `llms.txt` points machines at, and five figures were live with no caption
on 2026-09-15.

WHAT THIS CAN AND CANNOT DO. Of the seven rules in CLAUDE.md, three are judgment and no
script will ever hold them: whether the thing that moves is the thing being claimed,
whether a drawing shows the product's real surface or an abstraction of it, and which
tier of motion a section deserved. Those are read by a person or not at all. What is
here is the mechanical floor under the other four, and one honest gap: animation
declared in css/styles.css rather than in the figure's own <style> is invisible to the
reduced-motion check below, because this reads figures, not the stylesheet.

Checks, each named for the rule it holds:

  caption      Rule 1. Every .explain-figure carries a <figcaption>. The caption is
               where the figure's claim is written down in words.
  name         Rule 6. Every <svg> in a figure that is not aria-hidden carries an
               accessible name, either aria-label or aria-labelledby resolving to a
               real <title> in that same SVG, and the name says something: a name of
               four words describes nothing to the machine reading it.
  trust        Rule 5. No phrasing from TRUST.md's Banned Phrasings table appears in
               anything a figure says: its labels, its accessible name, its caption.
               A drawing makes claims, so the claims rules apply to it.
  variants     Every figure carries paired desktop and mobile drawings, swapped at
               640px, so a diagram never scrolls sideways.
  motion       Any animation declared in a figure's own <style> sits inside a
               prefers-reduced-motion: no-preference block.

Usage:
  python3 scripts/check-figures.py            # check, exit 1 on failure
  python3 scripts/check-figures.py --report   # every figure, with shape and label counts
"""

import re
import sys
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SKIP_DIRS = {"node_modules", ".git", "__pycache__"}

# An accessible name shorter than this describes the drawing to nobody. Set from the
# shortest real one on the site when this landed (11 words, the add-on picker), not
# invented.
NAME_MIN_WORDS = 8

# Figures that legitimately do not take a check, each with the reason. A figure is
# listed here or it is fixed; there is no third option, and the reason is the point.
ALLOW = {
    # The phone mocks are generated by gen-phone-mocks.py and pair differently: one
    # desktop trio, then .mk-gallery for under 640px rather than an .explain-svg--mobile.
    # Same rule, different mechanism, so the variants check cannot see it.
    ("archie/mobile/index.html", "variants"): "phone mocks pair via .mk-gallery, not explain-svg--mobile",
}

SHAPE_TAGS = ("rect", "circle", "path", "line", "polygon", "polyline", "ellipse", "use")


def normalize(text):
    """Lowercase, straighten quotes, collapse space: what two phrasings share."""
    text = text.replace("’", "'").replace("‘", "'")
    text = text.replace("“", '"').replace("”", '"')
    text = text.replace("&rsquo;", "'").replace("&lsquo;", "'")
    text = text.replace("&ldquo;", '"').replace("&rdquo;", '"')
    text = text.replace("&nbsp;", " ").replace("&amp;", "&")
    return re.sub(r"\s+", " ", text).strip().lower()


def banned_phrases():
    """The Banned Phrasings table in TRUST.md, as phrases to look for.

    The table's first column quotes each banned wording, sometimes several separated
    by a slash, sometimes with an unquoted note like (unscoped) beside it. Only the
    quoted parts are phrases; the notes are prose about them.
    """
    trust = (ROOT / "TRUST.md").read_text(encoding="utf-8")
    m = re.search(r"^## Banned Phrasings.*?$(.*?)^## ", trust, re.S | re.M)
    if not m:
        raise SystemExit("check-figures: TRUST.md has no Banned Phrasings table to read.")
    out = []
    for line in m.group(1).splitlines():
        if not line.startswith("|") or line.startswith("| ---") or "| Banned" in line:
            continue
        first = line.split("|")[1]
        for quoted in re.findall(r"[\"“]([^\"”]+)[\"”]", first):
            phrase = normalize(quoted.replace("**", ""))
            # Every quoted entry counts, down to the one-word ones: the two of those
            # are "bank-grade" and "military-grade", which nobody writes by accident.
            # An earlier three-word floor silently dropped "fully private", which is
            # the single punchiest false claim the table exists to stop.
            if phrase:
                out.append((phrase, quoted.strip()))
    if not out:
        raise SystemExit("check-figures: read the Banned Phrasings table and found no phrases.")
    return out


def strip_tags(fragment):
    return re.sub(r"<[^>]+>", " ", fragment)


def figure_blocks(path):
    """Every .explain-figure on the page, with the line it starts on."""
    src = path.read_text(encoding="utf-8")
    for m in re.finditer(r'<figure\b[^>]*class="([^"]*\bexplain-figure\b[^"]*)"[\s\S]*?</figure>', src):
        yield m.group(0), m.group(1), src[: m.start()].count("\n") + 1


def guarded_style(block):
    """The figure's inline CSS with every reduced-motion-guarded block removed.

    Whatever animation is left is animation that runs for a reader who asked for none.
    Brace-matched rather than regexed, because these media blocks nest.
    """
    css = " ".join(re.findall(r"<style>([\s\S]*?)</style>", block))
    while True:
        m = re.search(r"@media\s*\([^)]*prefers-reduced-motion\s*:\s*no-preference[^)]*\)\s*\{", css)
        if not m:
            return css
        depth, i = 1, m.end()
        while i < len(css) and depth:
            depth += (css[i] == "{") - (css[i] == "}")
            i += 1
        css = css[: m.start()] + css[i:]


def says(block):
    """Everything a figure says: its labels, its accessible names, its caption."""
    parts = []
    parts += re.findall(r"<text\b[^>]*>([\s\S]*?)</text>", block)
    parts += re.findall(r"<title\b[^>]*>([\s\S]*?)</title>", block)
    parts += re.findall(r'aria-label="([^"]*)"', block)
    parts += [strip_tags(c) for c in re.findall(r"<figcaption\b[^>]*>([\s\S]*?)</figcaption>", block)]
    return [strip_tags(p) for p in parts]


def check_figure(rel, block, classes, line, banned):
    """Every failing check for one figure, as (check, message) pairs."""
    bad = []

    if "<figcaption" not in block:
        bad.append(("caption", "no <figcaption>: the figure's claim is written nowhere in words"))
    else:
        for cap in re.findall(r"<figcaption\b[^>]*>([\s\S]*?)</figcaption>", block):
            if not strip_tags(cap).strip():
                bad.append(("caption", "empty <figcaption>"))

    for tag in re.findall(r"<svg\b[^>]*>", block):
        if 'aria-hidden="true"' in tag:
            continue
        label = re.search(r'aria-label="([^"]*)"', tag)
        ref = re.search(r'aria-labelledby="([^"]*)"', tag)
        if label:
            name = label.group(1)
        elif ref:
            title = re.search(
                r'<title\b[^>]*id="%s"[^>]*>([\s\S]*?)</title>' % re.escape(ref.group(1)), block
            )
            if not title:
                bad.append(("name", f'aria-labelledby="{ref.group(1)}" points at no <title> in this figure'))
                continue
            name = title.group(1)
        else:
            bad.append(("name", "an <svg> with no aria-label and no aria-labelledby"))
            continue
        words = len(strip_tags(name).split())
        if words < NAME_MIN_WORDS:
            bad.append(("name", f"accessible name is {words} words, minimum {NAME_MIN_WORDS}: {name.strip()!r}"))

    text = normalize(" ".join(says(block)))
    for phrase, shown in banned:
        if phrase in text:
            bad.append(("trust", f"says a phrasing TRUST.md bans: {shown!r}"))

    has_desktop = "explain-svg--desktop" in block
    has_mobile = "explain-svg--mobile" in block
    if has_desktop != has_mobile:
        missing = "mobile" if has_desktop else "desktop"
        bad.append(("variants", f"has only one variant, missing the {missing} drawing"))
    elif not has_desktop and len(re.findall(r"<svg\b", block)) == 1:
        bad.append(("variants", "one unpaired <svg>: a figure needs a desktop and a mobile drawing"))

    if re.search(r"\banimation\s*:", guarded_style(block)):
        bad.append(("motion", "animation declared outside a prefers-reduced-motion: no-preference block"))

    return [(c, m) for c, m in bad if ALLOW.get((rel, c)) is None]


def pages():
    for path in sorted(ROOT.rglob("*.html")):
        if any(part in SKIP_DIRS for part in path.relative_to(ROOT).parts):
            continue
        yield path.relative_to(ROOT).as_posix(), path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true", help="every figure, with shape and label counts")
    args = ap.parse_args()

    banned = banned_phrases()
    failures, rows = [], []

    for rel, path in pages():
        for block, classes, line in figure_blocks(path):
            # The desktop variant alone. Counting the whole block sums both drawings and
            # reads double, which makes "about twenty shapes" look like forty.
            one = block.split("explain-svg--mobile")[0]
            shapes = sum(len(re.findall(r"<%s\b" % t, one)) for t in SHAPE_TAGS)
            labels = len(" ".join(re.findall(r"<text\b[^>]*>([\s\S]*?)</text>", one)).split())
            rows.append((rel, line, shapes, labels))
            for check, message in check_figure(rel, block, classes, line, banned):
                failures.append((rel, line, check, message))

    if args.report:
        print(f"{'figure':<52} {'line':>6} {'shapes':>7} {'labels':>7}   (desktop variant)")
        for rel, line, shapes, labels in sorted(rows, key=lambda r: -r[2]):
            print(f"{rel:<52} {line:6} {shapes:7} {labels:7}")
        print(f"\n{len(rows)} figures. Shapes and labels are reported, never failed:")
        print("one idea is about twenty shapes, and a figure that has grown past that is")
        print("usually two figures.")

    if failures:
        print()
        for rel, line, check, message in failures:
            print(f"check-figures: {rel}:{line} [{check}] {message}")
        print(f"\n{len(failures)} figures break the visual-first rules in CLAUDE.md.")
        print("Fix the figure, or add it to ALLOW in this script with the reason beside it.")
        return 1

    print(f"check-figures: clean. {len(rows)} figures, every one captioned, named and paired.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
