#!/usr/bin/env python3
"""Write js/store-lines.js from the Archie app's src/app/store-copy.ts.

The app's store leads every row with one short line per add-on, `STORE_LINE`, and keeps the
manifest's longer `description` for the expanded card. The site's browse grid led with that
`description` instead, which is two to four lines on every one of 170 cards, and Jett asked on
2026-10-06 for the marketplace to come down to "a few words" because the amount of text was
overwhelming the people it is for. The short lines already existed, written to the app's own
rules (lead with the relief, two lines at the outside, no superlatives), so the site copies them
rather than writing a second set.

The app is the source and the site never edits its copy, the same arrangement as js/faces.js and
scripts/check-faces.py. This one is generated rather than hand-copied because it is 150 lines of
prose, and a prose copy drifts one apostrophe at a time.

It reads the Archie checkout at the path CLAUDE.md names for verifying trust claims. Without that
checkout there is nothing to copy from, so --check says so and passes.

Run from anywhere:
  python3 scripts/gen-store-lines.py           # rewrite js/store-lines.js
  python3 scripts/gen-store-lines.py --check   # exit 1 if it has drifted from the app
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "store-lines.js"
APP_TS = Path("/Users/Games/Desktop/Code/Archie/src/app/store-copy.ts")

HEADER = """/* ========================================
   Otian AI | Add-on store lines
   js/store-lines.js

   GENERATED by scripts/gen-store-lines.py from the Archie app's src/app/store-copy.ts. Do not
   hand-edit: change the line in the app, then run the script. `--check` fails when this file and
   the app disagree.

   One short line per add-on, which is what a card leads with. The manifest's own `description`
   is longer and lives behind View Details. An add-on with no line here falls back the way the
   app's `storeLine` does: a personality to its tagline, anything else to its description, so a
   new add-on reads correctly on the day it is published.
   ======================================== */
"""

FOOTER = """
/** The line a card leads with: the written line, else a personality's tagline, else the
 *  description. Mirrors `storeLine` in the app's store-copy.ts. */
export function storeLine(item) {
  var written = STORE_LINE[item.kind + ":" + item.id];
  if (written) return written;
  if (item.kind === "personality" && item.tagline && item.tagline.trim()) return item.tagline.trim();
  return item.description;
}
"""


def read_lines(src: str) -> list[tuple[str, str]]:
    m = re.search(r"export const STORE_LINE[^=]*=\s*\{(.*?)\n\};", src, re.S)
    if not m:
        raise SystemExit("gen-store-lines: could not find STORE_LINE in store-copy.ts. Has its shape changed?")
    pairs = re.findall(r'"([a-z]+:[a-z0-9-]+)"\s*:\s*("(?:[^"\\]|\\.)*")', m.group(1))
    return [(k, json.loads(v)) for k, v in pairs]


def render(pairs: list[tuple[str, str]]) -> str:
    body = "".join(f"  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)},\n" for k, v in pairs)
    return HEADER + "\nexport var STORE_LINE = {\n" + body + "};\n" + FOOTER


def main() -> int:
    check = "--check" in sys.argv[1:]
    if not APP_TS.exists():
        print(f"gen-store-lines: no Archie checkout at {APP_TS.parent.parent.parent}, nothing to copy. Skipped.")
        return 0
    pairs = read_lines(APP_TS.read_text())
    if not pairs:
        print("gen-store-lines: STORE_LINE in store-copy.ts is empty. Has its shape changed?")
        return 1
    want = render(pairs)
    have = OUT.read_text() if OUT.exists() else ""
    if check:
        if have != want:
            print(f"gen-store-lines: js/store-lines.js has drifted from the app ({len(pairs)} lines there). "
                  "Run: python3 scripts/gen-store-lines.py")
            return 1
        print(f"gen-store-lines: clean. {len(pairs)} lines, matching the app.")
        return 0
    if have == want:
        print(f"gen-store-lines: already current, {len(pairs)} lines.")
        return 0
    OUT.write_text(want)
    print(f"gen-store-lines: wrote js/store-lines.js, {len(pairs)} lines.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
