#!/usr/bin/env python3
"""gen-phone-mocks.py: the three Archie Mobile screens on archie/mobile/, drawn once.

The page shows three phone screens twice: as a trio side by side on a wide window, and as
the scrolling gallery under 640px. That is six drawings of three screens, and until
2026-09-14 all six were hand-written SVG pasted into the page. A styling change meant six
edits, which is how the two halves drift: a card radius fixed in the gallery and missed in
the trio reads as a bug nobody can find.

So the screens live here, as content plus components, and this writes both renderings into
the page between markers. Same arrangement as gen-marketplace.mjs and gen-blog.mjs: the
result is committed, and --check is what stops the committed markup drifting from its source.

WHAT IT IS AND IS NOT. These are drawings of the app, not screenshots of it, and the
distinction is load-bearing: the app is in testing and its screens still move. What the
drawings owe the reader is that every element on them is one the app actually has, doing
what the app actually does. The styling was brought to the shipping app's on 2026-09-14
from screenshots of the real build: the status bar, the header with its wordmark and agent
picker, the stacked action card under a draft, the per-skill toggle and chevron, the tab
bars and their counts. The CONTENT is the site's own and stays that way, because the real
screens carry a real person's mail.

    python3 scripts/gen-phone-mocks.py           write the page
    python3 scripts/gen-phone-mocks.py --check   fail if the page is out of date
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "archie", "mobile", "index.html")

BEGIN = "<!-- BEGIN phone mocks: generated by scripts/gen-phone-mocks.py. Do not hand-edit. -->"
END = "<!-- END phone mocks -->"

# The screen is 390x800 inside a 412x822 shell, which is the geometry the page already used
# and the reason the outer viewBoxes below are unchanged.
W, H = 390.0, 800.0
SHELL_PAD = 11.0

# Vertical bands, top to bottom. The app's own proportions: a status bar, a header with a
# hairline under it, the scrolling content, then the tab bar pinned to the bottom.
STATUS_H = 52.0
HEAD_H = 52.0
HEAD_RULE = STATUS_H + HEAD_H          # 104
TABBAR_Y = 722.0
COMPOSER_Y = 660.0        # the chat screen's input bar, drawn at a fixed height

# ── ids ──────────────────────────────────────────────────────────────────────────────────
# Every gradient and clipPath needs an id unique across the whole page, because the desktop
# trio puts three screens in one <svg> and the browser resolves url(#x) document-wide.
_n = [0]


def uid(p):
    _n[0] += 1
    return "%s%d" % (p, _n[0])


def esc(t):
    return (t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace("’", "&rsquo;").replace("·", "&middot;"))


def f(v):
    """Trim floats so the markup does not carry 14 decimals of nothing."""
    s = "%.1f" % float(v)
    return s[:-2] if s.endswith(".0") else s


# ── primitives ───────────────────────────────────────────────────────────────────────────
SERIF = "Georgia,'Times New Roman',serif"


def rect(x, y, w, h, r=0, fill="none", stroke=None, sw=1, extra=""):
    s = '<rect x="%s" y="%s" width="%s" height="%s"' % (f(x), f(y), f(w), f(h))
    if r:
        s += ' rx="%s"' % f(r)
    s += ' fill="%s"' % fill
    if stroke:
        s += ' stroke="%s" stroke-width="%s"' % (stroke, f(sw))
    return s + extra + "/>"


def text(x, y, t, size=13.5, fill="var(--ink)", weight="400", anchor="start", serif=False):
    s = '<text x="%s" y="%s" font-size="%s" fill="%s" font-weight="%s" text-anchor="%s"' % (
        f(x), f(y), f(size), fill, weight, anchor)
    if serif:
        s += ' font-family="%s"' % SERIF
    return s + ">%s</text>" % esc(t)


def circle(cx, cy, r, fill="none", stroke=None, sw=1):
    s = '<circle cx="%s" cy="%s" r="%s" fill="%s"' % (f(cx), f(cy), f(r), fill)
    if stroke:
        s += ' stroke="%s" stroke-width="%s"' % (stroke, f(sw))
    return s + "/>"


def line(x1, y1, x2, y2, stroke="var(--bd)", sw=1):
    return '<line x1="%s" y1="%s" x2="%s" y2="%s" stroke="%s" stroke-width="%s"/>' % (
        f(x1), f(y1), f(x2), f(y2), stroke, f(sw))


def icon(paths, x, y, scale=1.0, stroke="var(--ink3)", fill="none", sw=1.8):
    """A 24x24 stroked glyph, the same vocabulary the app's tab bar and rows use."""
    return ('<g transform="translate(%s,%s) scale(%s)" fill="%s" stroke="%s" stroke-width="%s"'
            ' stroke-linecap="round" stroke-linejoin="round">%s</g>') % (
        f(x), f(y), "%.4f" % scale, fill, stroke, f(sw), paths)


# ── the Ember faces, lifted from the app's own marks ──────────────────────────────────────
# A face is drawn in a 200x200 space and scaled into a circle of radius r, so the call site
# only says where and how big. Colours and accessories per agent, the way the app deals them
# from the agent itself, so two agents never look like twins.
FACES = {
    "ember":  dict(hi="#F0AB80", mid="#E28D5E", lo="#C36A3D", eyes="oval", extra="hat"),
    "teal":   dict(hi="#63B2A9", mid="#3E9A92", lo="#2E7C75", eyes="round", extra="glasses"),
    "gold":   dict(hi="#D3A855", mid="#BB8C33", lo="#9A7226", eyes="oval", extra="antenna"),
}


def face_body(kind):
    c = FACES[kind]
    g = uid("em")
    o = ['<defs><linearGradient id="%s" x1="0" y1="0.18" x2="0" y2="1">'
         '<stop offset="0" stop-color="%s"/><stop offset="0.55" stop-color="%s"/>'
         '<stop offset="1" stop-color="%s"/></linearGradient></defs>' % (g, c["hi"], c["mid"], c["lo"])]
    o.append('<ellipse cx="82" cy="169" rx="10" ry="7.5" fill="%s"/>' % c["lo"])
    o.append('<ellipse cx="118" cy="169" rx="10" ry="7.5" fill="%s"/>' % c["lo"])
    if c["extra"] == "hat":
        o.append('<path d="M100 30 L87 58 L113 58 Z" fill="%s" stroke="%s" stroke-width="8"'
                 ' stroke-linejoin="round"/>' % (c["lo"], c["lo"]))
    if c["extra"] == "antenna":
        o.append('<path d="M100 52 L100 34" stroke="%s" stroke-width="7" stroke-linecap="round"/>' % c["lo"])
        o.append('<circle cx="100" cy="27" r="9" fill="%s"/>' % c["lo"])
    o.append('<circle cx="100" cy="108" r="60" fill="url(#%s)"/>' % g)
    o.append('<ellipse cx="65" cy="125" rx="8.5" ry="5" fill="%s" opacity=".38"/>' % c["lo"])
    o.append('<ellipse cx="135" cy="125" rx="8.5" ry="5" fill="%s" opacity=".38"/>' % c["lo"])
    for ex in (78, 122):
        if c["eyes"] == "oval":
            eye = ('<rect x="-7" y="-14" width="14" height="28" rx="7" fill="#2A2521"/>'
                   '<circle cx="-2.5" cy="-7" r="2.5" fill="#FFF" opacity=".85"/>')
        else:
            eye = ('<circle cx="0" cy="0" r="10" fill="#2A2521"/>'
                   '<circle cx="-3" cy="-3.5" r="3" fill="#FFF" opacity=".85"/>')
        o.append('<g transform="translate(%d,103)">%s</g>' % (ex, eye))
    o.append('<path d="M93 132 Q100 138 107 132" stroke="#2A2521" stroke-width="3.2" fill="none"'
             ' stroke-linecap="round"/>')
    if c["extra"] == "glasses":
        o.append('<g fill="none" stroke="#2A2521" stroke-width="3.4" opacity=".85">'
                 '<circle cx="78" cy="103" r="17"/><circle cx="122" cy="103" r="17"/>'
                 '<path d="M95 103h10" stroke-linecap="round"/></g>')
    if c["extra"] == "antenna":
        o.append('<g fill="%s" opacity=".55"><circle cx="60" cy="118" r="2.6"/>'
                 '<circle cx="68" cy="126" r="2.6"/><circle cx="56" cy="130" r="2.6"/>'
                 '<circle cx="140" cy="118" r="2.6"/><circle cx="132" cy="126" r="2.6"/>'
                 '<circle cx="144" cy="130" r="2.6"/></g>' % c["lo"])
    return "".join(o)


def avatar(cx, cy, r, kind, dot=False):
    cid = uid("fc")
    o = ['<defs><clipPath id="%s"><circle cx="%s" cy="%s" r="%s"/></clipPath></defs>' % (
        cid, f(cx), f(cy), f(r))]
    o.append(circle(cx, cy, r, "var(--accS)"))
    o.append('<g clip-path="url(#%s)"><g transform="translate(%s,%s) scale(%s)">%s</g></g>' % (
        cid, f(cx - r), f(cy - r), "%.4f" % (r / 100.0), face_body(kind)))
    if dot:
        # the app puts a presence dot on the agent in the header, and it is the one place
        # "running" is stated without a word for it
        o.append(circle(cx + r * 0.72, cy + r * 0.72, r * 0.26, "var(--grn)", "var(--bg)", 1.5))
    return "".join(o)


# ── the Archie wordmark ──────────────────────────────────────────────────────────────────
def wordmark(x, y, scale=0.02444):
    a, b = uid("wm"), uid("wm")
    return ('<g transform="translate(%s,%s) scale(%s)"><defs>'
            '<linearGradient id="%s" gradientUnits="userSpaceOnUse" x1="512" y1="85" x2="512" y2="888">'
            '<stop offset="0" stop-color="#F0AB80"/><stop offset="0.55" stop-color="#E28D5E"/>'
            '<stop offset="1" stop-color="#C36A3D"/></linearGradient>'
            '<linearGradient id="%s" x1="0" y1="0" x2="0" y2="1">'
            '<stop offset="0" stop-color="#EFA97E"/><stop offset="1" stop-color="#C36A3D"/>'
            '</linearGradient></defs><g transform="translate(-190,-35)">'
            '<polygon fill="url(#%s)" stroke="url(#%s)" stroke-width="34" stroke-linejoin="round"'
            ' stroke-linecap="round" points="328,887 512,727 696,887"/>'
            '<path fill="url(#%s)" stroke="url(#%s)" stroke-width="34" stroke-linejoin="round"'
            ' stroke-linecap="round" fill-rule="evenodd"'
            ' d="M 512,85 L 824,850 L 512,712 L 200,850 Z M 512,272 L 384,616 L 640,616 Z"/></g>'
            '<text x="690" y="690" font-family="Georgia,serif" font-size="590" font-weight="bold"'
            ' fill="url(#%s)" dominant-baseline="middle">rchie</text></g>') % (
        f(x), f(y), "%.5f" % scale, a, b, a, a, a, a, b)


# ── chrome ───────────────────────────────────────────────────────────────────────────────
def status_bar(clock="9:41"):
    """The phone's own bar. Nothing here is Archie: it is what makes the rest read as a phone."""
    o = [text(30, 34, clock, 15.5, "var(--ink)", "600", serif=False)]
    # the silent bell, which is on every one of these because they are drawn quiet
    o.append(icon('<path d="M6 16.5V11a6 6 0 0 1 9.3-5M18 13v3.5l1.5 1.5H7"/><path d="M4 4l16 16"/>',
                  72, 20, 0.62, "var(--ink)", sw=2.2))
    # signal, wifi, battery
    for i, h in enumerate((4.5, 7, 9.5, 12)):
        fill = "var(--ink)" if i < 3 else "var(--soft2)"
        o.append(rect(300 + i * 6.5, 33 - h, 4, h, 1.2, fill))
    o.append(icon('<path d="M2 8.5a13 13 0 0 1 16 0M5 12a8.5 8.5 0 0 1 10 0"/>'
                  '<circle cx="10" cy="15.6" r="1.2" fill="currentColor" stroke="none"/>',
                  328, 20, 0.62, "var(--ink)", sw=2.2))
    o.append(rect(348, 24, 22, 11, 3.2, "none", "var(--ink)", 1.2))
    o.append(rect(350, 26, 15, 7, 1.8, "var(--ink)"))
    o.append(rect(371, 27.5, 1.8, 4, 0.9, "var(--ink)"))
    return "".join(o)


def header_agent(name, kind):
    """Wordmark left, then the agent you are talking to, centred, with the picker chevron."""
    o = [wordmark(16, STATUS_H + 5)]
    cx = W / 2 - 34
    o.append(avatar(cx, STATUS_H + 26, 15, kind, dot=True))
    o.append(text(cx + 24, STATUS_H + 31, name, 17, "var(--ink)", "400", serif=True))
    tw = len(name) * 8.6
    o.append(icon('<path d="M4 8l6 6 6-6"/>', cx + 28 + tw, STATUS_H + 18, 0.75, "var(--ink2)", sw=2))
    o.append(line(0, HEAD_RULE, W, HEAD_RULE))
    return "".join(o)


def header_list(title, chip):
    """Wordmark left, the screen's name centred, and which computer you are looking at."""
    o = [wordmark(16, STATUS_H + 5)]
    o.append(text(W / 2, STATUS_H + 32, title, 18, "var(--ink)", "400", "middle", serif=True))
    cw = len(chip) * 7.0 + 26
    o.append(rect(W - 16 - cw, STATUS_H + 12, cw, 30, 15, "var(--soft)", "var(--bd)", 1))
    o.append(text(W - 16 - cw / 2, STATUS_H + 32, chip, 13, "var(--ink2)", "500", "middle"))
    o.append(line(0, HEAD_RULE, W, HEAD_RULE))
    return "".join(o)


TAB_ICONS = {
    "Now": '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    "Chat": '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',
    "Skills": '<path d="M12 3v4M12 17v4M5 12H1M23 12h-4M6.3 6.3 4 4M20 20l-2.3-2.3M17.7 6.3 20 4M4 20l2.3-2.3"/><circle cx="12" cy="12" r="3"/>',
    "Routines": '<circle cx="12" cy="12" r="10"/><path d="M12 6.4v5.6l3.5 2.3"/>',
    "More": '<circle cx="5.5" cy="12" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="18.5" cy="12" r="1.6"/>',
    "Agents": '<circle cx="12" cy="9" r="3.4"/><path d="M 5.5 19.2 C 5.5 15.5 8.4 13.6 12 13.6 C 15.6 13.6 18.5 15.5 18.5 19.2"/>',
    "Work": '<rect x="3" y="3" width="5" height="18" rx="1.5"/><rect x="10" y="3" width="5" height="12" rx="1.5"/><rect x="17" y="3" width="4" height="8" rx="1.5"/>',
    "Marketplace": '<path d="M4 8h16l-1.2 12.5H5.2z"/><path d="M8.6 8V6.2a3.4 3.4 0 0 1 6.8 0V8"/>',
    "Settings": '<rect x="6" y="2.5" width="12" height="19" rx="2.6"/><path d="M10.6 18.6h2.8"/>',
}


def tab_bar(tabs, active):
    o = [rect(0, TABBAR_Y, W, H - TABBAR_Y, 0, "var(--card)"), line(0, TABBAR_Y, W, TABBAR_Y)]
    step = W / len(tabs)
    for i, name in enumerate(tabs):
        cx = step * (i + 0.5)
        on = name == active
        col = "var(--acc)" if on else "var(--ink3)"
        o.append(icon(TAB_ICONS[name], cx - 11, TABBAR_Y + 12, 0.9167, col, sw=1.8))
        o.append(text(cx, TABBAR_Y + 48, name, 12, col, "600" if on else "500", "middle"))
    return "".join(o)


def pill(x, y, label, fg, bg, size=12.5, pad=10, h=22):
    w = len(label) * 6.4 + pad * 2
    return (rect(x, y, w, h, h / 2, bg)
            + text(x + pad, y + h / 2 + 4.2, label, size, fg, "600")), w


def toggle(x, y, on):
    """The app's switch: ember when on, a quiet fill when off."""
    o = [rect(x, y, 50, 30, 15, "var(--acc)" if on else "var(--soft2)")]
    o.append(circle(x + (35 if on else 15), y + 15, 12, "#FFFFFF"))
    return "".join(o)


def chevron_button(cx, cy):
    """The disclosure the app puts beside every switch, so the row has two different jobs."""
    return (circle(cx, cy, 15, "var(--soft)")
            + icon('<path d="M4 8l6 6 6-6"/>', cx - 7.5, cy - 7.5, 0.75, "var(--ink2)", sw=2))


# ── screen 1: the agents on your computer ────────────────────────────────────────────────
AGENTS = [
    dict(name="Email Manager", kind="ember", running=True,
         said="Twelve came in overnight. Two need you, and the",
         said2="other ten are filed.",
         meta="40m ago · 4 skills, 2 routines"),
    dict(name="Bookkeeper", kind="teal", running=False,
         said="Four receipts filed. One from the hardware shop",
         said2="has no total on it, so I left it alone.",
         meta="Yesterday · 2 skills, 1 routine"),
    dict(name="Around the House", kind="gold", running=False,
         said="The car insurance expires in three weeks. Worth",
         said2="looking at now rather than later.",
         meta="9h ago · 1 skill, 2 routines"),
]


def screen_agents():
    o = [status_bar(), header_list("Agents", "Your Mac")]
    y = HEAD_RULE + 16
    for a in AGENTS:
        ch = 146.0
        o.append(rect(16, y, 358, ch, 16, "var(--card)", "var(--bd)", 1))
        o.append(avatar(54, y + 38, 22, a["kind"]))
        o.append(text(88, y + 45, a["name"], 19, "var(--ink)", "400", serif=True))
        # Start or Stop, the one control the app puts on a card at rest
        lbl = "Stop" if a["running"] else "Start"
        bw = 84.0
        bx = 358 + 16 - 16 - bw
        o.append(rect(bx, y + 22, bw, 34, 11, "var(--redF)" if a["running"] else "var(--grnF)"))
        if a["running"]:
            glyph = '<rect x="6.6" y="6.6" width="10.8" height="10.8" rx="2.4"/>'
        else:
            glyph = '<path d="M 8.6 5.6 L 18.4 12 L 8.6 18.4 Z"/>'
        o.append(icon(glyph, bx + 13, y + 30, 0.625, "#FFFFFF", "#FFFFFF", 1.8))
        o.append(text(bx + 34, y + 43.5, lbl, 13.5, "#FFFFFF", "600"))
        o.append(text(32, y + 82, a["said"], 13.5, "var(--ink2)"))
        o.append(text(32, y + 99, a["said2"], 13.5, "var(--ink2)"))
        p, pw = pill(32, y + 112, "Running" if a["running"] else "Stopped",
                     "var(--grn)" if a["running"] else "var(--ink3)",
                     "var(--grnS)" if a["running"] else "var(--soft)")
        o.append(p)
        o.append(text(32 + pw + 10, y + 127.5, a["meta"], 13, "var(--ink3)"))
        y += ch + 14
    o.append(tab_bar(["Agents", "Work", "Marketplace", "Settings"], "Agents"))
    return "".join(o)


# ── screen 2: the conversation, and what a draft offers ──────────────────────────────────
ACTIONS = [
    ("Send", '<path d="M5 12.5l5 5 9-10"/>', "var(--grn)", "var(--acc)"),
    ("Edit it", '<path d="M4 20h4l10-10-4-4L4 16z"/>', "var(--ink2)", "var(--acc)"),
    ("Send later", '<circle cx="12" cy="13" r="8"/><path d="M12 9v4l2.5 1.6M8 3L5 5.5M16 3l3 2.5"/>', "var(--ink2)", "var(--acc)"),
    ("Dismiss", '<path d="M6 6l12 12M18 6L6 18"/>', "var(--ink3)", "var(--ink3)"),
]


def screen_chat():
    o = [status_bar(), header_agent("Archibald", "ember")]
    y = HEAD_RULE + 18

    def bubble(x, w, h, mine):
        return rect(x, y, w, h, 16, "var(--accS)" if mine else "var(--card)",
                    None if mine else "var(--bd)", 1)

    # you, asking
    o.append(bubble(158, 216, 38, True))
    o.append(text(172, y + 24, "Anything from the accountant?", 13.5, "var(--ink)"))
    y += 46
    # the agent answers, with its face beside the bubble the way the app shows it
    o.append(avatar(30, y + 22, 15, "ember"))
    o.append(bubble(54, 276, 54, False))
    o.append(text(68, y + 24, "Nothing since Friday. I will wake you", 13.5, "var(--ink)"))
    o.append(text(68, y + 41, "for one, as you asked.", 13.5, "var(--ink)"))
    y += 62
    o.append(avatar(30, y + 22, 15, "ember"))
    o.append(bubble(54, 300, 54, False))
    o.append(text(68, y + 24, "Twelve came in overnight. Two need you,", 13.5, "var(--ink)"))
    o.append(text(68, y + 41, "and the other ten are filed.", 13.5, "var(--ink)"))
    y += 62
    o.append(bubble(86, 288, 38, True))
    o.append(text(100, y + 24, "Tell the landlord Tuesday morning works.", 13.5, "var(--ink)"))
    y += 46

    # the draft, and then its actions in a card of their own: the shape the app uses to make
    # "nothing was sent" obvious, because the verb is a row you have not pressed yet
    o.append(avatar(30, y + 22, 15, "ember"))
    o.append(bubble(54, 300, 96, False))
    o.append(text(68, y + 24, "Here is what I would send:", 13.5, "var(--ink)"))
    o.append(rect(68, y + 34, 272, 46, 6, "var(--soft)"))
    o.append(line(68, y + 34, 68, y + 80, "var(--acc)", 3))
    o.append(text(78, y + 52, "Tuesday morning works for us. Any time", 13, "var(--ink2)"))
    o.append(text(78, y + 69, "before noon is fine, and somebody will be in.", 13, "var(--ink2)"))
    y += 108

    rowh = 44.0
    o.append(rect(54, y, 300, rowh * len(ACTIONS), 16, "var(--card)", "var(--bd)", 1))
    for i, (label, glyph, gcol, tcol) in enumerate(ACTIONS):
        ry = y + rowh * i
        if i:
            o.append(line(54, ry, 354, ry, "var(--bd)", 1))
        lw = len(label) * 8.0
        gx = 204 - lw / 2 - 26
        o.append(icon(glyph, gx, ry + rowh / 2 - 10, 0.83, gcol, sw=2.2))
        o.append(text(gx + 28, ry + rowh / 2 + 5, label, 15, tcol, "600"))
    y += rowh * len(ACTIONS) + 14
    o.append(text(54, y + 10, "8 minutes ago", 12.5, "var(--ink3)"))

    # The thread is laid out by accumulation, so adding a bubble pushes everything below it
    # into the composer, which is drawn at a fixed y and would happily print over the top.
    # That happened once: the timestamp landed at 662 against a composer at 660 and the two
    # were each inside the screen, so a bounds check saw nothing wrong. Assert the gap.
    assert y + 14 <= COMPOSER_Y, (
        "chat thread runs to %.0f and the composer starts at %.0f: tighten the bubble gaps "
        "or drop a message" % (y + 14, COMPOSER_Y))

    # the composer
    o.append(circle(38, COMPOSER_Y + 22, 22, "var(--soft)"))
    o.append(icon('<path d="M12 5v14M5 12h14"/>', 27, COMPOSER_Y + 11, 0.9167, "var(--ink2)", sw=2))
    o.append(rect(68, COMPOSER_Y, 254, 44, 22, "var(--card)", "var(--bd)", 1))
    o.append(text(84, COMPOSER_Y + 28, "Message Archibald", 14, "var(--ink3)"))
    o.append(circle(352, COMPOSER_Y + 22, 22, "var(--acc)"))
    o.append('<path d="M352 692 v-18 m-7 7 l7 -7 l7 7" stroke="#FFF" stroke-width="2.4"'
             ' fill="none" stroke-linecap="round" stroke-linejoin="round"/>')
    o.append(tab_bar(["Now", "Chat", "Skills", "Routines", "More"], "Chat"))
    return "".join(o)


# ── screen 3: what an agent is made of ───────────────────────────────────────────────────
SKILLS = [
    dict(name="Inbox triage", on=True, note=None,
         lines=["Sorts the morning's mail into what needs", "you and what does not."]),
    dict(name="Reply drafts", on=True, note=None,
         lines=["Writes the reply and holds it until you", "press Send."]),
    dict(name="Proofreader", on=True, note=None,
         lines=["A specialist. Reads anything before it goes."]),
    dict(name="Calendar", on=False, note="Needs a connection",
         lines=["Reads and writes the calendar. Off until", "you connect an account."]),
    dict(name="Receipts", on=True, note=None,
         lines=["Files what arrives and totals the month."]),
]


def screen_skills():
    o = [status_bar(), header_agent("Archibald", "ember")]
    y = HEAD_RULE + 16
    # the way into the marketplace sits above the list, outlined rather than filled: it is
    # the only thing on this screen that leaves it
    o.append(rect(16, y, 358, 48, 12, "none", "var(--acc)", 1.5))
    o.append(icon('<path d="M4 8h16l-1.2 12.5H5.2z"/><path d="M8.6 8V6.2a3.4 3.4 0 0 1 6.8 0V8"/>',
                  110, y + 13, 0.9167, "var(--acc)", sw=1.8))
    o.append(text(142, y + 30, "Browse the marketplace", 15, "var(--acc)", "600"))
    y += 62

    for s in SKILLS:
        ch = 56.0 + 17.0 * len(s["lines"])
        o.append(rect(16, y, 358, ch, 16, "var(--card)", "var(--bd)", 1))
        o.append(text(32, y + 34, s["name"], 16, "var(--ink)", "400", serif=True))
        if s["note"]:
            nx = 32 + len(s["name"]) * 8.4 + 10
            p, _ = pill(nx, y + 18, s["note"], "var(--gld)", "var(--gldS)", 11.5, 8, 20)
            o.append(p)
        o.append(toggle(266, y + 18, s["on"]))
        o.append(chevron_button(343, y + 33))
        for i, ln in enumerate(s["lines"]):
            o.append(text(32, y + 58 + i * 17, ln, 13.5, "var(--ink3)"))
        y += ch + 12
    o.append(tab_bar(["Now", "Chat", "Skills", "Routines", "More"], "Skills"))
    return "".join(o)


SCREENS = [
    (screen_agents, "Your agents, awake or asleep",
     "The agents on your computer, each with the last thing it said and a Start or Stop button."),
    (screen_chat, "The conversation, and its buttons",
     "A conversation with an agent, where a drafted reply offers Send, Edit it, Send later and Dismiss."),
    (screen_skills, "What an agent is made of",
     "The skills an agent is made of, each with a switch to turn it on or off."),
]


# ── assembly ─────────────────────────────────────────────────────────────────────────────
# Two theme blocks, because these are drawings of an app that has both and the page is read
# in both. Same token names the rest of the site uses, so a mock never invents a colour.
THEME = (
    '<style>.mk{--bg:#FCFAF8;--card:#FFFFFF;--ink:#44403B;--ink2:#69645D;--ink3:#6D6861;'
    '--bd:#EAE6E1;--acc:#E08A5B;--accS:#FBE4D3;--grn:#679B55;--grnS:rgba(103,155,85,.14);'
    '--grnF:#4E7D3F;--redF:#BC5145;--gld:#8C6820;--gldS:rgba(187,140,51,.14);'
    '--soft:rgba(68,64,59,.04);--soft2:rgba(68,64,59,.12);--ls:rgba(68,64,59,.16);--shell:#2E2C29}'
    ':root[data-theme="dark"] .mk{--bg:#1A1A19;--card:#2B2B29;--ink:#F3F0ED;--ink2:#AEACA6;'
    '--ink3:#ACA8A3;--bd:#3F3E3A;--acc:#EDA277;--accS:#453629;--grn:#8FC47B;'
    '--grnS:rgba(143,196,123,.16);--grnF:#4E7440;--redF:#B0503F;--gld:#DCAF57;--gldS:rgba(220,175,87,.16);'
    '--soft:rgba(243,240,237,.05);--soft2:rgba(243,240,237,.14);--ls:rgba(243,240,237,.16);'
    '--shell:#4A4844}</style>'
)


def phone(body, ox, oy):
    cid = uid("sc")
    return ('<g transform="translate(%s,%s)">' % (f(ox), f(oy))
            + rect(-SHELL_PAD, -SHELL_PAD, W + SHELL_PAD * 2, H + SHELL_PAD * 2, 52, "var(--shell)")
            + '<defs><clipPath id="%s">%s</clipPath></defs>' % (
                cid, rect(0, 0, W, H, 42, "#000"))
            + '<g clip-path="url(#%s)">' % cid
            + rect(0, 0, W, H, 42, "var(--bg)") + body + "</g></g>")


def build():
    _n[0] = 0
    caption_y = 856.0

    # desktop: the trio, side by side
    parts = []
    titles = []
    for i, (fn, cap, desc) in enumerate(SCREENS):
        ox = 41.0 + i * 460.0
        parts.append(phone(fn(), ox, 11.0))
        parts.append(text(ox + W / 2, caption_y, cap, 21, "currentColor", "500", "middle"))
        titles.append(desc)
    desk = ('<svg class="mk explain-svg--desktop" viewBox="0 0 1392 884" role="img"'
            ' aria-labelledby="mockt-desktop" xmlns="http://www.w3.org/2000/svg"'
            ' style="max-width:960px;font-family:inherit">' + THEME
            + '<title id="mockt-desktop">Three screens from Archie Mobile. %s</title>'
            % esc(" ".join(titles)) + "".join(parts) + "</svg>")

    # mobile: one per gallery item
    items = []
    for i, (fn, cap, desc) in enumerate(SCREENS):
        tid = "mkg%d" % (i + 1)
        svg = ('<svg class="mk" viewBox="0 0 412 874" role="img" aria-labelledby="%s"'
               ' xmlns="http://www.w3.org/2000/svg" style="font-family:inherit">' % tid
               + THEME + '<title id="%s">%s</title>' % (tid, esc(desc))
               + phone(fn(), 11.0, 11.0)
               + text(206, caption_y, cap, 21, "currentColor", "500", "middle") + "</svg>")
        items.append('<div class="screenshot-gallery-item">%s</div>' % svg)

    gallery = ('<div class="screenshot-gallery mk-gallery" data-pps="30"'
               ' aria-label="Three screens from Archie Mobile">'
               '<div class="screenshot-gallery-track">' + "".join(items) + "</div></div>")

    return "            " + desk + "\n            " + gallery


def main():
    check = "--check" in sys.argv
    html = open(PAGE, encoding="utf-8").read()
    block = BEGIN + "\n" + build() + "\n            " + END
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if pat.search(html):
        new = pat.sub(lambda _: block, html, count=1)
    else:
        # first run: swallow the hand-written figure contents
        old = re.compile(r'(<figure class="explain-figure fade-up delay-2">\s*).*?(\s*</figure>)', re.S)
        if not old.search(html):
            print("gen-phone-mocks: cannot find the figure to replace")
            return 1
        new = old.sub(lambda m: m.group(1) + block + m.group(2), html, count=1)

    if new == html:
        print("gen-phone-mocks: clean. 3 screens, 2 renderings.")
        return 0
    if check:
        print("gen-phone-mocks: archie/mobile/ is out of date. Run scripts/gen-phone-mocks.py")
        return 1
    open(PAGE, "w", encoding="utf-8").write(new)
    print("gen-phone-mocks: wrote 3 screens as the desktop trio and the mobile gallery.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
