/* Write the Archie Learning Library into learn/<slug>/, one page per section, from assets/library.json.
 *
 * WHAT A PAGE IS (Jett, 2026-09-30). Each section of a level is its own video and its own page:
 * the video from YouTube behind a press, the section's notes directly under it, previous and next,
 * the words Jack reads, and the whole library down the side so any section is one press away.
 * TRUST.md's library entry governs all of it; the parts that bind this file:
 *
 *   - Nothing reaches YouTube until the reader presses play. The page shows our own poster
 *     (assets/learn/<slug>.jpg) inside a plain link to the video on youtube.com, and js/library.js
 *     swaps that link for the youtube-nocookie player on the press. Without scripts the link
 *     simply goes to YouTube, which is also the reader's choice. The CSP opens frame-src to
 *     youtube-nocookie on these pages only (scripts/gen-csp.py, LIBRARY_SOURCES).
 *   - The notes box sits directly under the player, because TRUST.md lets the narration point
 *     "below this video" at a figure only while the box is on the same page, right there, and says
 *     it. Notes carry FACTS.md figures and TRUST.md wording and nothing else.
 *   - "Read by Jack." is the line under every player, true only while he read it.
 *
 * WHEN A SECTION IS PUBLISHED. When it has a YouTube id and no hold. Every other section is left
 * out everywhere, including the side list and previous and next, so no page links to one that is
 * not there. A hold says why in words, and only Jett clears it.
 *
 * THE CHROME. The head, the three copies of the menu, and the footer are copied from a live page
 * at generation time (CHROME below), never kept in a template here, so a menu sweep across the
 * site can never leave these pages behind: a sweep edits these pages too, and --check says so if
 * the two ever disagree. The CSP tag is the one thing gen-csp.py writes afterwards, so --check
 * ignores it.
 *
 * Usage:
 *   node scripts/gen-library.mjs             write the published pages, remove unpublished ones
 *   node scripts/gen-library.mjs --check     exit 1 if any page is out of date
 *   node scripts/gen-library.mjs --preview   write every section, held or not, with a stand-in
 *                                            video id, for looking at locally. Never commit it.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DATA = path.join(ROOT, "assets", "library.json");
const OUT = path.join(ROOT, "learn");
const CHROME = path.join(ROOT, "compare", "questions-to-ask", "index.html");
const BANNER = "<!-- GENERATED by scripts/gen-library.mjs from assets/library.json. Do not hand-edit. -->";
const CSP_RE = /[ \t]*<!-- CSP: generated by scripts\/gen-csp\.py[^\n]*\n[ \t]*<meta http-equiv="Content-Security-Policy"[^>]*>\n/;

const esc = (t) => String(t).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
/* The data's strings are already HTML (entities and a few links), so attributes get them with the
   tags taken off and nothing escaped twice. */
const plain = (html) => html.replace(/<[^>]+>/g, "");
const attr = (html) => plain(html).replace(/"/g, "&quot;");

function chrome() {
  const src = fs.readFileSync(CHROME, "utf8");
  const cssLine = src.match(/[ \t]*<link rel="stylesheet" href="\.\.\/\.\.\/css\/styles\.css\?v=([^"]+)" \/>\n/);
  if (!cssLine) throw new Error("no stylesheet link in " + CHROME);
  const stamp = cssLine[1];
  const head = src.slice(0, cssLine.index + cssLine[0].length);
  const bodyStart = src.indexOf("<body>");
  const mainStart = src.indexOf('  <main id="main">');
  const mainEnd = src.indexOf("  </main>\n");
  if (bodyStart < 0 || mainStart < 0 || mainEnd < 0) throw new Error("landmarks missing in " + CHROME);
  const top = src.slice(bodyStart, mainStart);
  let tail = src.slice(mainEnd + "  </main>\n".length);
  // The chrome page's own player script is not ours; the library's is.
  tail = tail.replace(/[ \t]*<script src="\.\.\/\.\.\/js\/demo-player\.js\?v=[^"]+"><\/script>\n/, "");
  tail = tail.replace("</body>", `  <script src="../../js/library.js?v=${stamp}"></script>\n</body>`);
  return { head, top, tail, stamp };
}

/* The length as a person says it: an intro is "under a minute", the rest "about 1 minute" and up.
   Rounded, so a trim in the edit does not make it wrong. */
function length(s) {
  const sec = s.seconds || 60;
  if (sec < 45) return "under a minute";
  const m = Math.round(sec / 60);
  return m === 1 ? "about 1 minute" : `about ${m} minutes`;
}

/* How a section is named: "0.1" in the list's number column and before its title elsewhere; a
   level's intro is "Intro" in the column and "Level 0:" before its title, since its title is the
   level's own name. */
const intro = (s) => s.n.endsWith(".0");
const num = (s) => (intro(s) ? "Intro" : s.n);
const named = (s) => (intro(s) ? `Level ${s.level}: ${s.title}` : `${s.n} ${s.title}`);

function page(s, all, levels, C, preview) {
  const lv = levels.find((l) => l.n === s.level);
  const i = all.indexOf(s);
  const prev = all[i - 1], next = all[i + 1];
  const id = preview ? "PREVIEW" : s.youtube;
  const title = `${plain(s.title)} | Learning Library | Otian AI`;
  const desc = `${plain(s.lede)} A short video, read by Jack.`;
  let head = C.head
    .replace(/<title>[^<]*<\/title>/, `<title>${esc(title)}</title>`)
    .replace(/<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${attr(desc)}" />`)
    .replace(/<meta property="og:image" content="[^"]*" \/>/, `<meta property="og:image" content="https://otianai.com/assets/learn/${s.slug}.jpg" />`)
    .replace(/<meta name="twitter:card" content="[^"]*" \/>/, `<meta name="twitter:card" content="summary_large_image" />`);
  if (preview) head = head.replace("<head>", '<head>\n  <meta name="robots" content="noindex" />');

  const index = levels
    .filter((l) => all.some((x) => x.level === l.n))
    .map((l) => {
      const items = all.filter((x) => x.level === l.n).map((x) =>
        `<li><a href="../${x.slug}/"${x === s ? ' aria-current="page"' : ""}><span class="lib-n">${esc(num(x))}</span><span>${x.title}</span></a></li>`).join("\n              ");
      return `<details class="lib-level"${l.n === s.level ? " open" : ""}>
            <summary>Level ${l.n}: ${esc(l.title)}</summary>
            <ol>
              ${items}
            </ol>
          </details>`;
    }).join("\n          ");

  const step = (x, rel, word) => x
    ? `<a class="lib-step-${rel}" rel="${rel}" href="../${x.slug}/"><span class="lib-step-w">${word}</span><span class="lib-step-t">${named(x)}</span></a>`
    : "";

  const notes = s.notes && s.notes.length
    ? `
        <section class="lib-notes" aria-labelledby="lib-notes-h">
          <h2 id="lib-notes-h">${s.notes_heading}</h2>
          <ul>
            ${s.notes.map((n) => `<li>${n}</li>`).join("\n            ")}
          </ul>
        </section>`
    : "";

  const words = s.words.map((p) => `<p>${esc(p)}</p>`).join("\n            ");
  const playLabel = `Play the video: ${plain(s.title)}, ${length(s)}`;

  const main = `  <main id="main" class="lib">
    ${BANNER}
    <div class="lib-wrap">
      <article class="lib-main">
        <p class="section-label">Learning Library &middot; Level ${s.level}: ${esc(lv.title)}</p>
        <h1 class="lib-h1"><span class="lib-h1-n">${intro(s) ? `Level ${s.level}:` : s.n}</span> ${s.title}</h1>
        <p class="lib-lede">${s.lede}</p>

        <figure class="lib-player">
          <a class="lib-play" href="https://www.youtube.com/watch?v=${esc(id)}" data-yt="${esc(id)}" data-title="${attr(s.title)}" aria-label="${attr(playLabel)}">
            <img src="../../assets/learn/${s.slug}.jpg" width="1280" height="720" alt="" />
            <span class="lib-play-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M8 5.5v13l11-6.5z" fill="currentColor"/></svg></span>
          </a>
          <figcaption>Read by Jack. Pressing play on a video in the library loads YouTube&rsquo;s player, and YouTube counts that play.</figcaption>
        </figure>
${notes}
        <nav class="lib-step" aria-label="Previous and next video">
          ${step(prev, "prev", "Previous")}
          ${step(next, "next", "Next")}
        </nav>

        <details class="lib-words">
          <summary>Read what Jack says in ${intro(s) ? `the Level ${s.level} intro` : s.n}</summary>
          <blockquote class="lib-words-body">
            ${words}
          </blockquote>
        </details>
      </article>

      <nav class="lib-index" aria-label="Learning Library">
        <p class="lib-index-t">Learning Library</p>
          ${index}
      </nav>
    </div>
  </main>
`;
  return head + STYLE + "</head>\n" + C.top + main + C.tail;
}

/* The library's own rules, in the page like compare/questions-to-ask/'s, so a change here never
   needs the whole site's asset stamp moved. Colors are the site's tokens only. */
const STYLE = `  <style>
    /* ── The Learning Library (learn/<slug>/, 2026-09-30), written by scripts/gen-library.mjs ── */
    .lib { padding-block: clamp(96px, 12vw, 132px) 72px; }
    .lib-wrap { width: min(1180px, 100% - 32px); margin-inline: auto; display: grid; gap: 40px; grid-template-columns: minmax(0, 1fr) 300px; align-items: start; }
    .lib-main { min-width: 0; display: grid; gap: 20px; }
    .lib-h1 { margin: 0; font-size: clamp(1.9rem, 1.2rem + 2.2vw, 2.75rem); line-height: 1.15; text-wrap: balance; }
    .lib-h1-n { color: var(--accent); font-variant-numeric: tabular-nums; }
    .lib-lede { margin: 0; max-width: 62ch; color: var(--text-secondary); font-size: var(--fs-xl); }
    .lib-player { margin: 8px 0 0; display: grid; gap: 10px; }
    .lib-play, .lib-frame { position: relative; display: block; width: 100%; aspect-ratio: 16 / 9; border: 0; border-radius: 16px; overflow: hidden; background: #1c1916; box-shadow: var(--shadow-md); }
    .lib-play img { display: block; width: 100%; height: 100%; object-fit: cover; }
    .lib-play-mark { position: absolute; left: 50%; top: 80%; width: 84px; height: 84px; margin: -42px 0 0 -42px; border-radius: 50%; display: grid; place-items: center; background: var(--accent); color: #fff; box-shadow: var(--shadow-sm); transition: transform 0.2s ease; }
    .lib-play-mark svg { width: 38px; height: 38px; margin-left: 4px; }
    .lib-play:hover .lib-play-mark, .lib-play:focus-visible .lib-play-mark { transform: scale(1.08); }
    .lib-play:focus-visible { outline: 3px solid var(--accent); outline-offset: 3px; }
    .lib-player figcaption { font-size: var(--fs-base); color: var(--text-secondary); }
    .lib-notes { padding: 22px 24px; border-radius: 14px; background: var(--bg-card, #fff); border: 1px solid var(--border, rgba(68, 64, 59, 0.12)); }
    .lib-notes h2 { margin: 0 0 10px; font-size: var(--fs-2xl); line-height: 1.3; }
    .lib-notes ul { margin: 0; padding-left: 1.2em; display: grid; gap: 8px; list-style: disc; }
    .lib-notes li { line-height: 1.5; }
    .lib-step { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .lib-step a { display: grid; gap: 2px; padding: 14px 16px; border-radius: var(--radius); border: 1px solid var(--border, rgba(68, 64, 59, 0.16)); text-decoration: none; color: inherit; }
    .lib-step a:hover { border-color: var(--accent); }
    .lib-step-next { grid-column: 2; text-align: right; }
    .lib-step-w { font-size: var(--fs-sm); font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase; color: var(--accent); }
    .lib-step-t { font-weight: 600; line-height: 1.3; }
    .lib-words summary { cursor: pointer; font-weight: 600; }
    /* Jack's words, quoted: a quote is his voice and not the page's, which check-voice.py honors. */
    .lib-words-body { max-width: 66ch; margin: 0; padding: 8px 0 0; border: 0; color: var(--text-secondary); font-style: normal; }
    .lib-words-body p { margin: 0 0 10px; }
    .lib-index { position: sticky; top: 96px; display: grid; gap: 6px; padding: 18px; border-radius: 14px; border: 1px solid var(--border, rgba(68, 64, 59, 0.16)); max-height: calc(100vh - 120px); overflow: auto; }
    .lib-index-t { margin: 0 0 4px; font-size: var(--fs-sm); font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; color: var(--text-secondary); }
    .lib-level summary { cursor: pointer; padding: 6px 0; font-weight: 600; }
    .lib-level ol { list-style: none; margin: 0 0 8px; padding: 0; display: grid; gap: 2px; }
    .lib-level a { display: grid; grid-template-columns: 3em 1fr; gap: 6px; padding: 7px 8px; border-radius: var(--radius-sm); text-decoration: none; color: inherit; font-size: var(--fs-md); line-height: 1.3; }
    .lib-level a:hover { background: var(--surface-hover, rgba(68, 64, 59, 0.06)); }
    .lib-level a[aria-current="page"] { background: var(--accent-subtle); box-shadow: inset 3px 0 0 var(--accent); font-weight: 600; }
    .lib-n { font-variant-numeric: tabular-nums; opacity: 0.8; }
    @media (max-width: 900px) {
      .lib-wrap { grid-template-columns: minmax(0, 1fr); }
      .lib-index { position: static; max-height: none; }
    }
    @media (max-width: 560px) {
      .lib-step { grid-template-columns: minmax(0, 1fr); }
      .lib-step-next { grid-column: auto; }
      .lib-play-mark { width: 56px; height: 56px; margin: -28px 0 0 -28px; }
      .lib-play-mark svg { width: 26px; height: 26px; }
    }
  </style>
`;

function main() {
  const check = process.argv.includes("--check");
  const preview = process.argv.includes("--preview");
  const { levels, sections } = JSON.parse(fs.readFileSync(DATA, "utf8"));
  const C = chrome();
  const all = preview ? sections : sections.filter((s) => s.youtube && !s.hold);
  const wanted = new Map(all.map((s) => [s.slug, page(s, all, levels, C, preview)]));

  /* The first player changes two things the site says about itself, on the same day (TRUST.md, the
     video library): the website entry gains the sentence about YouTube counting a play, and the
     privacy policy names YouTube among the outside resources. Publishing refuses until both do. */
  if (!preview && wanted.size) {
    const trust = fs.readFileSync(path.join(ROOT, "TRUST.md"), "utf8");
    const privacy = fs.readFileSync(path.join(ROOT, "privacy-policy", "index.html"), "utf8");
    const missing = [];
    if (!trust.includes("Pressing play on a video in the library loads YouTube")) missing.push("TRUST.md's website entry lacks the YouTube sentence");
    if (!/YouTube/.test(privacy)) missing.push("the privacy policy does not name YouTube");
    if (missing.length) {
      console.log("gen-library: not publishing, because " + missing.join(" and ") + ".");
      process.exit(1);
    }
  }

  const ours = fs.existsSync(OUT)
    ? fs.readdirSync(OUT, { withFileTypes: true })
        .filter((d) => d.isDirectory() && fs.existsSync(path.join(OUT, d.name, "index.html")) &&
          fs.readFileSync(path.join(OUT, d.name, "index.html"), "utf8").includes(BANNER))
        .map((d) => d.name)
    : [];
  const stale = ours.filter((slug) => !wanted.has(slug));
  const noCsp = (t) => t.replace(CSP_RE, "");
  let bad = 0;
  for (const [slug, html] of wanted) {
    const file = path.join(OUT, slug, "index.html");
    const have = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (have !== null && noCsp(have) === noCsp(html)) continue;
    if (check) { console.log("  out of date: learn/" + slug + "/"); bad++; continue; }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    // Keep the CSP gen-csp.py wrote, so a regeneration does not undo it.
    const csp = have && have.match(CSP_RE);
    fs.writeFileSync(file, csp ? html.replace(CSP_RE, csp[0]) : html);
    console.log("  wrote learn/" + slug + "/");
  }
  for (const slug of stale) {
    if (check) { console.log("  not published, still on disk: learn/" + slug + "/"); bad++; continue; }
    fs.rmSync(path.join(OUT, slug), { recursive: true });
    console.log("  removed learn/" + slug + "/");
  }
  const held = sections.filter((s) => s.hold).map((s) => `${s.n} (${s.hold})`);
  const waiting = sections.filter((s) => !s.youtube && !s.hold).length;
  if (check && bad) { console.log(`gen-library: ${bad} page(s) out of date. Run: node scripts/gen-library.mjs`); process.exit(1); }
  console.log(`gen-library: ${wanted.size} published, ${waiting} waiting for a YouTube id, ${held.length} held.`);
  for (const h of held) console.log("  held: " + h);
}

main();
