#!/usr/bin/env python3
"""gen-phone-mocks.py: the three Archie Mobile screens on archie/mobile/, drawn once.

The page shows three phone screens twice. Since 2026-09-18 the first showing is the stage:
one phone shell with all three screens inside it, one lit at a time as the reader scrolls,
the way the homepage's phone changes screens (js/mobile.js drives it). The second is the
stills, three separate drawings in a row, which is what a reader with reduced motion or no
JavaScript gets under the stage's captions. Until 2026-09-14 the page carried six
hand-written SVGs of the same three screens, and a styling change meant six edits, which is
how two halves drift: a card radius fixed in one and missed in the other reads as a bug
nobody can find. Until 2026-09-18 the second showing was a marquee (.mk-gallery); it went
when the stage took over the narrow layout, because the reader the stills are now for has
asked for no motion.

So the screens live here, as content plus components, and this writes both renderings into
the page between markers. Same arrangement as gen-marketplace.mjs and gen-blog.mjs: the
result is committed, and --check is what stops the committed markup drifting from its source.

BEATS. On the stage, pieces of a screen land as the scroll passes them: the conversation's
replies and its draft, the skills one card at a time. A screen builder marks a piece with
beat(markup, at), and what that does depends on the rendering being drawn: nothing in the
stills, where the whole screen is the resting state a crawler reads, and a day-beat group in
the stage, which js/mobile.js lights when the act's scroll reaches `at`. The same builder
draws both, so a piece can never be on one and missing from the other.

WHAT IT IS AND IS NOT. These are drawings of the app, not screenshots of it, and the
distinction is load-bearing: the app is in testing and its screens still move. What the
drawings owe the reader is that every element on them is one the app actually has, doing
what the app actually does. The styling was brought to the shipping app's on 2026-09-14
from screenshots of the real build: the status bar, the header with its wordmark and agent
picker, the stacked action card under a draft, the per-skill toggle and chevron, the tab
bars and their counts. The CONTENT is the site's own and stays that way, because the real
screens carry a real person's mail.

WIDTHS ARE MEASURED, NOT GUESSED. Anything drawn around a string is sized from the string,
through tw() and the advance tables under it. The version that shipped first used
len(s) * 6.4, which is the kind of estimate that is wrong in both directions on the same
screen: it left a sentence sitting off to one side of a bubble 25px too wide for it, and it
drew the draft's container narrower than the two lines inside it, which ran out the side.

    python3 scripts/gen-phone-mocks.py           write the page
    python3 scripts/gen-phone-mocks.py --check   fail if the page is out of date
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "archie", "mobile", "index.html")

BEGIN = "<!-- BEGIN phone mocks: generated by scripts/gen-phone-mocks.py. Do not hand-edit. -->"
END = "<!-- END phone mocks -->"
STAGE_BEGIN = "<!-- BEGIN phone stage: generated by scripts/gen-phone-mocks.py. Do not hand-edit. -->"
STAGE_END = "<!-- END phone stage -->"

# The screen is 390x800 inside a 412x822 shell, which is the geometry the page already used
# and the reason the outer viewBoxes below are unchanged.
W, H = 390.0, 800.0
SHELL_PAD = 11.0

# Vertical bands, top to bottom. The app's own proportions: a status bar, a header with a
# hairline under it, the scrolling content, then the tab bar pinned to the bottom.
STATUS_H = 52.0
HEAD_H = 52.0
HEAD_RULE = STATUS_H + HEAD_H          # 104
TABBAR_Y = 722.0
COMPOSER_Y = 660.0        # the chat screen's input bar, drawn at a fixed height

# ── ids ──────────────────────────────────────────────────────────────────────────────────
# Every gradient and clipPath needs an id unique across the whole page, because the desktop
# trio puts three screens in one <svg> and the browser resolves url(#x) document-wide.
_n = [0]


def uid(p):
    _n[0] += 1
    return "%s%d" % (p, _n[0])


def esc(t):
    return (t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace("’", "&rsquo;").replace("·", "&middot;"))


def f(v):
    """Trim floats so the markup does not carry 14 decimals of nothing."""
    s = "%.1f" % float(v)
    return s[:-2] if s.endswith(".0") else s


# ── beats ────────────────────────────────────────────────────────────────────────────────
# Which act the screen being drawn belongs to on the stage, or None while the stills are
# being drawn. See BEATS in the docstring.
_beat = {"act": None}


def beat(markup, at):
    if _beat["act"] is None:
        return markup
    return '<g class="day-beat" data-act="%d" data-at="%s">%s</g>' % (
        _beat["act"], ("%.2f" % at).rstrip("0").rstrip("."), markup)


# ── text metrics ─────────────────────────────────────────────────────────────────────────
# Advance widths per 1000 units, so anything drawn around a string can be sized from the
# string. What was here before was len(s) * 6.4, and it is wrong in both directions at once:
# the bubble around "Anything from the accountant?" came out 25px wider than the sentence and
# left it sitting off to one side, while the container around the draft came out narrower
# than the two lines inside it and they ran out the side of it. Inter is what the page sets
# and the drawings inherit; names inside them are Georgia, so both are measured.
SERIF = "Georgia,'Times New Roman',serif"

_INTER = {
    " ": 260, "a": 543, "b": 585, "c": 511, "d": 585, "e": 553, "f": 340, "g": 585,
    "h": 570, "i": 245, "j": 245, "k": 530, "l": 245, "m": 870, "n": 570, "o": 580,
    "p": 585, "q": 585, "r": 375, "s": 500, "t": 355, "u": 570, "v": 505, "w": 780,
    "x": 505, "y": 505, "z": 470,
    "A": 664, "B": 654, "C": 682, "D": 700, "E": 590, "F": 578, "G": 712, "H": 718,
    "I": 273, "J": 522, "K": 645, "L": 559, "M": 883, "N": 726, "O": 744, "P": 632,
    "Q": 744, "R": 646, "S": 630, "T": 601, "U": 705, "V": 664, "W": 999, "X": 632,
    "Y": 605, "Z": 606,
    ".": 290, ",": 290, ":": 290, ";": 290, "!": 290, "?": 510, "'": 222, "\u2019": 222,
    "-": 360, "\u00b7": 360, "/": 420, "(": 350, ")": 350, "&": 660, "+": 600, "%": 800,
}

_GEORGIA = {
    " ": 240, "a": 512, "b": 555, "c": 445, "d": 556, "e": 468, "f": 331, "g": 500,
    "h": 566, "i": 264, "j": 297, "k": 530, "l": 264, "m": 843, "n": 566, "o": 528,
    "p": 555, "q": 543, "r": 400, "s": 396, "t": 340, "u": 566, "v": 484, "w": 738,
    "x": 490, "y": 484, "z": 420,
    "A": 723, "B": 649, "C": 673, "D": 730, "E": 640, "F": 597, "G": 728, "H": 787,
    "I": 377, "J": 400, "K": 726, "L": 611, "M": 934, "N": 748, "O": 745, "P": 590,
    "Q": 745, "R": 680, "S": 570, "T": 638, "U": 735, "V": 723, "W": 1035, "X": 703,
    "Y": 668, "Z": 599,
    ".": 275, ",": 275, ":": 275, ";": 275, "!": 275, "?": 435, "'": 213, "\u2019": 213,
    "-": 348, "\u00b7": 348, "/": 420, "(": 350, ")": 350, "&": 780, "+": 600, "%": 800,
}


def tw(s, size, serif=False, weight="400"):
    """How wide that string is, drawn. Estimated, and deliberately a little generous:
    the fallback stack is wider than Inter, and every caller uses this to decide how much
    room to leave, so erring narrow is the one direction that shows."""
    table = _GEORGIA if serif else _INTER
    digit = 622 if serif else 600
    units = 0
    for ch in s:
        # An emoji draws from the system's colour font at about an em and a quarter, and the
        # variation selector and joiner beside one draw nothing at all.
        if ch in ("\ufe0f", "\u200d"):
            continue
        if ord(ch) >= 0x2300:
            units += 1250
            continue
        units += digit if ch.isdigit() else table.get(ch, 560)
    w = units * float(size) / 1000.0
    return w * 1.035 if weight in ("500", "600", "700") else w * 1.01


# ── primitives ───────────────────────────────────────────────────────────────────────────


def rect(x, y, w, h, r=0, fill="none", stroke=None, sw=1, extra=""):
    s = '<rect x="%s" y="%s" width="%s" height="%s"' % (f(x), f(y), f(w), f(h))
    if r:
        s += ' rx="%s"' % f(r)
    s += ' fill="%s"' % fill
    if stroke:
        s += ' stroke="%s" stroke-width="%s"' % (stroke, f(sw))
    return s + extra + "/>"


def text(x, y, t, size=13.5, fill="var(--ink)", weight="400", anchor="start", serif=False):
    s = '<text x="%s" y="%s" font-size="%s" fill="%s" font-weight="%s" text-anchor="%s"' % (
        f(x), f(y), f(size), fill, weight, anchor)
    if serif:
        s += ' font-family="%s"' % SERIF
    return s + ">%s</text>" % esc(t)


def circle(cx, cy, r, fill="none", stroke=None, sw=1):
    s = '<circle cx="%s" cy="%s" r="%s" fill="%s"' % (f(cx), f(cy), f(r), fill)
    if stroke:
        s += ' stroke="%s" stroke-width="%s"' % (stroke, f(sw))
    return s + "/>"


def line(x1, y1, x2, y2, stroke="var(--bd)", sw=1):
    return '<line x1="%s" y1="%s" x2="%s" y2="%s" stroke="%s" stroke-width="%s"/>' % (
        f(x1), f(y1), f(x2), f(y2), stroke, f(sw))


def icon(paths, x, y, scale=1.0, stroke="var(--ink3)", fill="none", sw=1.8):
    """A 24x24 stroked glyph, the same vocabulary the app's tab bar and rows use."""
    return ('<g transform="translate(%s,%s) scale(%s)" fill="%s" stroke="%s" stroke-width="%s"'
            ' stroke-linecap="round" stroke-linejoin="round">%s</g>') % (
        f(x), f(y), "%.4f" % scale, fill, stroke, f(sw), paths)


# ── the Ember faces, lifted from the app's own marks ──────────────────────────────────────
# A face is drawn in a 200x200 space and scaled into a circle of radius r, so the call site
# only says where and how big. Colours and accessories per agent, the way the app deals them
# from the agent itself, so two agents never look like twins.
FACES = {
    "ember":  dict(hi="#F0AB80", mid="#E28D5E", lo="#C36A3D", eyes="oval", extra="hat"),
    "teal":   dict(hi="#63B2A9", mid="#3E9A92", lo="#2E7C75", eyes="round", extra="glasses"),
    "gold":   dict(hi="#D3A855", mid="#BB8C33", lo="#9A7226", eyes="oval", extra="antenna"),
}


def face_body(kind):
    c = FACES[kind]
    g = uid("em")
    o = ['<defs><linearGradient id="%s" x1="0" y1="0.18" x2="0" y2="1">'
         '<stop offset="0" stop-color="%s"/><stop offset="0.55" stop-color="%s"/>'
         '<stop offset="1" stop-color="%s"/></linearGradient></defs>' % (g, c["hi"], c["mid"], c["lo"])]
    o.append('<ellipse cx="82" cy="169" rx="10" ry="7.5" fill="%s"/>' % c["lo"])
    o.append('<ellipse cx="118" cy="169" rx="10" ry="7.5" fill="%s"/>' % c["lo"])
    if c["extra"] == "hat":
        o.append('<path d="M100 30 L87 58 L113 58 Z" fill="%s" stroke="%s" stroke-width="8"'
                 ' stroke-linejoin="round"/>' % (c["lo"], c["lo"]))
    if c["extra"] == "antenna":
        o.append('<path d="M100 52 L100 34" stroke="%s" stroke-width="7" stroke-linecap="round"/>' % c["lo"])
        o.append('<circle cx="100" cy="27" r="9" fill="%s"/>' % c["lo"])
    o.append('<circle cx="100" cy="108" r="60" fill="url(#%s)"/>' % g)
    o.append('<ellipse cx="65" cy="125" rx="8.5" ry="5" fill="%s" opacity=".38"/>' % c["lo"])
    o.append('<ellipse cx="135" cy="125" rx="8.5" ry="5" fill="%s" opacity=".38"/>' % c["lo"])
    for ex in (78, 122):
        if c["eyes"] == "oval":
            eye = ('<rect x="-7" y="-14" width="14" height="28" rx="7" fill="#2A2521"/>'
                   '<circle cx="-2.5" cy="-7" r="2.5" fill="#FFF" opacity=".85"/>')
        else:
            eye = ('<circle cx="0" cy="0" r="10" fill="#2A2521"/>'
                   '<circle cx="-3" cy="-3.5" r="3" fill="#FFF" opacity=".85"/>')
        o.append('<g transform="translate(%d,103)">%s</g>' % (ex, eye))
    o.append('<path d="M93 132 Q100 138 107 132" stroke="#2A2521" stroke-width="3.2" fill="none"'
             ' stroke-linecap="round"/>')
    if c["extra"] == "glasses":
        o.append('<g fill="none" stroke="#2A2521" stroke-width="3.4" opacity=".85">'
                 '<circle cx="78" cy="103" r="17"/><circle cx="122" cy="103" r="17"/>'
                 '<path d="M95 103h10" stroke-linecap="round"/></g>')
    if c["extra"] == "antenna":
        o.append('<g fill="%s" opacity=".55"><circle cx="60" cy="118" r="2.6"/>'
                 '<circle cx="68" cy="126" r="2.6"/><circle cx="56" cy="130" r="2.6"/>'
                 '<circle cx="140" cy="118" r="2.6"/><circle cx="132" cy="126" r="2.6"/>'
                 '<circle cx="144" cy="130" r="2.6"/></g>' % c["lo"])
    return "".join(o)


def avatar(cx, cy, r, kind, dot=False):
    cid = uid("fc")
    o = ['<defs><clipPath id="%s"><circle cx="%s" cy="%s" r="%s"/></clipPath></defs>' % (
        cid, f(cx), f(cy), f(r))]
    o.append(circle(cx, cy, r, "var(--accS)"))
    o.append('<g clip-path="url(#%s)"><g transform="translate(%s,%s) scale(%s)">%s</g></g>' % (
        cid, f(cx - r), f(cy - r), "%.4f" % (r / 100.0), face_body(kind)))
    if dot:
        # the app puts a presence dot on the agent in the header, and it is the one place
        # "running" is stated without a word for it
        o.append(circle(cx + r * 0.72, cy + r * 0.72, r * 0.26, "var(--grn)", "var(--bg)", 1.5))
    return "".join(o)


# ── the Archie wordmark ──────────────────────────────────────────────────────────────────
def wordmark(x, y, scale=0.02867):
    """78 wide on the homepage phone's 393 screen (.dp-topbar .wm), so 77 on this 390 one. It was
    66 until 2026-09-18, which read as small beside the homepage's (Jett)."""
    a, b = uid("wm"), uid("wm")
    return ('<g transform="translate(%s,%s) scale(%s)"><defs>'
            '<linearGradient id="%s" gradientUnits="userSpaceOnUse" x1="512" y1="85" x2="512" y2="888">'
            '<stop offset="0" stop-color="#F0AB80"/><stop offset="0.55" stop-color="#E28D5E"/>'
            '<stop offset="1" stop-color="#C36A3D"/></linearGradient>'
            '<linearGradient id="%s" x1="0" y1="0" x2="0" y2="1">'
            '<stop offset="0" stop-color="#EFA97E"/><stop offset="1" stop-color="#C36A3D"/>'
            '</linearGradient></defs><g transform="translate(-190,-35)">'
            '<polygon fill="url(#%s)" stroke="url(#%s)" stroke-width="34" stroke-linejoin="round"'
            ' stroke-linecap="round" points="328,887 512,727 696,887"/>'
            '<path fill="url(#%s)" stroke="url(#%s)" stroke-width="34" stroke-linejoin="round"'
            ' stroke-linecap="round" fill-rule="evenodd"'
            ' d="M 512,85 L 824,850 L 512,712 L 200,850 Z M 512,272 L 384,616 L 640,616 Z"/></g>'
            '<text x="690" y="690" font-family="Georgia,serif" font-size="590" font-weight="bold"'
            ' fill="url(#%s)" dominant-baseline="middle">rchie</text></g>') % (
        f(x), f(y), "%.5f" % scale, a, b, a, a, a, a, b)


# ── chrome ───────────────────────────────────────────────────────────────────────────────
def status_bar(clock="7:00"):
    """The phone's own bar. Nothing here is Archie: it is what makes the rest read as a phone.

    Everything sits on one midline with matching margins left and right, laid out from the
    right edge in: battery, wifi, signal. A silenced-bell glyph used to sit beside the clock
    because the drawings are quiet ones; it read as a thing that had happened to the phone,
    which is a fact about nothing, so it is gone.

    The clock reads 7:00, which is the homepage's morning brief and the site's own hour. It read
    9:41 until 2026-09-17: the time Apple stops every clock in its own marketing, and the plainest
    way a drawing of a generic phone tells a reader it is meant to be an iPhone. The drawing is
    ours and so is the hour on it.
    """
    mid = 30.0
    o = [text(30, mid + 5.4, clock, 15, "var(--ink)", "600")]

    # battery, its right edge 30 in from the screen edge, to match the clock's 30. Full, and so
    # are the bars below, because a drawing is not a phone that happens to be at 65% (Jett,
    # 2026-09-18); the homepage's phone and the kit it is ported from say the same.
    o.append(rect(332, mid - 6.2, 26, 12.4, 4.2, "none", "var(--ink)", 1.2, ' opacity=".4"'))
    o.append(rect(358.9, mid - 2.4, 1.8, 4.8, 0.9, "var(--ink)", extra=' opacity=".28"'))
    o.append(rect(334.4, mid - 4.2, 21.2, 8.4, 2.2, "var(--ink)"))

    # wifi, two arcs over a dot
    o.append('<g transform="translate(308,%s)" fill="none" stroke="var(--ink)" stroke-width="1.9"'
             ' stroke-linecap="round"><path d="M0.4,5.4 Q8,-1.6 15.6,5.4"/>'
             '<path d="M3.6,8.8 Q8,4.5 12.4,8.8"/></g>' % f(mid - 8))
    o.append(circle(316, mid + 4.4, 1.7, "var(--ink)"))

    # signal, four bars standing on the same baseline as the clock, all of them lit
    for i in range(4):
        h = 4.4 + i * 2.4
        o.append(rect(279 + i * 5.8, mid + 5.6 - h, 3.6, h, 1.3, "var(--ink)"))
    return "".join(o)


def header_agent(name, kind):
    """Wordmark left, then the agent you are talking to, with the picker chevron after it."""
    nw = tw(name, 17, serif=True)
    block = 30 + 9 + nw + 5 + 11          # avatar, gap, name, gap, chevron
    x = (W - block) / 2 + 10              # off true centre, so it clears the wordmark
    o = [wordmark(16, STATUS_H + 5)]
    o.append(avatar(x + 15, STATUS_H + 26, 15, kind, dot=True))
    o.append(text(x + 39, STATUS_H + 32, name, 17, "var(--ink)", "400", serif=True))
    o.append(icon('<path d="M4 8l6 6 6-6"/>', x + 39 + nw + 3, STATUS_H + 20,
                  0.58, "var(--ink2)", sw=2.4))
    o.append(line(0, HEAD_RULE, W, HEAD_RULE))
    return "".join(o)


def header_list(title, chip):
    """Wordmark left, the screen's name centred, and which computer you are looking at."""
    o = [wordmark(16, STATUS_H + 5)]
    o.append(text(W / 2, STATUS_H + 32, title, 18, "var(--ink)", "400", "middle", serif=True))
    cw = tw(chip, 13, weight="500") + 24
    o.append(rect(W - 16 - cw, STATUS_H + 13, cw, 28, 14, "var(--soft)", "var(--bd)", 1))
    o.append(text(W - 16 - cw / 2, STATUS_H + 31.5, chip, 13, "var(--ink2)", "500", "middle"))
    o.append(line(0, HEAD_RULE, W, HEAD_RULE))
    return "".join(o)


TAB_ICONS = {
    # Keyed by the label the phone shows, so a rename here is a rename of the key too. The bar
    # read Now and Work until 2026-09-21, when the app renamed both to follow the desktop.
    "Dashboard": '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    "Chat": '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',
    "Skills": '<path d="M12 3v4M12 17v4M5 12H1M23 12h-4M6.3 6.3 4 4M20 20l-2.3-2.3M17.7 6.3 20 4M4 20l2.3-2.3"/><circle cx="12" cy="12" r="3"/>',
    "Routines": '<circle cx="12" cy="12" r="10"/><path d="M12 6.4v5.6l3.5 2.3"/>',
    "More": '<circle cx="5.5" cy="12" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="18.5" cy="12" r="1.6"/>',
    "Agents": '<circle cx="12" cy="9" r="3.4"/><path d="M 5.5 19.2 C 5.5 15.5 8.4 13.6 12 13.6 C 15.6 13.6 18.5 15.5 18.5 19.2"/>',
    "Tasks": '<rect x="3" y="3" width="5" height="18" rx="1.5"/><rect x="10" y="3" width="5" height="12" rx="1.5"/><rect x="17" y="3" width="4" height="8" rx="1.5"/>',
    "Marketplace": '<path d="M4 8h16l-1.2 12.5H5.2z"/><path d="M8.6 8V6.2a3.4 3.4 0 0 1 6.8 0V8"/>',
    "Settings": '<rect x="6" y="2.5" width="12" height="19" rx="2.6"/><path d="M10.6 18.6h2.8"/>',
}


def tab_bar(tabs, active):
    o = [rect(0, TABBAR_Y, W, H - TABBAR_Y, 0, "var(--card)"), line(0, TABBAR_Y, W, TABBAR_Y)]
    step = W / len(tabs)
    for i, name in enumerate(tabs):
        cx = step * (i + 0.5)
        on = name == active
        col = "var(--acc)" if on else "var(--ink3)"
        o.append(icon(TAB_ICONS[name], cx - 11, TABBAR_Y + 12, 0.9167, col, sw=1.8))
        o.append(text(cx, TABBAR_Y + 48, name, 12, col, "600" if on else "500", "middle"))
    return "".join(o)


def pill(x, y, label, fg, bg, size=12.5, pad=11, h=22):
    w = tw(label, size, weight="600") + pad * 2
    return (rect(x, y, w, h, h / 2, bg)
            + text(x + pad, y + h / 2 + size * 0.34, label, size, fg, "600")), w


def toggle(x, y, on):
    """The app's switch: ember when on, a quiet fill when off.

    Sized to the row it sits in rather than to itself. At 50x30 it was taller than the name
    beside it and hung down into the line of description underneath, near enough to touch it.
    """
    return (rect(x, y, 42, 25, 12.5, "var(--acc)" if on else "var(--soft2)")
            + circle(x + (29.5 if on else 12.5), y + 12.5, 10, "#FFFFFF"))


TOGGLE_W, TOGGLE_H = 42.0, 25.0
CHEV_R = 12.5


def chevron_button(cx, cy):
    """The disclosure the app puts beside every switch, so the row has two different jobs."""
    return (circle(cx, cy, CHEV_R, "var(--soft)")
            + icon('<path d="M4 8l6 6 6-6"/>', cx - 6, cy - 6.2, 0.6, "var(--ink2)", sw=2.4))


# ── screen 1: the agents on your computer ────────────────────────────────────────────────
AGENTS = [
    dict(name="Email Manager", kind="ember", running=True,
         said="\U0001F4E7 Twelve came in overnight. Two need you,",
         said2="and the other ten are filed.",
         meta="40m ago · 4 skills, 2 routines"),
    dict(name="Bookkeeper", kind="teal", running=False,
         said="Four receipts filed. One from the hardware shop",
         said2="has no total on it, so I left it alone.",
         meta="Yesterday · 2 skills, 1 routine"),
    dict(name="Around the House", kind="gold", running=False,
         said="The car insurance expires in three weeks. Worth",
         said2="looking at now rather than later.",
         meta="9h ago · 1 skill, 2 routines"),
]


def screen_agents():
    o = [status_bar(), header_list("Agents", "Your Mac")]
    y = HEAD_RULE + 16
    for a in AGENTS:
        ch = 146.0
        o.append(rect(16, y, 358, ch, 16, "var(--card)", "var(--bd)", 1))
        o.append(avatar(54, y + 38, 22, a["kind"]))
        o.append(text(88, y + 45, a["name"], 19, "var(--ink)", "400", serif=True))
        # Start or Stop, the one control the app puts on a card at rest
        lbl = "Stop" if a["running"] else "Start"
        bw = 84.0
        bx = 358 + 16 - 16 - bw
        o.append(rect(bx, y + 22, bw, 34, 11, "var(--redF)" if a["running"] else "var(--grnF)"))
        if a["running"]:
            glyph = '<rect x="6.6" y="6.6" width="10.8" height="10.8" rx="2.4"/>'
        else:
            glyph = '<path d="M 8.6 5.6 L 18.4 12 L 8.6 18.4 Z"/>'
        lw = tw(lbl, 13.5, weight="600")
        gx = bx + (bw - (15 + 6 + lw)) / 2
        o.append(icon(glyph, gx, y + 31, 0.625, "#FFFFFF", "#FFFFFF", 1.8))
        o.append(text(gx + 21, y + 43.5, lbl, 13.5, "#FFFFFF", "600"))
        o.append(text(32, y + 82, a["said"], 13.5, "var(--ink2)"))
        o.append(text(32, y + 99, a["said2"], 13.5, "var(--ink2)"))
        p, pw = pill(32, y + 112, "Running" if a["running"] else "Stopped",
                     "var(--grn)" if a["running"] else "var(--ink3)",
                     "var(--grnS)" if a["running"] else "var(--soft)")
        o.append(p)
        o.append(text(32 + pw + 10, y + 127.5, a["meta"], 13, "var(--ink3)"))
        y += ch + 14
    o.append(tab_bar(["Agents", "Tasks", "Marketplace", "Settings"], "Agents"))
    return "".join(o)


# ── screen 2: the conversation, and what a draft offers ──────────────────────────────────
# The three screens are one person's phone, so the agent you are talking to here and the
# agent whose skills the third screen lists is the one at the top of the first screen's list.
AGENT_NAME = AGENTS[0]["name"]

# The card's rows are the app's own button labels, emoji and all, from the Archie repo's
# texts/replies/card.rs. They were line icons until 2026-09-18, which is not how the app draws
# them (Jett: the mockup should have emojis like it usually would).
ACTIONS = [
    ("\u2705 Send", "var(--acc)"),
    ("\u270f\ufe0f Edit it", "var(--acc)"),
    ("\u23f0 Send later", "var(--acc)"),
    ("\u2715 Dismiss", "var(--ink3)"),
]


# The thread. Each entry is who said it and the lines it wraps to; the bubble is drawn
# around the words rather than the words being fitted into a bubble of a guessed size.
CHAT = [
    (True,  ["Anything from the accountant?"]),
    (False, ["Nothing since Friday. I will wake you", "for one, as you asked."]),
    (False, ["\U0001F4E7 Twelve came in overnight. Two need you,", "and the other ten are filed."]),
    (True,  ["Tell the landlord Tuesday morning works."]),
]
DRAFT_LEAD = "\u270d\ufe0f Here is what I would send:"
DRAFT_QUOTE = ["Tuesday morning works for us.",
               "Any time before noon is fine, and",
               "somebody will be in."]

BUB_FS = 13.5     # the words
BUB_PADX = 14.0   # side padding inside a bubble, which is what sizes it
BUB_INK = 12.0    # where the words start, two in from that: at 14 they read as sitting too far
                  # right in the drawn bubble (Jett, 2026-09-18), and the width keeps its 14
BUB_PADY = 10.0   # top and bottom padding inside a bubble
BUB_LH = 17.0     # one line of a bubble
BUB_BASE = 12.6   # first baseline down from the padding, to sit the block on the middle
BUB_GAP = 10.0    # between one message and the next
AGENT_X = 16.0    # where a bubble of theirs starts: the same 16 in from the edge as yours end,
                  # since the face beside it went (the app's 510b626, 2026-09-18: one agent in the
                  # thread, its face in the bar, and the tail says who is speaking)


def screen_chat():
    o = [status_bar(), header_agent(AGENT_NAME, "ember")]
    y = HEAD_RULE + 14

    # The first message is the resting state; each one after it is a beat on the stage, and so
    # are the draft and its actions below, so the thread arrives the way a thread does.
    CHAT_AT = [None, 0.06, 0.2, 0.36]
    for n, (mine, lines) in enumerate(CHAT):
        m = []
        w = max(tw(l, BUB_FS) for l in lines) + BUB_PADX * 2
        h = BUB_PADY * 2 + BUB_LH * len(lines)
        x = (W - 16 - w) if mine else AGENT_X
        m.append(rect(x, y, w, h, 15, "var(--accS)" if mine else "var(--card)",
                      None if mine else "var(--bd)", 1))
        for i, ln in enumerate(lines):
            m.append(text(x + BUB_INK, y + BUB_PADY + BUB_LH * i + BUB_BASE, ln,
                          BUB_FS, "var(--ink)"))
        assert x + w <= W - 16, "a bubble runs past the screen's edge: %r" % lines[0]
        o.append("".join(m) if CHAT_AT[n] is None else beat("".join(m), CHAT_AT[n]))
        y += h + BUB_GAP

    # The draft, quoted inside its own container, and then its actions in a card of their
    # own: the shape the app uses to make "nothing was sent" obvious, because the verb is a
    # row you have not pressed yet. The container is as wide as the longest line in it plus
    # its padding, which is the whole trick. Drawn at a fixed 272 it was narrower than the
    # sentences and they ran out the right hand side of it and out of the bubble too.
    qfs, qlh, qpad = 13.0, 16.0, 9.0
    bar_w, quote_x = 3.0, 14.0
    card_w = quote_x + max(tw(l, qfs) for l in DRAFT_QUOTE) + 12
    card_h = qpad * 2 + qlh * len(DRAFT_QUOTE)
    bw = max(tw(DRAFT_LEAD, BUB_FS), card_w) + BUB_PADX * 2
    h = BUB_PADY * 2 + BUB_LH + 8 + card_h
    d = [rect(AGENT_X, y, bw, h, 15, "var(--card)", "var(--bd)", 1),
         text(AGENT_X + BUB_INK, y + BUB_PADY + BUB_BASE, DRAFT_LEAD, BUB_FS, "var(--ink)")]
    cx0, cy0 = AGENT_X + BUB_INK, y + BUB_PADY + BUB_LH + 8
    d.append(rect(cx0, cy0, card_w, card_h, 7, "var(--soft)"))
    d.append(rect(cx0, cy0, bar_w, card_h, 1.5, "var(--acc)"))
    for i, ln in enumerate(DRAFT_QUOTE):
        d.append(text(cx0 + quote_x, cy0 + qpad + qlh * i + 11.8, ln, qfs, "var(--ink2)"))
    o.append(beat("".join(d), 0.52))
    y += h + BUB_GAP

    rowh, cardw = 40.0, 300.0
    a = [rect(AGENT_X, y, cardw, rowh * len(ACTIONS), 15, "var(--card)", "var(--bd)", 1)]
    for i, (label, tcol) in enumerate(ACTIONS):
        ry = y + rowh * i
        if i:
            a.append(line(AGENT_X, ry, AGENT_X + cardw, ry, "var(--bd)", 1))
        a.append(text(AGENT_X + cardw / 2, ry + rowh / 2 + 5.2, label, 14.5, tcol, "600", "middle"))
    y += rowh * len(ACTIONS)
    a.append(text(AGENT_X, y + 19, "8 minutes ago", 12.5, "var(--ink3)"))
    o.append(beat("".join(a), 0.66))

    # The thread is laid out by accumulation, so adding a bubble pushes everything below it
    # into the composer, which is drawn at a fixed y and would happily print over the top.
    # That happened once: the timestamp landed at 662 against a composer at 660 and the two
    # were each inside the screen, so a bounds check saw nothing wrong. Assert the gap.
    assert y + 23 <= COMPOSER_Y, (
        "chat thread runs to %.0f and the composer starts at %.0f: tighten the bubble gaps "
        "or drop a message" % (y + 23, COMPOSER_Y))

    # the composer
    o.append(circle(38, COMPOSER_Y + 22, 22, "var(--soft)"))
    o.append(icon('<path d="M12 5v14M5 12h14"/>', 27, COMPOSER_Y + 11, 0.9167, "var(--ink2)", sw=2))
    o.append(rect(68, COMPOSER_Y, 254, 44, 22, "var(--card)", "var(--bd)", 1))
    o.append(text(84, COMPOSER_Y + 27, "Message " + AGENT_NAME, 14, "var(--ink3)"))
    o.append(circle(352, COMPOSER_Y + 22, 22, "var(--acc)"))
    o.append('<path d="M352 %s v-18 m-7 7 l7 -7 l7 7" stroke="#FFF" stroke-width="2.4"'
             ' fill="none" stroke-linecap="round" stroke-linejoin="round"/>' % f(COMPOSER_Y + 32))
    o.append(tab_bar(["Dashboard", "Chat", "Skills", "Routines", "More"], "Chat"))
    return "".join(o)


# ── screen 3: what an agent is made of ───────────────────────────────────────────────────
SKILLS = [
    dict(name="Inbox triage", on=True, note=None,
         lines=["Sorts the morning's mail into what needs", "you and what does not."]),
    dict(name="Reply drafts", on=True, note=None,
         lines=["Writes the reply and holds it until you", "press Send."]),
    dict(name="Proofreader", on=True, note=None,
         lines=["A specialist. Reads anything before it goes."]),
    dict(name="Calendar", on=False, note="Needs a connection",
         lines=["Reads and writes the calendar. Off until", "you connect an account."]),
    dict(name="Receipts", on=True, note=None,
         lines=["Files what arrives and totals the month."]),
]


def screen_skills():
    o = [status_bar(), header_agent(AGENT_NAME, "ember")]
    y = HEAD_RULE + 16
    # the way into the marketplace sits above the list, outlined rather than filled: it is
    # the only thing on this screen that leaves it
    # The glyph and the words are one block, measured and centred in the button: placed by hand
    # they sat 20px right of its middle (Jett, 2026-09-18).
    label = "Browse the marketplace"
    block = 22 + 10 + tw(label, 15, weight="600")
    bx0 = 16 + (358 - block) / 2
    o.append(rect(16, y, 358, 48, 12, "none", "var(--acc)", 1.5))
    o.append(icon('<path d="M4 8h16l-1.2 12.5H5.2z"/><path d="M8.6 8V6.2a3.4 3.4 0 0 1 6.8 0V8"/>',
                  bx0, y + 13, 0.9167, "var(--acc)", sw=1.8))
    o.append(text(bx0 + 32, y + 30, label, 15, "var(--acc)", "600"))
    y += 62

    # Both controls are centred on the name's line rather than hung from the top of the card,
    # which is what left a 50x30 switch and a 30px chevron reaching down to within a pixel of
    # the description underneath and reading as though they belonged to it.
    for n, s in enumerate(SKILLS):
        ch = 58.0 + 17.0 * len(s["lines"])
        row = y + 28            # the middle of the name's line
        c = [rect(16, y, 358, ch, 16, "var(--card)", "var(--bd)", 1),
             text(32, y + 33.5, s["name"], 16, "var(--ink)", "400", serif=True)]
        if s["note"]:
            nx = 32 + tw(s["name"], 16, serif=True) + 10
            p, _ = pill(nx, row - 10, s["note"], "var(--gld)", "var(--gldS)", 11.5, 9, 20)
            c.append(p)
        chev_cx = 374 - 16 - CHEV_R
        c.append(toggle(chev_cx - CHEV_R - 12 - TOGGLE_W, row - TOGGLE_H / 2, s["on"]))
        c.append(chevron_button(chev_cx, row))
        for i, ln in enumerate(s["lines"]):
            c.append(text(32, y + 60 + i * 17, ln, 13.5, "var(--ink3)"))
        # the cards land one after another on the stage, a beat apart
        o.append(beat("".join(c), 0.08 + 0.13 * n))
        y += ch + 12
    o.append(tab_bar(["Dashboard", "Chat", "Skills", "Routines", "More"], "Skills"))
    return "".join(o)


SCREENS = [
    (screen_agents, "Your agents, awake or asleep",
     "The agents on your computer, each with the last thing it said and a Start or Stop button."),
    (screen_chat, "The conversation, and its buttons",
     "A conversation with an agent, where a drafted reply offers Send, Edit it, Send later and Dismiss."),
    (screen_skills, "What an agent is made of",
     "The skills an agent is made of, each with a switch to turn it on or off."),
]


# ── assembly ─────────────────────────────────────────────────────────────────────────────
# Two theme blocks, because these are drawings of an app that has both and the page is read
# in both. Same token names the rest of the site uses, so a mock never invents a colour.
THEME = (
    '<style>.mk{--bg:#FCFAF8;--card:#FFFFFF;--ink:#44403B;--ink2:#69645D;--ink3:#6D6861;'
    '--bd:#EAE6E1;--acc:#E08A5B;--accS:#FBE4D3;--grn:#679B55;--grnS:rgba(103,155,85,.14);'
    '--grnF:#4E7D3F;--redF:#BC5145;--gld:#8C6820;--gldS:rgba(187,140,51,.14);'
    '--soft:rgba(68,64,59,.04);--soft2:rgba(68,64,59,.12);--ls:rgba(68,64,59,.16);'
    '--shell:#2E2C29;--shell-hi:#5A5753;--shell-lo:#171614;--edge:rgba(255,255,255,.18)}'
    ':root[data-theme="dark"] .mk{--bg:#1A1A19;--card:#2B2B29;--ink:#F3F0ED;--ink2:#AEACA6;'
    '--ink3:#ACA8A3;--bd:#3F3E3A;--acc:#EDA277;--accS:#453629;--grn:#8FC47B;'
    '--grnS:rgba(143,196,123,.16);--grnF:#4E7440;--redF:#B0503F;--gld:#DCAF57;--gldS:rgba(220,175,87,.16);'
    '--soft:rgba(243,240,237,.05);--soft2:rgba(243,240,237,.14);--ls:rgba(243,240,237,.16);'
    '--shell:#3A3936;--shell-hi:#6E6B66;--shell-lo:#1A1918;--edge:rgba(255,255,255,.22)}</style>'
)


def device(inner, ox, oy):
    """The phone around a screen. Until 2026-09-18 this was one dark rounded rectangle, which
    read as a card with a screen on it (Jett: "too bland"). What a phone has that a card does
    not: a body that is lit from one corner and darker toward the other, a bright line where
    the glass meets the metal, a black bezel between the two, the buttons on its sides, and the
    island at the top of the screen with the lens in it. None of it is Archie; it is what makes
    the rest read as a phone. Drawn once for the stage and the stills, so the two cannot drift."""
    cid, gid = uid("sc"), uid("gs")
    P = SHELL_PAD
    return ('<g transform="translate(%s,%s)">' % (f(ox), f(oy))
            + '<defs><clipPath id="%s">%s</clipPath>' % (cid, rect(0, 0, W, H, 42, "#000"))
            + '<linearGradient id="%s" x1="0" y1="0" x2="0.4" y2="1">' % gid
            + '<stop offset="0" style="stop-color:var(--shell-hi)"/>'
            + '<stop offset="0.45" style="stop-color:var(--shell)"/>'
            + '<stop offset="1" style="stop-color:var(--shell-lo)"/></linearGradient></defs>'
            # the buttons, on the metal behind the body: volume on the left, power on the right
            + rect(-P - 3, 118, 3.5, 34, 1.5, "var(--shell-lo)")
            + rect(-P - 3, 166, 3.5, 54, 1.5, "var(--shell-lo)")
            + rect(-P - 3, 232, 3.5, 54, 1.5, "var(--shell-lo)")
            + rect(W + P - 0.5, 186, 3.5, 84, 1.5, "var(--shell-lo)")
            # the body, its lit edge, and the bezel
            + rect(-P, -P, W + P * 2, H + P * 2, 52, "url(#%s)" % gid)
            + rect(-P + 0.75, -P + 0.75, W + P * 2 - 1.5, H + P * 2 - 1.5, 51.5, "none", "var(--edge)", 1)
            + rect(-4, -4, W + 8, H + 8, 46, "#0B0B0A")
            # the screen
            + '<g clip-path="url(#%s)">' % cid
            + rect(0, 0, W, H, 42, "var(--bg)") + inner + "</g>"
            # the island and the lens, inside the status bar's clear middle
            + rect(W / 2 - 46, 11, 92, 28, 14, "#000")
            + circle(W / 2 + 19, 25, 5.6, "#121820")
            + circle(W / 2 + 17.4, 23.4, 1.7, "rgba(255,255,255,.32)")
            + "</g>")


def phone(body, ox, oy):
    return device(body, ox, oy)


def build():
    """The two renderings: the stage phone, then the stills."""
    _n[0] = 0
    caption_y = 856.0

    # The stage: the shell once, the three screens inside it, screen i on act i. aria-hidden,
    # because the scene it stands in carries the accessible name for the whole drawing, the
    # way the homepage's does; the stills below are what a machine reads.
    bodies = []
    for i, (fn, cap, desc) in enumerate(SCREENS):
        _beat["act"] = i
        bodies.append(fn())
    _beat["act"] = None
    # The screen alone, at the screen's own size: the device around it on the stage is the
    # homepage phone's, in HTML (styles.css section 49, the .dp-* classes), which is what gives
    # it a rim, a chamfer and light that moves with its angle. The stylesheet lights one
    # .mk-scr at a time and the rest are not painted.
    stage = ('<svg class="mk mk-stage" viewBox="0 0 %s %s" aria-hidden="true" focusable="false"'
             ' xmlns="http://www.w3.org/2000/svg" style="font-family:inherit">' % (f(W), f(H)) + THEME
             + rect(0, 0, W, H, 0, "var(--bg)")
             + "".join('<g class="mk-scr%s" data-scr="%d">%s</g>'
                       % (" is-on" if i == 0 else "", i, body) for i, body in enumerate(bodies))
             + "</svg>")

    # The stills: one drawing per screen, each named, in a row the stylesheet stacks narrow.
    items = []
    for i, (fn, cap, desc) in enumerate(SCREENS):
        tid = "mks%d" % (i + 1)
        svg = ('<svg class="mk" viewBox="0 0 412 874" role="img" aria-labelledby="%s"'
               ' xmlns="http://www.w3.org/2000/svg" style="font-family:inherit;overflow:visible">' % tid
               + THEME + '<title id="%s">%s</title>' % (tid, esc(desc))
               + phone(fn(), 11.0, 11.0)
               + text(206, caption_y, cap, 21, "currentColor", "500", "middle") + "</svg>")
        items.append('<div class="mb-still-item">%s</div>' % svg)
    stills = ('<div class="mb-still" aria-label="Three screens from Archie Mobile">'
              + "".join(items) + "</div>")

    return stage, stills


def main():
    check = "--check" in sys.argv
    html = open(PAGE, encoding="utf-8").read()
    stage, stills = build()
    new = html
    for begin, end, body in ((STAGE_BEGIN, STAGE_END, stage), (BEGIN, END, stills)):
        pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
        if not pat.search(new):
            print("gen-phone-mocks: cannot find %r in the page" % begin)
            return 1
        block = begin + "\n              " + body + "\n              " + end
        new = pat.sub(lambda _: block, new, count=1)

    if new == html:
        print("gen-phone-mocks: clean. 3 screens, 2 renderings.")
        return 0
    if check:
        print("gen-phone-mocks: archie/mobile/ is out of date. Run scripts/gen-phone-mocks.py")
        return 1
    open(PAGE, "w", encoding="utf-8").write(new)
    print("gen-phone-mocks: wrote 3 screens as the stage phone and the three stills.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
