/* Write the Archie Learning Library into learn/<slug>/, one page per section, from assets/library.json.
 *
 * WHAT A PAGE IS (Jett, 2026-09-30). Each section of a level is its own video and its own page:
 * the video from YouTube behind a press, the section's notes directly under it, previous and next,
 * the words Jack reads, and the whole library down the side so any section is one press away.
 * TRUST.md's library entry governs all of it; the parts that bind this file:
 *
 *   - Nothing reaches YouTube until the reader presses play. The page shows our own poster
 *     (assets/learn/<slug>.jpg) inside a plain link to the video on youtube.com, and js/library.js
 *     swaps that link for the youtube-nocookie player on the press. Without scripts the link
 *     simply goes to YouTube, which is also the reader's choice. The CSP opens frame-src to
 *     youtube-nocookie on these pages only (scripts/gen-csp.py, LIBRARY_SOURCES).
 *   - The notes box sits directly under the player, because TRUST.md lets the narration point
 *     "below this video" at a figure only while the box is on the same page, right there, and says
 *     it. Notes carry FACTS.md figures and TRUST.md wording and nothing else.
 *   - "Read by Jack." is the line under every player, true only while he read it.
 *
 * WHEN A SECTION IS PUBLISHED. When it has a YouTube id and no hold. Every other section is left
 * out everywhere, including the side list and previous and next, so no page links to one that is
 * not there. A hold says why in words, and only Jett clears it.
 *
 * THE CHROME. The head, the three copies of the menu, and the footer are copied from a live page
 * at generation time (CHROME below), never kept in a template here, so a menu sweep across the
 * site can never leave these pages behind: a sweep edits these pages too, and --check says so if
 * the two ever disagree. The CSP tag is the one thing gen-csp.py writes afterwards, so --check
 * ignores it.
 *
 * Usage:
 *   node scripts/gen-library.mjs             write the published pages, remove unpublished ones
 *   node scripts/gen-library.mjs --check     exit 1 if any page is out of date
 *   node scripts/gen-library.mjs --preview   write every section, held or not, with a stand-in
 *                                            video id, for looking at locally. Never commit it.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DATA = path.join(ROOT, "assets", "library.json");
const OUT = path.join(ROOT, "learn");
const CHROME = path.join(ROOT, "compare", "questions-to-ask", "index.html");
const BANNER = "<!-- GENERATED by scripts/gen-library.mjs from assets/library.json. Do not hand-edit. -->";
const CSP_RE = /[ \t]*<!-- CSP: generated by scripts\/gen-csp\.py[^\n]*\n[ \t]*<meta http-equiv="Content-Security-Policy"[^>]*>\n/;

const esc = (t) => String(t).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
/* The data's strings are already HTML (entities and a few links), so attributes get them with the
   tags taken off and nothing escaped twice. */
const plain = (html) => html.replace(/<[^>]+>/g, "");
const attr = (html) => plain(html).replace(/"/g, "&quot;");

function chrome() {
  const src = fs.readFileSync(CHROME, "utf8");
  const cssLine = src.match(/[ \t]*<link rel="stylesheet" href="\.\.\/\.\.\/css\/styles\.css\?v=([^"]+)" \/>\n/);
  if (!cssLine) throw new Error("no stylesheet link in " + CHROME);
  const stamp = cssLine[1];
  const head = src.slice(0, cssLine.index + cssLine[0].length);
  const bodyStart = src.indexOf("<body>");
  const mainStart = src.indexOf('  <main id="main">');
  const mainEnd = src.indexOf("  </main>\n");
  if (bodyStart < 0 || mainStart < 0 || mainEnd < 0) throw new Error("landmarks missing in " + CHROME);
  const top = src.slice(bodyStart, mainStart);
  let tail = src.slice(mainEnd + "  </main>\n".length);
  // The chrome page's own player script is not ours; the library's is.
  tail = tail.replace(/[ \t]*<script src="\.\.\/\.\.\/js\/demo-player\.js\?v=[^"]+"><\/script>\n/, "");
  tail = tail.replace("</body>", `  <script src="../../js/library.js?v=${stamp}"></script>\n</body>`);
  return { head, top, tail, stamp };
}

/* The length as a person says it: an intro is "under a minute", the rest "about 1 minute" and up.
   Rounded, so a trim in the edit does not make it wrong. */
function length(s) {
  const sec = s.seconds || 60;
  if (sec < 45) return "under a minute";
  const m = Math.round(sec / 60);
  return m === 1 ? "about 1 minute" : `about ${m} minutes`;
}

/* How a section is named: "0.1" in the list's number column and before its title elsewhere; a
   level's intro is "Intro" in the column and "Level 0:" before its title, since its title is the
   level's own name. */
const intro = (s) => s.n.endsWith(".0");
const num = (s) => (intro(s) ? "Intro" : s.n);
const named = (s) => (intro(s) ? `Level ${s.level}: ${s.title}` : `${s.n} ${s.title}`);

/* The pictures in the page's own UI (Jett, 2026-09-30: "more visuals and iconography"): line icons
   from assets/learn/icons/, drawn as masks in the text color like the menu's, one per level. A mask
   rather than inline SVG, so a label's text is still the first thing in it for check-pronouns. */
const LEVEL_ICON = { 0: "laptop", 1: "spark", 2: "steps", 3: "shield", 4: "chat" };
const ICONS = ["laptop", "spark", "steps", "shield", "chat", "clock", "play", "played", "arrow-left", "arrow-right", "notes", "quote", "book"];
const ico = (name, cls = "") => `<span class="lib-i lib-i-${name}${cls ? " " + cls : ""}" aria-hidden="true"></span>`;
/* A row's length, rounded like length() so a trim in the edit does not make it wrong. */
const short = (s) => { const sec = s.seconds || 60; return sec < 45 ? "Under 1 min" : `${Math.round(sec / 60)} min`; };

function page(s, all, levels, C, preview) {
  const lv = levels.find((l) => l.n === s.level);
  const i = all.indexOf(s);
  const prev = all[i - 1], next = all[i + 1];
  const id = preview ? "PREVIEW" : s.youtube;
  const title = `${plain(s.title)} | Learning Library | Otian AI`;
  const desc = `${plain(s.lede)} A short video, read by Jack.`;
  let head = C.head
    .replace(/<title>[^<]*<\/title>/, `<title>${esc(title)}</title>`)
    .replace(/<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${attr(desc)}" />`)
    .replace(/<meta property="og:image" content="[^"]*" \/>/, `<meta property="og:image" content="https://otianai.com/assets/learn/${s.slug}.jpg" />`)
    .replace(/<meta name="twitter:card" content="[^"]*" \/>/, `<meta name="twitter:card" content="summary_large_image" />`);
  if (preview) head = head.replace("<head>", '<head>\n  <meta name="robots" content="noindex" />');

  const index = levels
    .filter((l) => all.some((x) => x.level === l.n))
    .map((l) => {
      const mine = all.filter((x) => x.level === l.n);
      const items = mine.map((x) =>
        `<li><a href="../${x.slug}/" data-slug="${x.slug}"${x === s ? ' aria-current="page"' : ""}>${ico("play", "lib-row-i")}<span class="lib-n">${esc(num(x))}</span><span class="lib-row-t">${x.title}</span><span class="lib-row-len">${short(x)}</span></a></li>`).join("\n              ");
      return `<details class="lib-level"${l.n === s.level ? " open" : ""}>
            <summary>${ico(LEVEL_ICON[l.n], "lib-lv-i")}<span class="lib-lv-t">Level ${l.n}: ${esc(l.title)}<span class="lib-lv-count">${mine.length} ${mine.length === 1 ? "video" : "videos"}</span></span></summary>
            <ol>
              ${items}
            </ol>
          </details>`;
    }).join("\n          ");

  const step = (x, rel, word) => x
    ? `<a class="lib-step-${rel}" rel="${rel}" href="../${x.slug}/" data-slug="${x.slug}"><img class="lib-step-img" src="../../assets/learn/${x.slug}.jpg" width="1280" height="720" alt="" loading="lazy" /><span class="lib-step-txt"><span class="lib-step-w">${rel === "prev" ? ico("arrow-left") : ""}${word}${rel === "next" ? ico("arrow-right") : ""}</span><span class="lib-step-t">${named(x)}</span></span></a>`
    : "";
  /* This level's videos as a row of numbered stops: where you are, and every other one a press away. */
  const mates = all.filter((x) => x.level === s.level);
  const dots = mates.map((x, k) =>
    `<li><a href="../${x.slug}/" data-slug="${x.slug}" title="${attr(named(x))}" aria-label="${attr(named(x))}"${x === s ? ' aria-current="page"' : ""}>${k + 1}</a></li>`).join("\n            ");

  const notes = s.notes && s.notes.length
    ? `
        <section class="lib-notes" aria-labelledby="lib-notes-h">
          <h2 id="lib-notes-h"><span class="lib-badge">${ico("notes")}</span><span>${s.notes_heading}</span></h2>
          <ul>
            ${s.notes.map((n) => `<li>${n}</li>`).join("\n            ")}
          </ul>
        </section>`
    : "";

  const words = s.words.map((p) => `<p>${esc(p)}</p>`).join("\n            ");
  const playLabel = `Play the video: ${plain(s.title)}, ${length(s)}`;

  const main = `  <main id="main" class="lib">
    ${BANNER}
    <div class="lib-wrap">
      <article class="lib-main">
        <p class="section-label lib-kicker lib-kicker-${LEVEL_ICON[s.level]}">Learning Library &middot; Level ${s.level}: ${esc(lv.title)}</p>
        <h1 class="lib-h1"><span class="lib-h1-n">${intro(s) ? `Level ${s.level}:` : s.n}</span> ${s.title}</h1>

        <figure class="lib-player">
          <div class="lib-slot">
            <div class="lib-screen">
              <a class="lib-play" href="https://www.youtube.com/watch?v=${esc(id)}" data-yt="${esc(id)}" data-title="${attr(s.title)}" aria-label="${attr(playLabel)}">
                <img src="../../assets/learn/${s.slug}.jpg" width="1280" height="720" alt="" />
                <span class="lib-play-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M8 5.5v13l11-6.5z" fill="currentColor"/></svg></span>
                <span class="lib-play-len" aria-hidden="true">${ico("clock")}${short(s)}</span>
              </a>
            </div>
          </div>
          <figcaption class="lib-cap"><img class="lib-jack" src="../../assets/learn/jack.jpg" width="96" height="96" alt="" /><span>Read by Jack. Pressing play on a video in the library loads YouTube&rsquo;s player, and YouTube counts that play.</span></figcaption>
        </figure>
        <p class="lib-lede">${s.lede}</p>
${notes}
        <div class="lib-go">
          <nav class="lib-path" aria-label="The videos in Level ${s.level}">
            <p class="lib-path-t">${ico(LEVEL_ICON[s.level])}<span>Level ${s.level}, video ${mates.indexOf(s) + 1} of ${mates.length}</span></p>
            <ol class="lib-dots">
            ${dots}
            </ol>
          </nav>
          <nav class="lib-step" aria-label="Previous and next video">
            ${step(prev, "prev", "Previous")}
            ${step(next, "next", "Next")}
          </nav>
        </div>

        <details class="lib-words">
          <summary><span class="lib-badge">${ico("quote")}</span><span>Read what Jack says in ${intro(s) ? `the Level ${s.level} intro` : s.n}</span></summary>
          <blockquote class="lib-words-body">
            ${words}
          </blockquote>
        </details>
      </article>

      <nav class="lib-index" aria-label="Learning Library">
        <p class="lib-index-t">${ico("book")}Learning Library</p>
          ${index}
      </nav>
    </div>
  </main>
`;
  return head + STYLE + "</head>\n" + C.top + main + C.tail;
}

/* The library's own rules, in the page like compare/questions-to-ask/'s, so a change here never
   needs the whole site's asset stamp moved. Colors are the site's tokens only. */
const STYLE = `  <style>
    /* ── The Learning Library (learn/<slug>/, 2026-09-30), written by scripts/gen-library.mjs ── */
    .lib { padding-block: calc(var(--nav-height) + 28px) 72px; }
    .lib-wrap { width: min(1180px, 100% - 32px); margin-inline: auto; display: grid; gap: 40px; grid-template-columns: minmax(0, 1fr) 320px; align-items: start; }
    .lib-main { min-width: 0; display: grid; gap: 18px; }
    /* Icons: masks over the text color, the way the menu draws its own (.nav-row-ico). */
    .lib-i { display: inline-block; flex: none; width: 1.15em; height: 1.15em; background-color: currentColor; -webkit-mask: var(--ico) center / contain no-repeat; mask: var(--ico) center / contain no-repeat; }
${ICONS.map((n) => `    .lib-i-${n}, .lib-kicker-${n}::before { --ico: url("../../assets/learn/icons/${n}.svg"); }`).join("\n")}
    .lib-kicker { display: flex; align-items: center; gap: 10px; margin: 0; }
    .lib-kicker::before { content: ""; flex: none; width: 1.6em; height: 1.6em; background-color: currentColor; -webkit-mask: var(--ico) center / contain no-repeat; mask: var(--ico) center / contain no-repeat; }
    .lib-h1 { margin: 0; font-size: clamp(1.9rem, 1.2rem + 2.2vw, 2.75rem); line-height: 1.15; text-wrap: balance; }
    .lib-h1-n { color: var(--accent); font-variant-numeric: tabular-nums; }
    .lib-lede { margin: 0; max-width: 62ch; color: var(--text-secondary); font-size: var(--fs-xl); }
    .lib-player { margin: 0; display: grid; gap: 10px; }
    /* The player comes straight after the title and is never taller than the window has room for,
       so a reader arriving from the side list or Next sees the whole video without scrolling (Jett,
       2026-09-30). The slot keeps the player's place when it docks, so the page never jumps. */
    .lib-slot { width: min(100%, max(60%, calc((100svh - var(--nav-height) - 240px) * 16 / 9))); aspect-ratio: 16 / 9; }
    .lib-screen { position: relative; width: 100%; height: 100%; }
    .lib-play, .lib-frame { position: relative; display: block; width: 100%; height: 100%; border: 0; border-radius: 16px; overflow: hidden; background: #1c1916; box-shadow: var(--shadow-md); }
    /* Playing and scrolled past, the player docks in the corner above the theme button, and across
       the bottom on a phone. Only after the press (js/library.js), so it is YouTube's player or nothing. */
    .lib-screen.is-docked { position: fixed; z-index: 70; right: max(16px, env(safe-area-inset-right)); bottom: calc(max(20px, env(safe-area-inset-bottom)) + 52px); width: clamp(320px, 34vw, 480px); height: auto; aspect-ratio: 16 / 9; }
    .lib-screen.is-docked .lib-frame { border-radius: var(--radius); box-shadow: var(--shadow-lg); }
    .lib-dock-bar { position: absolute; right: 0; bottom: 100%; display: flex; gap: 6px; padding-bottom: 8px; }
    .lib-dock-bar button { padding: 6px 12px; border-radius: 999px; border: 1px solid var(--border, rgba(68, 64, 59, 0.16)); background: var(--bg-card, #fff); color: var(--text-primary); box-shadow: var(--shadow-sm); font: inherit; font-size: var(--fs-sm); font-weight: 600; cursor: pointer; }
    .lib-dock-bar button:hover { border-color: var(--accent); }
    .lib-dock-bar button:focus-visible { outline: 3px solid var(--accent); outline-offset: 2px; }
    .lib-play img { display: block; width: 100%; height: 100%; object-fit: cover; }
    .lib-play-mark { position: absolute; left: 50%; top: 80%; width: 84px; height: 84px; margin: -42px 0 0 -42px; border-radius: 50%; display: grid; place-items: center; background: var(--accent); color: #fff; box-shadow: var(--shadow-sm); transition: transform 0.2s ease; }
    .lib-play-mark svg { width: 38px; height: 38px; margin-left: 4px; }
    .lib-play:hover .lib-play-mark, .lib-play:focus-visible .lib-play-mark { transform: scale(1.08); }
    .lib-play:focus-visible { outline: 3px solid var(--accent); outline-offset: 3px; }
    .lib-play-len { position: absolute; right: 14px; bottom: 14px; display: inline-flex; align-items: center; gap: 6px; padding: 5px 11px; border-radius: 999px; background: rgba(20, 18, 16, 0.74); color: #fff; font-size: var(--fs-sm); font-weight: 600; font-variant-numeric: tabular-nums; }
    .lib-cap { display: flex; align-items: center; gap: 12px; font-size: var(--fs-base); color: var(--text-secondary); }
    .lib-jack { flex: none; width: 40px; height: 40px; border-radius: 50%; object-fit: cover; border: 2px solid var(--accent-subtle); }
    .lib-notes { padding: 22px 24px; border-radius: 14px; background: var(--bg-card, #fff); border: 1px solid var(--border, rgba(68, 64, 59, 0.12)); }
    .lib-notes h2 { display: flex; align-items: center; gap: 14px; margin: 0 0 14px; font-size: var(--fs-2xl); line-height: 1.3; }
    .lib-badge { flex: none; display: grid; place-items: center; width: 44px; height: 44px; border-radius: var(--radius); background: var(--accent-subtle); color: var(--accent); }
    .lib-badge .lib-i { width: 24px; height: 24px; }
    .lib-notes ul { margin: 0; padding: 0; display: grid; gap: 10px; list-style: none; }
    .lib-notes li { position: relative; padding-left: 24px; line-height: 1.5; }
    .lib-notes li::before { content: ""; position: absolute; left: 4px; top: 0.62em; width: 8px; height: 8px; border-radius: 50%; background: var(--accent); }
    /* Where this video sits in its level, and the way to the ones either side of it. */
    .lib-go { display: grid; gap: 18px; padding: 20px; border-radius: 14px; border: 1px solid var(--border, rgba(68, 64, 59, 0.12)); }
    .lib-path { display: grid; gap: 12px; }
    .lib-path-t { display: flex; align-items: center; gap: 8px; margin: 0; font-size: var(--fs-sm); font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase; color: var(--text-secondary); }
    .lib-path-t .lib-i { color: var(--accent); width: 1.4em; height: 1.4em; }
    .lib-dots { list-style: none; margin: 0; padding: 0; display: flex; gap: 8px; }
    .lib-dots li { position: relative; flex: 1 1 0; display: flex; justify-content: center; }
    .lib-dots li + li::before { content: ""; position: absolute; top: 50%; right: 50%; width: calc(100% + 8px); height: 2px; margin-top: -1px; background: var(--border, rgba(68, 64, 59, 0.16)); }
    .lib-dots a { position: relative; z-index: 1; display: grid; place-items: center; width: min(38px, 100%); aspect-ratio: 1; border-radius: 50%; border: 2px solid var(--border, rgba(68, 64, 59, 0.16)); background: var(--bg-primary); color: var(--text-secondary); font-size: var(--fs-sm); font-weight: 600; font-variant-numeric: tabular-nums; text-decoration: none; }
    .lib-dots a:hover { border-color: var(--accent); color: var(--accent); }
    .lib-dots a.is-played { border-color: var(--accent); color: var(--accent); }
    .lib-dots a[aria-current="page"] { border-color: var(--accent); background: var(--accent); color: #fff; box-shadow: var(--shadow-sm); }
    .lib-step { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .lib-step a { display: grid; grid-template-columns: 112px minmax(0, 1fr); align-items: center; gap: 14px; padding: 10px; border-radius: var(--radius); border: 1px solid var(--border, rgba(68, 64, 59, 0.16)); text-decoration: none; color: inherit; }
    .lib-step a:hover { border-color: var(--accent); }
    .lib-step-img { display: block; width: 100%; height: auto; aspect-ratio: 16 / 9; object-fit: cover; border-radius: var(--radius-sm); }
    .lib-step-txt { display: grid; gap: 2px; min-width: 0; }
    .lib-step a.lib-step-next { grid-column: 2; grid-template-columns: minmax(0, 1fr) 112px; text-align: right; }
    .lib-step-next .lib-step-img { order: 2; }
    .lib-step-w .lib-i { vertical-align: -0.2em; margin: 0 6px; }
    .lib-step-w { font-size: var(--fs-sm); font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase; color: var(--accent); }
    .lib-step-t { font-weight: 600; line-height: 1.3; }
    .lib-words { border-radius: 14px; border: 1px solid var(--border, rgba(68, 64, 59, 0.12)); padding: 14px 20px 14px 14px; }
    .lib-words summary { display: flex; align-items: center; gap: 14px; cursor: pointer; font-weight: 600; list-style: none; }
    .lib-words summary::-webkit-details-marker { display: none; }
    .lib-words summary::after, .lib-level summary::after { content: ""; flex: none; width: 7px; height: 7px; margin: 0 4px 4px auto; border-right: 2px solid currentColor; border-bottom: 2px solid currentColor; transform: rotate(45deg); opacity: 0.55; }
    .lib-words[open] summary::after, .lib-level[open] summary::after { margin-bottom: 0; transform: rotate(-135deg); }
    /* Jack's words, quoted: a quote is his voice and not the page's, which check-voice.py honors. */
    .lib-words-body { max-width: 66ch; margin: 0; padding: 16px 0 2px 4px; border: 0; color: var(--text-secondary); font-style: normal; }
    .lib-words-body p { margin: 0 0 10px; }
    .lib-index { position: sticky; top: 96px; display: grid; gap: 6px; padding: 18px; border-radius: 14px; border: 1px solid var(--border, rgba(68, 64, 59, 0.16)); max-height: calc(100vh - 120px); overflow: auto; }
    .lib-index-t .lib-i { color: var(--accent); width: 1.3em; height: 1.3em; }
    .lib-index-t { display: flex; align-items: center; gap: 8px; margin: 0 0 4px; font-size: var(--fs-sm); font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; color: var(--text-secondary); }
    .lib-level summary { display: flex; align-items: center; gap: 10px; cursor: pointer; padding: 8px 0; font-weight: 600; list-style: none; }
    .lib-level summary::-webkit-details-marker { display: none; }
    .lib-lv-i { color: var(--accent); width: 1.5em; height: 1.5em; }
    .lib-lv-t { display: grid; line-height: 1.3; }
    .lib-lv-count { font-size: var(--fs-sm); font-weight: 500; color: var(--text-secondary); }
    .lib-level ol { list-style: none; margin: 0 0 8px; padding: 0; display: grid; gap: 2px; }
    .lib-level a { display: grid; grid-template-columns: 1.15em 2.6em minmax(0, 1fr) auto; align-items: start; gap: 8px; padding: 7px 8px; border-radius: var(--radius-sm); text-decoration: none; color: inherit; font-size: var(--fs-md); line-height: 1.3; }
    .lib-level a:hover { background: var(--surface-hover, rgba(68, 64, 59, 0.06)); }
    .lib-level a[aria-current="page"] { background: var(--accent-subtle); box-shadow: inset 3px 0 0 var(--accent); font-weight: 600; }
    .lib-n { font-variant-numeric: tabular-nums; opacity: 0.8; }
    .lib-row-i { margin-top: 0.08em; color: var(--text-secondary); }
    .lib-level a[aria-current="page"] .lib-row-i, .lib-level a.is-played .lib-row-i { color: var(--accent); }
    .lib-level a.is-played .lib-i-play { --ico: url("../../assets/learn/icons/played.svg"); }
    .lib-row-len { font-size: var(--fs-sm); color: var(--text-secondary); white-space: nowrap; font-variant-numeric: tabular-nums; }
    @media (max-width: 900px) {
      .lib-wrap { grid-template-columns: minmax(0, 1fr); }
      .lib-index { position: static; max-height: none; }
    }
    @media (max-width: 700px) {
      .lib-screen.is-docked { left: max(12px, env(safe-area-inset-left)); right: max(12px, env(safe-area-inset-right)); width: auto; }
    }
    @media (max-width: 560px) {
      .lib-step { grid-template-columns: minmax(0, 1fr); }
      .lib-step a, .lib-step a.lib-step-next { grid-column: auto; grid-template-columns: 96px minmax(0, 1fr); text-align: left; }
      .lib-step-next .lib-step-img { order: 0; }
      .lib-dots { gap: 4px; }
      .lib-dots li + li::before { width: calc(100% + 4px); }
      .lib-go { padding: 16px; }
      .lib-play-mark { width: 56px; height: 56px; margin: -28px 0 0 -28px; }
      .lib-play-mark svg { width: 26px; height: 26px; }
    }
  </style>
`;

function main() {
  const check = process.argv.includes("--check");
  const preview = process.argv.includes("--preview");
  const { levels, sections } = JSON.parse(fs.readFileSync(DATA, "utf8"));
  const C = chrome();
  const all = preview ? sections : sections.filter((s) => s.youtube && !s.hold);
  const wanted = new Map(all.map((s) => [s.slug, page(s, all, levels, C, preview)]));

  /* The first player changes two things the site says about itself, on the same day (TRUST.md, the
     video library): the website entry gains the sentence about YouTube counting a play, and the
     privacy policy names YouTube among the outside resources. Publishing refuses until both do. */
  if (!preview && wanted.size) {
    const trust = fs.readFileSync(path.join(ROOT, "TRUST.md"), "utf8");
    const privacy = fs.readFileSync(path.join(ROOT, "privacy-policy", "index.html"), "utf8");
    const missing = [];
    if (!trust.includes("Pressing play on a video in the library loads YouTube")) missing.push("TRUST.md's website entry lacks the YouTube sentence");
    if (!/YouTube/.test(privacy)) missing.push("the privacy policy does not name YouTube");
    if (missing.length) {
      console.log("gen-library: not publishing, because " + missing.join(" and ") + ".");
      process.exit(1);
    }
  }

  const ours = fs.existsSync(OUT)
    ? fs.readdirSync(OUT, { withFileTypes: true })
        .filter((d) => d.isDirectory() && fs.existsSync(path.join(OUT, d.name, "index.html")) &&
          fs.readFileSync(path.join(OUT, d.name, "index.html"), "utf8").includes(BANNER))
        .map((d) => d.name)
    : [];
  const stale = ours.filter((slug) => !wanted.has(slug));
  const noCsp = (t) => t.replace(CSP_RE, "");
  let bad = 0;
  for (const [slug, html] of wanted) {
    const file = path.join(OUT, slug, "index.html");
    const have = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (have !== null && noCsp(have) === noCsp(html)) continue;
    if (check) { console.log("  out of date: learn/" + slug + "/"); bad++; continue; }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    // Keep the CSP gen-csp.py wrote, so a regeneration does not undo it.
    const csp = have && have.match(CSP_RE);
    fs.writeFileSync(file, csp ? html.replace(CSP_RE, csp[0]) : html);
    console.log("  wrote learn/" + slug + "/");
  }
  for (const slug of stale) {
    if (check) { console.log("  not published, still on disk: learn/" + slug + "/"); bad++; continue; }
    fs.rmSync(path.join(OUT, slug), { recursive: true });
    console.log("  removed learn/" + slug + "/");
  }
  const held = sections.filter((s) => s.hold).map((s) => `${s.n} (${s.hold})`);
  const waiting = sections.filter((s) => !s.youtube && !s.hold).length;
  if (check && bad) { console.log(`gen-library: ${bad} page(s) out of date. Run: node scripts/gen-library.mjs`); process.exit(1); }
  console.log(`gen-library: ${wanted.size} published, ${waiting} waiting for a YouTube id, ${held.length} held.`);
  for (const h of held) console.log("  held: " + h);
}

main();
