#!/usr/bin/env python3
"""Write a Content-Security-Policy meta tag into every page, and verify it stays correct.

WHY A META TAG AND NOT A HEADER. The site is served by GitHub Pages, which does not let you set
response headers. A meta-tag CSP is what is available, and it is most of one. Two things it
cannot do, and pretending otherwise would be worse than knowing:

  * `frame-ancestors` is ignored in a meta tag, and so is X-Frame-Options, which is a header
    only. So clickjacking protection is NOT achievable here. Closing that means moving hosting
    (Cloudflare Pages, Firebase Hosting, anything with a headers file). It is not a thing this
    script can fix, and it should not be listed as done anywhere.
  * `report-uri` / `report-to` need a collector, which we do not run. Violations show up in the
    browser console, which is what scripts/check-csp.py drives.

WHY `style-src 'unsafe-inline'`. 24 pages carry a <style> block and 30 use style= attributes.
CSP hashes do not cover style attributes at all, so removing 'unsafe-inline' would mean deleting
every inline style on a hand-written 60-page site. Inline style is a far weaker vector than
inline script, and script-src is where this policy is strict, so that is the trade taken.

WHY A GENERATOR. script-src carries a sha256 hash per distinct inline script body. There are 19
of them, one appearing in 54 pages (the theme-before-first-paint script). Hand-maintaining those
would break a page silently the first time someone edited an inline script, so the hashes are
computed from the files themselves and this script is the only thing that writes them.

Usage:
  python3 scripts/gen-csp.py            rewrite the meta tag in every page
  python3 scripts/gen-csp.py --check    exit 1 if any page's tag is missing or stale
"""

import base64
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_DIRS = {".git", ".claude", "node_modules", "firebase-hosting", "scripts"}
# _csp-selftest.html is written into the repo root by scripts/check-csp.py while a sweep is in
# flight, and it carries a deliberately-blocked inline script. Without this exclusion, running the
# generator during a sweep hashes that script and writes a bogus twentieth hash into all seventy-odd
# pages. Caught by --check on 2026-08-15, before it could.
SKIP_FILES = {"preview.html", "_csp-selftest.html"}

MARKER = "<!-- CSP: generated by scripts/gen-csp.py. Do not hand-edit; run the script. -->"
TAG_RE = re.compile(
    r'[ \t]*' + re.escape(MARKER) + r'\s*\n[ \t]*<meta http-equiv="Content-Security-Policy"[^>]*>\n',
    re.S,
)
INLINE_SCRIPT_RE = re.compile(r"<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>", re.S)

# Origins, each one traced to what actually loads it. Anything not on this list is refused, which
# is the point: it is also what stops a future "just drop in this CDN widget" from working
# silently.
SOURCES = {
    # The Firebase SDK is imported as ES modules straight from gstatic (firebase-app, -auth,
    # -firestore, -storage @ 10.12.0) by js/marketplace.js, js/phone.js, js/account-nav.js and
    # js/submit.js. Without this, sign-in and the marketplace do not load at all.
    # apis.google.com is the second half of sign-in with Google: the SDK's popup flow loads
    # gapi's iframe helper (apis.google.com/js/api.js) on the sign-in click, then embeds the
    # authDomain iframe allowed under frame-src. Blocking either one is the same
    # auth/internal-error.
    "script-src": ["'self'", "https://www.gstatic.com", "https://apis.google.com"],
    "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
    "font-src": ["'self'", "https://fonts.gstatic.com"],
    # data: covers inline SVG-as-image and the QR code canvas export on the phone page.
    "img-src": ["'self'", "data:", "https://*.firebasestorage.app"],
    # Firestore reads, Auth token exchange, Storage uploads for submission screenshots, the
    # billing service on Render, and the contact form.
    "connect-src": [
        "'self'",
        "https://*.googleapis.com",
        "https://*.firebasestorage.app",
        "https://archie-4f35.onrender.com",
        "https://formspree.io",
    ],
    # The booking widget on /contact/ and /questionnaire/, and the Firebase Auth helper
    # iframe (authDomain in js/account-nav.js and friends), which signInWithPopup embeds on
    # the sign-in click. The page-load CSP sweep can never see that one: it only exists
    # after a user gesture, which is how blocking it shipped as auth/internal-error on
    # "Continue with Google" (found live 2026-08-16).
    "frame-src": ["https://calendar.google.com", "https://archie-77170.firebaseapp.com"],
    "form-action": ["'self'", "https://formspree.io"],
    # Nothing on this site embeds a plugin or needs to rewrite its own base URL, and both are
    # standard injection footholds.
    "object-src": ["'none'"],
    "base-uri": ["'none'"],
}


def page_files():
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if name.endswith(".html") and name not in SKIP_FILES:
                yield os.path.join(dirpath, name)


def script_hashes():
    """One sha256 per distinct inline <script> body across the whole site."""
    digests = set()
    for path in page_files():
        with open(path, encoding="utf-8", errors="ignore") as fh:
            body = fh.read()
        for match in INLINE_SCRIPT_RE.finditer(body):
            digest = hashlib.sha256(match.group(1).encode("utf-8")).digest()
            digests.add("'sha256-" + base64.b64encode(digest).decode("ascii") + "'")
    return sorted(digests)


def policy():
    hashes = script_hashes()
    parts = []
    parts.append("default-src 'self'")
    for name, values in SOURCES.items():
        if name == "script-src":
            values = values + hashes
        parts.append(name + " " + " ".join(values))
    return "; ".join(parts)


def tag_for(policy_text):
    return (
        "  " + MARKER + "\n"
        '  <meta http-equiv="Content-Security-Policy" content="' + policy_text + '" />\n'
    )


def apply(check_only):
    text = policy()
    tag = tag_for(text)
    changed, missing = [], []

    for path in page_files():
        rel = os.path.relpath(path, ROOT)
        with open(path, encoding="utf-8") as fh:
            body = fh.read()

        existing = TAG_RE.search(body)
        if existing and existing.group(0) == tag:
            continue

        if check_only:
            (changed if existing else missing).append(rel)
            continue

        if existing:
            body = body[: existing.start()] + tag + body[existing.end() :]
        else:
            # Straight after <meta charset>, so the policy is parsed before anything it governs.
            anchor = re.search(r'[ \t]*<meta charset="[^"]*"\s*/?>\n', body)
            if not anchor:
                missing.append(rel)
                continue
            body = body[: anchor.end()] + tag + body[anchor.end() :]
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(body)
        changed.append(rel)

    if check_only:
        if missing or changed:
            for rel in missing:
                print("  no CSP tag:  %s" % rel)
            for rel in changed:
                print("  stale CSP:   %s" % rel)
            print("\nRun: python3 scripts/gen-csp.py")
            return 1
        print("gen-csp: every page carries the current policy (%d inline script hashes)."
              % len(script_hashes()))
        return 0

    for rel in missing:
        print("  SKIPPED (no <meta charset> to anchor to): %s" % rel)
    print("gen-csp: wrote the policy into %d pages (%d inline script hashes)."
          % (len(changed), len(script_hashes())))
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(apply("--check" in sys.argv))
