/* Write the published posts into blog/ as static HTML.
 *
 * THE BUG THIS FIXES. The blog index's feed was two empty elements, <article id="resourceFeatured">
 * and <div id="resourceGrid">, that js/blog.js filled from assets/articles.json on load. The page
 * carried 183 characters of readable text and named none of its fifteen posts: to a crawler, an
 * answer engine or a link preview, the blog hub linked to nothing and described nothing. The posts
 * themselves are real static pages and were always readable; what was missing was the one page
 * that says they exist and what each is about.
 *
 * WHAT THIS DOES NOT CHANGE. js/blog.js still fetches articles.json and still rewrites the feed on
 * load, because search and the category filter rerender on every keystroke and neither can be
 * baked. What ships in the markup is the unfiltered list in file order, which is exactly what the
 * script draws before anybody types anything.
 *
 * The renderer lives in js/blog-card.js and both callers import it, for the reason set out in
 * that file and in js/addon-card.js: one card builder, not two that drift.
 *
 * Usage:
 *   node scripts/gen-blog.mjs           write the feed into the page
 *   node scripts/gen-blog.mjs --check   exit 1 if the page is out of date
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { makeFeatured, makeCard, normalizeArticles } from "../js/blog-card.js";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const PAGE = path.join(ROOT, "blog", "index.html");
const DATA = path.join(ROOT, "assets", "articles.json");

/* Two regions, because the featured post and the grid are separate elements in the page and the
 * script fills them separately. Each is replaced between its own opening and closing tag. */
const REGIONS = [
  {
    open: '<article id="resourceFeatured" class="resource-featured">',
    close: "</article>",
    render: (articles) => (articles.length ? makeFeatured(articles[0]) : ""),
  },
  {
    open: '<div id="resourceGrid" class="resource-grid" role="list">',
    close: "</div>",
    render: (articles) => articles.slice(1).map(makeCard).join(""),
  },
];

const BANNER =
  "<!-- GENERATED by scripts/gen-blog.mjs from assets/articles.json. Do not hand-edit. " +
  "js/blog.js redraws this on load, and on every keystroke in the search box; this copy is " +
  "what everything that does not run scripts reads. -->";

/* The featured region holds <div>s and the grid holds <article>s, so the first closing tag after
 * the opening one is not the matching one. Count depth on whichever tag name the region uses. */
function regionBounds(html, region) {
  const start = html.indexOf(region.open);
  if (start === -1) throw new Error("not found in blog/index.html: " + region.open);
  const tag = region.close.slice(2, -1);
  const re = new RegExp("<" + tag + "\\b[^>]*>|</" + tag + ">", "g");
  re.lastIndex = start;
  let depth = 0;
  let m;
  while ((m = re.exec(html))) {
    depth += m[0] === region.close ? -1 : 1;
    if (depth === 0) return { start, end: m.index + m[0].length };
  }
  throw new Error("never closed in blog/index.html: " + region.open);
}

function main() {
  const check = process.argv.includes("--check");
  const articles = normalizeArticles(JSON.parse(fs.readFileSync(DATA, "utf8")));
  let html = fs.readFileSync(PAGE, "utf8");
  let changed = false;

  /* Last region first, so replacing it cannot move the earlier one's offsets. */
  for (const region of [...REGIONS].reverse()) {
    const { start, end } = regionBounds(html, region);
    const wanted = region.open + BANNER + region.render(articles) + region.close;
    if (html.slice(start, end) !== wanted) {
      changed = true;
      html = html.slice(0, start) + wanted + html.slice(end);
    }
  }

  if (!changed) {
    console.log(`gen-blog: clean. ${articles.length} posts in the page.`);
    return 0;
  }
  if (check) {
    console.log(
      "gen-blog: blog/index.html is out of date against assets/articles.json " +
      `(${articles.length} published posts).\n\nRun: node scripts/gen-blog.mjs`
    );
    return 1;
  }
  fs.writeFileSync(PAGE, html, "utf8");
  console.log(`gen-blog: wrote ${articles.length} posts into blog/.`);
  return 0;
}

process.exit(main());
