#!/usr/bin/env python3
"""gen-phone-mocks.py: the three Archie Mobile screens on archie/mobile/, drawn once.

The page shows three phone screens twice. Since 2026-09-18 the first showing is the stage:
one phone shell with all three screens inside it, one lit at a time as the reader scrolls,
the way the homepage's phone changes screens (js/mobile.js drives it). The second is the
stills, three separate drawings in a row, which is what a reader with reduced motion or no
JavaScript gets under the stage's captions. Until 2026-09-14 the page carried six
hand-written SVGs of the same three screens, and a styling change meant six edits, which is
how two halves drift: a card radius fixed in one and missed in the other reads as a bug
nobody can find. Until 2026-09-18 the second showing was a marquee (.mk-gallery); it went
when the stage took over the narrow layout, because the reader the stills are now for has
asked for no motion.

So the screens live here, as content plus components, and this writes both renderings into
the page between markers. Same arrangement as gen-marketplace.mjs and gen-blog.mjs: the
result is committed, and --check is what stops the committed markup drifting from its source.

BEATS. On the stage, pieces of a screen land as the scroll passes them: your message and the
draft that answers it, the skills one tile at a time. A screen builder marks a piece with
beat(markup, at), and what that does depends on the rendering being drawn: nothing in the
stills, where the whole screen is the resting state a crawler reads, and a day-beat group in
the stage, which js/mobile.js lights when the act's scroll reaches `at`. The same builder
draws both, so a piece can never be on one and missing from the other.

WHAT IT IS AND IS NOT. These are drawings of the app, not screenshots of it, and the
distinction is load-bearing: the app is in testing and its screens still move. What the
drawings owe the reader is that every element on them is one the app actually has, doing
what the app actually does. The CONTENT is the site's own and stays that way, because the
real screens carry a real person's mail.

THE LOOK IS THE IPHONE'S. The styling was first brought to the shipping app's on 2026-09-14,
from screenshots. On September 28, 2026 the screens were brought to the iPhone look as
archie-screen-kit.html draws it (the kit in the shared drive's Brand Assets folder, which
copies iosLight and iosDark from the app's src/theme.ts and its primitives from src/ui.tsx):
the cream ground with white cards on it and no outline anywhere, SF Pro with Georgia for
titles, a large title on a tab and a bar with a round glass back button over a pushed
screen, the floating glass tab bar, a card's answers as a rounded bar inside the message,
and Skills as a grid of tiles. Where this file and the kit disagree, the kit is right and
this file is the one to change; the numbers below carry the kit's names so a value can be
found in both.

WIDTHS ARE MEASURED, NOT GUESSED. Anything drawn around a string is sized from the string,
through tw() and the advance tables under it, and every line that wraps is wrapped by wrap(),
which uses the same tables. The version that shipped first used len(s) * 6.4, which is the
kind of estimate that is wrong in both directions on the same screen: it left a sentence
sitting off to one side of a bubble 25px too wide for it, and it drew the draft's container
narrower than the two lines inside it, which ran out the side.

    python3 scripts/gen-phone-mocks.py           write the page
    python3 scripts/gen-phone-mocks.py --check   fail if the page is out of date
"""

import base64
import math
import os
import re
import struct
import sys
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "archie", "mobile", "index.html")

BEGIN = "<!-- BEGIN phone mocks: generated by scripts/gen-phone-mocks.py. Do not hand-edit. -->"
END = "<!-- END phone mocks -->"
STAGE_BEGIN = "<!-- BEGIN phone stage: generated by scripts/gen-phone-mocks.py. Do not hand-edit. -->"
STAGE_END = "<!-- END phone stage -->"

# The screen is 390x800 inside a 412x822 shell, which is the geometry the page already used
# and the reason the outer viewBoxes below are unchanged. The kit's screen is 393x852; every
# measure below is the kit's own, and the 52 rows this screen is shorter come out of the empty
# page under the content, which is why the bottom bands are placed from the bottom edge.
W, H = 390.0, 800.0
SHELL_PAD = 11.0
SCREEN_R = 54.0           # the screen's corner (.ph), and the stage's --ph-r

# Vertical bands, top to bottom, in the kit's numbers.
STATUS_MID = 30.0         # the status bar's row, 22 tall at 19, on the island's middle
BAR_TOP = 61.0            # the row of a pushed screen's bar (.topbar), two under the status bar
BAR_BOTTOM = 111.0        # its 44 row, and 6 under it
PAGE_TOP = BAR_BOTTOM + 16.0
TITLE_TOP = 103.0         # a tab's large title (.page.titled), under the status bar's 59 and 44
MARGIN = 16.0             # the page's side margin, and a card's inside one
TABBAR_H = 62.0           # the floating tab bar: 62 tall, 21 off the bottom (.tabbar)
TABBAR_Y = H - 21.0 - TABBAR_H          # 717
TABROOM = 21.0 + TABBAR_H + 12.0        # the strip a conversation leaves it (.tabroom), 95
COMPOSER_H = 68.0                        # the message box's row, 44 with 12 above and below
COMPOSER_Y = H - TABROOM - COMPOSER_H   # 637: the chat screen's input bar, drawn at a fixed height

# ── ids ──────────────────────────────────────────────────────────────────────────────────
# Every gradient, mask, filter and clipPath needs an id unique across the whole page, because
# the stage puts three screens in one <svg>, the page holds four of them, and the browser
# resolves url(#x) document-wide.
_n = [0]


def uid(p):
    _n[0] += 1
    return "%s%d" % (p, _n[0])


# The shared pieces one drawing asks for (a symbol's mask, the glass's shadow, the fade under a
# bar) are made once per <svg> and written into its <defs>. new_doc() starts a drawing and
# doc_defs() hands back what it asked for.
_doc = {"defs": {}}


def new_doc():
    _doc["defs"] = {}


def doc_def(key, build):
    if key not in _doc["defs"]:
        i = uid(key.replace("-", ""))
        _doc["defs"][key] = (i, build(i))
    return _doc["defs"][key][0]


def doc_defs():
    return "<defs>%s</defs>" % "".join(m for _, m in _doc["defs"].values())


def esc(t):
    return (t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace("’", "&rsquo;").replace("·", "&middot;"))


def f(v):
    """Trim floats so the markup does not carry 14 decimals of nothing."""
    s = "%.1f" % float(v)
    return s[:-2] if s.endswith(".0") else s


# ── beats ────────────────────────────────────────────────────────────────────────────────
# Which act the screen being drawn belongs to on the stage, or None while the stills are
# being drawn. See BEATS in the docstring.
_beat = {"act": None}


def beat(markup, at):
    if _beat["act"] is None:
        return markup
    return '<g class="day-beat" data-act="%d" data-at="%s">%s</g>' % (
        _beat["act"], ("%.2f" % at).rstrip("0").rstrip("."), markup)


# ── text metrics ─────────────────────────────────────────────────────────────────────────
# Advance widths per 1000 units, so anything drawn around a string can be sized from the
# string. What was here before was len(s) * 6.4, and it is wrong in both directions at once:
# the bubble around "Anything from the accountant?" came out 25px wider than the sentence and
# left it sitting off to one side, while the container around the draft came out narrower
# than the two lines inside it and they ran out the side of it.
#
# The screens are set in SF Pro, the phone's own face, and their titles in Georgia bold, so
# those are the three tables. Each was measured in Chrome on a Mac on September 28, 2026 with
# canvas measureText: SF Pro through system-ui at 17px regular, Georgia at 17px regular and
# bold. SF Pro is not one width at every size: it is set a little looser the smaller it gets,
# about 1.2% of its width per point under 17, and each step of weight adds about 2.5%, which
# is what sf_scale() carries. A reader without SF Pro gets system-ui or Helvetica, both
# narrower, so a measure taken from SF errs wide for them, which is the safe side.
SF = "-apple-system,system-ui,BlinkMacSystemFont,'SF Pro Text','Helvetica Neue',Arial,sans-serif"
SERIF = "Georgia,'Times New Roman',serif"

_SF = {
    " ": 256, "a": 526, "b": 589, "c": 534, "d": 589, "e": 546, "f": 336, "g": 584,
    "h": 563, "i": 222, "j": 221, "k": 518, "l": 228, "m": 845, "n": 558, "o": 565,
    "p": 585, "q": 584, "r": 355, "s": 498, "t": 338, "u": 558, "v": 517, "w": 749,
    "x": 499, "y": 518, "z": 514,
    "A": 648, "B": 632, "C": 690, "D": 701, "E": 570, "F": 547, "G": 721, "H": 717,
    "I": 242, "J": 513, "K": 633, "L": 542, "M": 849, "N": 717, "O": 746, "P": 610,
    "Q": 746, "R": 628, "S": 612, "T": 608, "U": 712, "V": 648, "W": 942, "X": 653,
    "Y": 630, "Z": 636,
    "0": 604, "1": 438, "2": 578, "3": 602, "4": 618, "5": 593, "6": 611, "7": 544,
    "8": 613, "9": 611,
    ".": 271, ",": 271, ":": 271, ";": 271, "!": 286, "?": 487, "'": 271, "\u2019": 271,
    "-": 446, "\u00b7": 271, "/": 279, "(": 356, ")": 356, "&": 686, "+": 604, "%": 900,
    "\u2026": 779,
}

_GEORGIA = {
    " ": 241, "a": 504, "b": 560, "c": 454, "d": 574, "e": 483, "f": 325, "g": 509,
    "h": 582, "i": 293, "j": 292, "k": 536, "l": 286, "m": 881, "n": 591, "o": 539,
    "p": 571, "q": 560, "r": 410, "s": 432, "t": 345, "u": 575, "v": 497, "w": 737,
    "x": 505, "y": 492, "z": 444,
    "A": 671, "B": 654, "C": 642, "D": 749, "E": 653, "F": 599, "G": 725, "H": 815,
    "I": 390, "J": 518, "K": 694, "L": 604, "M": 927, "N": 767, "O": 744, "P": 610,
    "Q": 744, "R": 702, "S": 561, "T": 619, "U": 756, "V": 667, "W": 976, "X": 710,
    "Y": 615, "Z": 602,
    ".": 270, ",": 270, ":": 313, ";": 313, "!": 331, "?": 479, "'": 215, "\u2019": 227,
    "-": 374, "\u00b7": 279, "/": 469, "(": 375, ")": 375, "&": 710, "+": 643, "%": 817,
    "\u2026": 807,
}

_GEORGIA_BOLD = {
    " ": 254, "a": 596, "b": 646, "c": 531, "d": 663, "e": 572, "f": 393, "g": 577,
    "h": 680, "i": 354, "j": 346, "k": 632, "l": 344, "m": 1016, "n": 690, "o": 636,
    "p": 658, "q": 648, "r": 520, "s": 513, "t": 397, "u": 677, "v": 567, "w": 863,
    "x": 588, "y": 562, "z": 525,
    "A": 758, "B": 757, "C": 715, "D": 834, "E": 721, "F": 671, "G": 807, "H": 913,
    "I": 446, "J": 595, "K": 817, "L": 686, "M": 1023, "N": 839, "O": 820, "P": 701,
    "Q": 820, "R": 797, "S": 649, "T": 684, "U": 833, "V": 762, "W": 1126, "X": 809,
    "Y": 732, "Z": 689,
    ".": 328, ",": 328, ":": 367, ";": 367, "!": 376, "?": 548, "'": 269, "\u2019": 269,
    "-": 379, "\u00b7": 338, "/": 472, "(": 447, ")": 447, "&": 799, "+": 703, "%": 879,
    "\u2026": 942,
}

_SF_WEIGHT = {"400": 1.0, "500": 1.0245, "600": 1.049, "650": 1.061, "700": 1.0735}


def sf_scale(size, weight):
    return (1.0 + (17.0 - float(size)) * 0.0117) * _SF_WEIGHT.get(weight, 1.0)


def tw(s, size, serif=False, weight="400"):
    """How wide that string is, drawn. Deliberately a little generous, because every caller
    uses this to decide how much room to leave, and erring narrow is the one direction that
    shows."""
    if serif:
        table, digit, scale = (_GEORGIA_BOLD if weight in ("600", "700") else _GEORGIA), 560, 1.0
    else:
        table, digit, scale = _SF, 600, sf_scale(size, weight)
    units = 0
    for ch in s:
        # An emoji draws from the system's color font at about an em and a quarter, and the
        # variation selector and joiner beside one draw nothing at all. The one exception is
        # the multiplication cross on Dismiss, which is a text glyph and three quarters of an em.
        if ch in ("\ufe0f", "\u200d"):
            continue
        if ch == "\u2715":
            units += 762
            continue
        if ord(ch) >= 0x2300:
            units += 1235
            continue
        units += table.get(ch, digit if ch.isdigit() else 560)
    return units * float(size) / 1000.0 * scale * 1.01


def wrap(s, width, size, serif=False, weight="400"):
    """The lines a paragraph breaks into at `width`, greedily, the way the phone breaks them."""
    lines, cur = [], ""
    for word in s.split(" "):
        trial = word if not cur else cur + " " + word
        if cur and tw(trial, size, serif, weight) > width:
            lines.append(cur)
            cur = word
        else:
            cur = trial
    if cur:
        lines.append(cur)
    return lines


def clamp(lines, most, width, size, serif=False, weight="400"):
    """numberOfLines: at most `most` lines, the last one cut with an ellipsis when there was
    more, which is how the app shortens a line it has no room for."""
    if len(lines) <= most:
        return lines
    last = lines[most - 1] + " " + lines[most]
    while last and tw(last + "\u2026", size, serif, weight) > width:
        last = last[:-1]
    return lines[:most - 1] + [last.rstrip(" ,.") + "\u2026"]


def baseline(top, lh, size, serif=False):
    """Where a line's baseline sits when its line box starts at `top`, the way a browser centers
    a face's ascent and descent in the line height. SF Pro's are 0.95 and 0.24 of the size,
    Georgia's 0.917 and 0.219."""
    asc, desc = (0.917, 0.219) if serif else (0.952, 0.241)
    return top + (lh - (asc + desc) * size) / 2.0 + asc * size


# ── primitives ───────────────────────────────────────────────────────────────────────────


def rect(x, y, w, h, r=0, fill="none", stroke=None, sw=1, extra=""):
    s = '<rect x="%s" y="%s" width="%s" height="%s"' % (f(x), f(y), f(w), f(h))
    if r:
        s += ' rx="%s"' % f(r)
    s += ' fill="%s"' % fill
    if stroke:
        s += ' stroke="%s" stroke-width="%s"' % (stroke, f(sw))
    return s + extra + "/>"


def text(x, y, t, size=17, fill="var(--text)", weight="400", anchor="start", serif=False, extra=""):
    s = '<text x="%s" y="%s" font-size="%s" fill="%s" font-weight="%s" text-anchor="%s"' % (
        f(x), f(y), f(size), fill, weight, anchor)
    if serif:
        s += ' font-family="%s"' % SERIF
    return s + extra + ">%s</text>" % esc(t)


def circle(cx, cy, r, fill="none", stroke=None, sw=1, extra=""):
    s = '<circle cx="%s" cy="%s" r="%s" fill="%s"' % (f(cx), f(cy), f(r), fill)
    if stroke:
        s += ' stroke="%s" stroke-width="%s"' % (stroke, f(sw))
    return s + extra + "/>"


# ── symbols ──────────────────────────────────────────────────────────────────────────────
# The app draws SF Symbols on an iPhone. These are the kit's hand drawings of the same ones,
# copied from its sprite path for path, in its 24 box. A symbol with a shape cut out of it (the
# flap of an envelope, the hands of a clock) is cut with a mask, so the cut shows whatever the
# symbol stands on; {m:name} is where one goes, and sym() fills in that drawing's own id.
MASKS = {
    "basket": '<path d="M8.9 15.1v3.3M11.2 15.1v3.3M13.5 15.1v3.3M15.8 15.1v3.3" stroke="#000" stroke-width="1.15" stroke-linecap="round"/>',
    "gear": '<circle cx="12" cy="12" r="3" fill="#000"/>',
    "clock": '<path d="M12 6.7V12.2H7.7" fill="none" stroke="#000" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>',
    "dots": '<circle cx="7.5" cy="12" r="1.5" fill="#000"/><circle cx="12" cy="12" r="1.5" fill="#000"/><circle cx="16.5" cy="12" r="1.5" fill="#000"/>',
    "flap": '<path d="M3.6 6.6 12 12.9l8.4-6.3" fill="none" stroke="#000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>',
    "card": '<rect x="0" y="8.1" width="24" height="2.4" fill="#000"/><rect x="5.2" y="14.3" width="4.6" height="1.9" rx=".95" fill="#000"/>',
    "pencil": '<path d="M14.3 7 17 9.7" stroke="#000" stroke-width="1.1"/>',
}

_GEAR_TOOTH = '<rect x="10.15" y="3.1" width="3.7" height="4.6" rx="1.1"%s/>'

SYMBOLS = {
    # the two tab bars, filled, as Apple asks for on a tab bar
    "person2": '<g fill="currentColor"><circle cx="15.3" cy="8.8" r="3.2"/><path d="M9.5 18.1c0-2.9 2.5-4.9 5.8-4.9s5.8 2 5.8 4.9c0 .6-.4 1-1 1H10.5c-.6 0-1-.4-1-1z"/><circle cx="8" cy="9.7" r="2.6"/><path d="M2.9 18.2c0-2.5 2.1-4.2 5.1-4.2.9 0 1.7.2 2.4.5-1.1 1-1.7 2.2-1.8 3.6v1H3.8c-.5 0-.9-.4-.9-.9z"/></g>',
    "jobs": '<g fill="currentColor"><path d="M8.3 5.6H5.8A2.4 2.4 0 0 0 3.4 8v8a2.4 2.4 0 0 0 2.4 2.4h2.5z"/><rect x="9.6" y="5.6" width="4.8" height="12.8" rx=".4"/><path d="M15.7 5.6h2.5A2.4 2.4 0 0 1 20.6 8v8a2.4 2.4 0 0 1-2.4 2.4h-2.5z"/></g>',
    "basketfill": '<path d="M7.7 9.7 10.4 4.9M16.3 9.7 13.6 4.9" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/><rect x="2.7" y="9.6" width="18.6" height="2.9" rx="1.45" fill="currentColor"/><path d="M4.4 13.3h15.2l-1.1 5.5c-.2.9-.9 1.5-1.8 1.5H7.3c-.9 0-1.6-.6-1.8-1.5z" fill="currentColor" mask="url(#{m:basket})"/>',
    "gear": '<g fill="currentColor" mask="url(#{m:gear})"><circle cx="12" cy="12" r="7"/>' + "".join(
        _GEAR_TOOTH % (' transform="rotate(%d 12 12)"' % a if a else "") for a in range(0, 360, 45)) + "</g>",
    "grid": '<g fill="currentColor"><rect x="3.7" y="3.7" width="7.3" height="7.3" rx="1.8"/><rect x="13" y="3.7" width="7.3" height="7.3" rx="1.8"/><rect x="3.7" y="13" width="7.3" height="7.3" rx="1.8"/><rect x="13" y="13" width="7.3" height="7.3" rx="1.8"/></g>',
    "bubble": '<path d="M7.1 4.5h9.8a4.2 4.2 0 0 1 4.2 4.2v4.4a4.2 4.2 0 0 1-4.2 4.2h-5.8l-3.4 2.8c-.5.4-1.2 0-1.1-.6l.5-2.2A4.2 4.2 0 0 1 2.9 13.1V8.7a4.2 4.2 0 0 1 4.2-4.2z" fill="currentColor"/>',
    "sparkles": '<path fill="currentColor" d="M14.1 7.8Q15.5 13.2 20.8 14.6Q15.5 16 14.1 21.4Q12.7 16 7.4 14.6Q12.7 13.2 14.1 7.8ZM7.4 4.6Q8 7.2 10.5 7.8Q8 8.4 7.4 11Q6.8 8.4 4.3 7.8Q6.8 7.2 7.4 4.6ZM13.4 2.6Q13.75 4 15.1 4.3Q13.75 4.6 13.4 6Q13.05 4.6 11.7 4.3Q13.05 4 13.4 2.6Z"/>',
    "clockfill": '<circle cx="12" cy="12" r="9.3" fill="currentColor" mask="url(#{m:clock})"/>',
    "morefill": '<circle cx="12" cy="12" r="9.3" fill="currentColor" mask="url(#{m:dots})"/>',
    # marks on the skill tiles
    "envelope": '<rect x="2.6" y="5" width="18.8" height="14" rx="2.6" fill="currentColor" mask="url(#{m:flap})"/>',
    "tray": '<path d="M3 12.6h5.4c.4 0 .7.3.8.6.4 1.3 1.5 2.2 2.8 2.2s2.4-.9 2.8-2.2c.1-.3.4-.6.8-.6H21v5c0 1.2-.9 2-2 2H5c-1.1 0-2-.8-2-2z" fill="currentColor"/><path d="M3.9 12.3 6.3 7c.2-.6.8-.9 1.4-.9h8.6c.6 0 1.2.3 1.4.9l2.4 5.3" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><path d="M8.6 8.6h6.8M8.2 10.8h7.6" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>',
    "calendar": '<path d="M6.3 4.5h11.4a2.8 2.8 0 0 1 2.8 2.8v1.6h-17V7.3a2.8 2.8 0 0 1 2.8-2.8z" fill="currentColor"/><rect x="4.3" y="5.3" width="15.4" height="14.3" rx="2.1" fill="none" stroke="currentColor" stroke-width="1.6"/><g fill="currentColor">' + "".join(
        '<circle cx="%s" cy="%s" r=".9"/>' % (x, y) for y, xs in (("11.4", 5), ("13.8", 5), ("16.2", 3))
        for x in ("7.6", "9.8", "12", "14.2", "16.4")[:xs]) + "</g>",
    "card": '<rect x="2.6" y="5" width="18.8" height="14" rx="2.6" fill="currentColor" mask="url(#{m:card})"/>',
    "pencil": '<path d="M4.9 19.1l.9-3.5L16 5.4c.7-.7 1.8-.7 2.5 0l.1.1c.7.7.7 1.8 0 2.5L8.4 18.2z" fill="currentColor" mask="url(#{m:pencil})"/>',
    "mic": '<g fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><rect x="9" y="3.3" width="6" height="11.4" rx="3"/><path d="M5.9 11.3c0 3.4 2.7 6.1 6.1 6.1s6.1-2.7 6.1-6.1M12 17.4v3.3"/></g>',
    # Talk out loud: SF Symbols' waveform, which is what the app wears on an iPhone, traced bar
    # for bar into the microphone's box at the microphone's stroke
    "talk": '<path d="M4.5 10.7v2.6M7.5 7v10M10.5 3.5v17M13.5 8.2v7.6M16.5 5.4v13.2M19.5 9.9v4.2" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>',
    "plus": '<path d="M12 5.2v13.6M5.2 12h13.6" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/>',
    "hammer": '<g fill="currentColor" transform="rotate(45 12 12)"><rect x="10.85" y="9.2" width="2.3" height="12.4" rx="1.15"/><path d="M8.3 3.6h8.2c.6 0 1.1.5 1.1 1.1v2.8c0 .6-.5 1.1-1.1 1.1H9.9L6.6 7.2c-.6-.2-.6-1 0-1.2z"/></g>',
    # the buttons and the bars
    "stop": '<rect x="4.6" y="4.6" width="14.8" height="14.8" rx="2.6" fill="currentColor"/>',
    "play": '<path d="M7.4 5.1c0-1 1-1.5 1.8-1l10.3 6.8c.8.5.8 1.7 0 2.2L9.2 19.9c-.8.5-1.8-.1-1.8-1z" fill="currentColor"/>',
    "back": '<path d="M14.6 5.3 8 12l6.6 6.7" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/>',
    "down": '<path d="M5.3 9.2 12 15.7l6.7-6.5" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/>',
    "arrowup": '<path d="M12 19.4V5M6.5 10.5 12 5l5.5 5.5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>',
}


def mask_id(name):
    return doc_def("m-" + name, lambda i: (
        '<mask id="%s" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24">'
        '<rect width="24" height="24" fill="#fff"/>%s</mask>' % (i, MASKS[name])))


def sym(name, x, y, size, color):
    """A symbol in a `size` box whose top left is (x, y), in `color`."""
    body = re.sub(r"\{m:(\w+)\}", lambda m: mask_id(m.group(1)), SYMBOLS[name])
    return '<g transform="translate(%s,%s) scale(%s)" style="color:%s">%s</g>' % (
        f(x), f(y), "%.4f" % (size / 24.0), color, body)


def glass_shadow():
    """The soft cast under glass (--glass-cast), under the bend (lens) and the rim."""
    return doc_def("glass", lambda i: (
        '<filter id="%s" x="-20%%" y="-60%%" width="140%%" height="240%%">'
        '<feDropShadow dx="0" dy="5" stdDeviation="9" style="flood-color:var(--glass-cast)"/>'
        "</filter>" % i))


# ── the bend ──────────────────────────────────────────────────────────────────────────────
# Liquid Glass is told from frosted plastic by its rim: whatever is under it bends there, pulled
# in from further inside and folded over at the very edge, so a line of type running under a tab
# bar kinks as it reaches the curve. A page in a browser cannot do that to what is behind it (the
# one way is an SVG filter in backdrop-filter, which Safari ignores), but a drawing can, because a
# drawing knows what is under its glass: the screen's own content, drawn a second time inside the
# glass's outline and pushed through a displacement map shaped like the glass. That works in every
# browser, which is why it is done here rather than in CSS. Jett asked for the bend on October 4,
# 2026, after the glass had been "a frosted fill, a bright rim and a soft cast" since September.

LENS_BEZEL = 18.0   # how far in from the rim the bend reaches
LENS_PULL = 18.0    # how far the rim reaches inward for what it shows; past half the bezel it folds
LENS_SCALE = 2      # map pixels per point; the bend is smooth, so two is plenty


def png(w, h, rgb_rows):
    """A PNG from rows of RGB bytes, with nothing but the standard library."""
    def chunk(kind, data):
        return (struct.pack(">I", len(data)) + kind + data
                + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))
    raw = b"".join(b"\x00" + row for row in rgb_rows)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def lens_map(w, h, r):
    """The displacement map for a w by h rounded rectangle of corner r, as a data URI: red and
    green are how far across and down to look for what shows at each point, 0.5 being nowhere.
    Inside the bezel the look is along the inward normal, strongest at the rim and fading as the
    square of the distance in, which is the slope of a convex edge."""
    mw, mh = int(round(w * LENS_SCALE)), int(round(h * LENS_SCALE))
    hx, hy = w / 2.0, h / 2.0
    rows = []
    for j in range(mh):
        y = (j + 0.5) / LENS_SCALE
        row = bytearray()
        for i in range(mw):
            x = (i + 0.5) / LENS_SCALE
            qx, qy = abs(x - hx) - (hx - r), abs(y - hy) - (hy - r)
            sx, sy = (1 if x >= hx else -1), (1 if y >= hy else -1)
            if qx > 0 and qy > 0:
                ln = math.hypot(qx, qy)
                inside = r - ln
                nx, ny = -sx * qx / ln, -sy * qy / ln
            elif qx > qy:
                inside, nx, ny = r - qx, -sx, 0.0
            else:
                inside, nx, ny = r - qy, 0.0, -sy
            t = inside / LENS_BEZEL
            m = LENS_PULL * (1 - t) ** 2 if 0 <= t < 1 else 0.0
            row += bytes((int(round(255 * (0.5 + nx * m / (2 * LENS_PULL)))),
                          int(round(255 * (0.5 + ny * m / (2 * LENS_PULL)))), 128))
        rows.append(bytes(row))
    return "data:image/png;base64," + base64.b64encode(png(mw, mh, rows)).decode()


def lens(under, x, y, w, h, r):
    """The bend: `under` (the id of the content the glass lies on) drawn again inside the glass's
    outline, bent at the rim, lightly frosted and a little richer, the way Liquid Glass shows what
    it covers. Drawn under the glass's own fill, which thins it to glass."""
    key = "lens-%s-%s-%s-%s-%s" % (f(x), f(y), f(w), f(h), f(r))
    box = 'x="%s" y="%s" width="%s" height="%s"' % (f(x), f(y), f(w), f(h))
    fid = doc_def(key, lambda i: (
        '<filter id="%s" filterUnits="userSpaceOnUse" %s color-interpolation-filters="sRGB">'
        '<feImage href="%s" %s preserveAspectRatio="none" result="map"/>'
        '<feDisplacementMap in="SourceGraphic" in2="map" scale="%s" xChannelSelector="R"'
        ' yChannelSelector="G" result="bent"/>'
        '<feGaussianBlur in="bent" stdDeviation="1.4"/>'
        '<feColorMatrix type="saturate" values="1.4"/></filter>'
        % (i, box, lens_map(w, h, r), box, f(2 * LENS_PULL))))
    cid = doc_def(key + "-clip", lambda i: (
        '<clipPath id="%s">%s</clipPath>' % (i, rect(x, y, w, h, r, "#000"))))
    return ('<g clip-path="url(#%s)"><use href="#%s" filter="url(#%s)"/></g>' % (cid, under, fid))


# ── the Ember faces, lifted from the app's own marks ──────────────────────────────────────
# Each face is the app's own drawing (src/app/ember-gen.ts in the Archie repo), parts and light
# alike, drawn in its 200-unit space and framed through the app's window: a square 182 across at
# (9, 15), which is what puts Ember the size in his circle that he is in the app. Brought up to the
# app's drawing on October 2, 2026: the light from the upper left (a sheen and a rim shade on the
# ball, a highlight on each foot, two catchlights per eye), one pink for the cheeks, the curved
# antenna, and the tighter window. Colors and pieces per agent, the way the app deals them from the
# agent itself, so two agents never look like twins.
FACES = {
    "ember":  dict(hi="#F0AB80", mid="#E28D5E", lo="#C36A3D", eyes="pill", extra="peak"),
    "teal":   dict(hi="#63B2A9", mid="#3E9A92", lo="#2E7C75", eyes="round", extra="glasses"),
    "gold":   dict(hi="#D3A855", mid="#BB8C33", lo="#9A7226", eyes="pill", extra="antenna"),
    "plum":   dict(hi="#B48CD9", mid="#996FBE", lo="#7B549E", eyes="round", extra="peak"),
}
# The app's window onto the drawing (`FRAME` in ember-gen.ts), and how far a face wearing
# something on its head sits lower in it (`TOPPED_DROP`).
WINDOW_X, WINDOW_Y, WINDOW = 9, 15, 182
TOPPED_DROP = 4
BLUSH = "#EE7C86"


def face_body(kind):
    c = FACES[kind]
    g, sh, rim, bl, sd = uid("em"), uid("es"), uid("er"), uid("eb"), uid("ed")
    o = ['<defs><linearGradient id="%s" x1="0" y1="0.18" x2="0" y2="1">'
         '<stop offset="0" stop-color="%s"/><stop offset="0.55" stop-color="%s"/>'
         '<stop offset="1" stop-color="%s"/></linearGradient>' % (g, c["hi"], c["mid"], c["lo"]),
         '<radialGradient id="%s" cx="0.35" cy="0.27" r="0.55"><stop offset="0" stop-color="#FFFFFF"'
         ' stop-opacity=".34"/><stop offset="0.5" stop-color="#FFFFFF" stop-opacity=".08"/>'
         '<stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/></radialGradient>' % sh,
         '<radialGradient id="%s" cx="0.42" cy="0.38" r="0.68"><stop offset="0.68" stop-color="%s"'
         ' stop-opacity="0"/><stop offset="1" stop-color="%s" stop-opacity=".42"/></radialGradient>'
         % (rim, c["lo"], c["lo"]),
         '<radialGradient id="%s"><stop offset="0" stop-color="%s" stop-opacity=".55"/>'
         '<stop offset="1" stop-color="%s" stop-opacity="0"/></radialGradient>' % (bl, BLUSH, BLUSH),
         '<radialGradient id="%s"><stop offset="0" stop-color="#44403B" stop-opacity=".2"/>'
         '<stop offset="0.6" stop-color="#44403B" stop-opacity=".1"/><stop offset="1"'
         ' stop-color="#44403B" stop-opacity="0"/></radialGradient></defs>' % sd]
    topped = c["extra"] in ("peak", "antenna")
    if topped:
        o.append('<g transform="translate(0 %d)">' % TOPPED_DROP)
    o.append('<ellipse cx="100" cy="177" rx="40" ry="7" fill="url(#%s)"/>' % sd)
    o.append('<ellipse cx="82" cy="169" rx="10" ry="7.5" fill="%s"/>' % c["lo"])
    o.append('<ellipse cx="118" cy="169" rx="10" ry="7.5" fill="%s"/>' % c["lo"])
    o.append('<ellipse cx="80" cy="166.8" rx="4.6" ry="2.2" fill="#FFFFFF" opacity=".16"/>')
    o.append('<ellipse cx="116" cy="166.8" rx="4.6" ry="2.2" fill="#FFFFFF" opacity=".16"/>')
    if c["extra"] == "peak":
        o.append('<path d="M100 30 L87 58 L113 58 Z" fill="%s" stroke="%s" stroke-width="8"'
                 ' stroke-linejoin="round"/>' % (c["lo"], c["lo"]))
    if c["extra"] == "antenna":
        o.append('<path d="M100 52 Q98 36 104 28" stroke="%s" stroke-width="6" fill="none"'
                 ' stroke-linecap="round"/>' % c["lo"])
        o.append('<circle cx="105" cy="24" r="8" fill="%s"/>' % c["lo"])
    o.append('<circle cx="100" cy="108" r="60" fill="url(#%s)"/>' % g)
    o.append('<circle cx="100" cy="108" r="60" fill="url(#%s)"/>' % sh)
    o.append('<circle cx="100" cy="108" r="60" fill="url(#%s)"/>' % rim)
    o.append('<ellipse cx="65" cy="125" rx="10.5" ry="6.5" fill="url(#%s)"/>' % bl)
    o.append('<ellipse cx="135" cy="125" rx="10.5" ry="6.5" fill="url(#%s)"/>' % bl)
    for ex in (78, 122):
        if c["eyes"] == "pill":
            eye = ('<rect x="-7" y="-14" width="14" height="28" rx="7" fill="#2A2521"/>'
                   '<circle cx="-2.5" cy="-7" r="2.5" fill="#FFF" opacity=".85"/>'
                   '<circle cx="2.4" cy="6" r="1.4" fill="#FFF" opacity=".5"/>')
        else:
            eye = ('<circle cx="0" cy="0" r="10" fill="#2A2521"/>'
                   '<circle cx="-3" cy="-3.5" r="3" fill="#FFF" opacity=".85"/>'
                   '<circle cx="3.2" cy="4" r="1.5" fill="#FFF" opacity=".5"/>')
        o.append('<g transform="translate(%d,103)">%s</g>' % (ex, eye))
    o.append('<path d="M93 132 Q100 138 107 132" stroke="#2A2521" stroke-width="3.2" fill="none"'
             ' stroke-linecap="round"/>')
    if c["extra"] == "glasses":
        o.append('<g fill="none" stroke="#2A2521" stroke-width="3.4" opacity=".85">'
                 '<circle cx="78" cy="103" r="17"/><circle cx="122" cy="103" r="17"/>'
                 '<path d="M95 103h10" stroke-linecap="round"/></g>')
    if c["extra"] == "antenna":
        o.append('<g fill="%s" opacity=".55"><circle cx="60" cy="118" r="2.6"/>'
                 '<circle cx="68" cy="126" r="2.6"/><circle cx="56" cy="130" r="2.6"/>'
                 '<circle cx="140" cy="118" r="2.6"/><circle cx="132" cy="126" r="2.6"/>'
                 '<circle cx="144" cy="130" r="2.6"/></g>' % c["lo"])
    if topped:
        o.append("</g>")
    return "".join(o)


def avatar(x, y, size, kind, dot=False):
    """A face in a `size` circle whose top left is (x, y), on the terracotta wash the app hands
    every face (--face-ground). The drawing goes in through the app's window, so the face is
    the size in its circle that it is in the app."""
    r = size / 2.0
    cx, cy = x + r, y + r
    cid = uid("fc")
    o = ['<defs><clipPath id="%s"><circle cx="%s" cy="%s" r="%s"/></clipPath></defs>' % (
        cid, f(cx), f(cy), f(r))]
    o.append(circle(cx, cy, r, "var(--face-ground)"))
    o.append('<g clip-path="url(#%s)"><g transform="translate(%s,%s) scale(%s) translate(%d %d)">%s</g></g>' % (
        cid, f(x), f(y), "%.4f" % (size / float(WINDOW)), -WINDOW_X, -WINDOW_Y, face_body(kind)))
    if dot:
        # The running dot on the face in the bar (facewrap .dot): 30% of the face, one point past
        # its corner, ringed in the page's own ground. It is the one place "running" is stated
        # without a word for it.
        d = max(8.0, round(size * 0.3))
        o.append(circle(x + size + 1 - d / 2, y + size + 1 - d / 2, d / 2 - 1, "var(--green)", "var(--bg)", 2))
    return "".join(o)


# ── chrome ───────────────────────────────────────────────────────────────────────────────
def status_bar(clock="7:00"):
    """The phone's own bar. Nothing here is Archie: it is what makes the rest read as a phone,
    so it is in the phone's own ink (--status-ink), black over a light app and white over a
    dark one, rather than the app's.

    The kit's layout: the clock centered in the 156 left of the island, and the signal, the
    Wi-Fi and the battery centered as one group in the 156 right of it, all on the island's
    middle row. The battery is full, and so are the bars, because a drawing is not a phone that
    happens to be at 65% (Jett, 2026-09-18).

    The clock reads 7:00, which is the homepage's morning brief and the site's own hour. It read
    9:41 until 2026-09-17: the time Apple stops every clock in its own marketing, and the plainest
    way a drawing of a generic phone tells a reader it is meant to be an iPhone. The drawing is
    ours and so is the hour on it. The kit keeps 9:41, and this is the one place the two differ
    on purpose.
    """
    ink = "var(--status-ink)"
    o = [text(78, baseline(STATUS_MID - 11, 22, 17.5), clock, 17.5, ink, "650", "middle",
              extra=' letter-spacing="-0.2"')]
    x0 = W - 78 - (20 + 5 + 18 + 5 + 28.5) / 2
    top = STATUS_MID - 6.5
    # signal: four bars on one baseline, all of them lit
    o.append('<g transform="translate(%s,%s)">' % (f(x0), f(top))
             + "".join(rect(x, 13 - h, 3.7, h, 1.1, ink) for x, h in ((0, 4.8), (5.4, 7.5), (10.8, 10.3), (16.2, 13)))
             + "</g>")
    # Wi-Fi: two arcs over a dot, in the kit's 16x12 box drawn 18x13
    o.append('<g transform="translate(%s,%s) scale(1.0833)" fill="none" stroke="%s" stroke-width="2.55"'
             ' stroke-linecap="round"><path d="M4.66 6.88A4.74 4.74 0 0 1 11.34 6.88"/>'
             '<path d="M1.33 4.07A9.48 9.48 0 0 1 14.68 4.07"/>'
             '<circle cx="8" cy="9.68" r="1.75" fill="%s" stroke="none"/></g>' % (f(x0 + 25 + 0.33), f(top), ink, ink))
    # battery: a body at a third of the ink, full, and its cap
    o.append('<g transform="translate(%s,%s) scale(1.0556)" fill="%s">' % (f(x0 + 48), f(top - 0.3), ink)
             + '<rect width="24" height="13" rx="4" fill-opacity=".35"/><rect width="24" height="13" rx="4"/>'
             '<path d="M25.3 4.4v4.2a2.2 2.2 0 0 0 0-4.2z" fill-opacity=".4"/></g>')
    return "".join(o)


def glass_circle(cx, cy, r):
    """A bar button (barbtn glass): a 44 circle of glass with a bright rim. The cast is thrown by
    a disc of the page's ground under the glass rather than by the glass, which is half clear and
    would show its own shadow through itself. Nothing reaches it to bend: the bar it sits in
    paints its own ground, in the app as here."""
    return (circle(cx, cy, r, "var(--bg)", extra=' filter="url(#%s)"' % glass_shadow())
            + circle(cx, cy, r, "var(--glass)")
            + circle(cx, cy, r - 0.25, "none", "var(--glass-rim)", 0.5)
            + circle(cx, cy, r + 0.375, "none", "var(--glass-edge)", 0.75))


def top_bar(name, kind):
    """The bar over a pushed screen (TopBar in src/ui.tsx), here the agent's own bar: the one way
    back as a round glass button, and the agent's face and name centered, with the chevron that
    picks another agent when there is more than one. The page's own ground, no rule and no
    shadow; what sets it apart from the words going under it is the short fade below it."""
    fade = doc_def("fade", lambda i: (
        '<linearGradient id="%s" x1="0" y1="0" x2="0" y2="1">'
        '<stop offset="0" style="stop-color:var(--bg)"/>'
        '<stop offset="1" style="stop-color:var(--bg);stop-opacity:0"/></linearGradient>' % i))
    o = [rect(0, 0, W, BAR_BOTTOM, 0, "var(--bg)"),
         rect(0, BAR_BOTTOM, W, 14, 0, "url(#%s)" % fade)]
    o.append(glass_circle(MARGIN + 22, BAR_TOP + 22, 22))
    o.append(sym("back", MARGIN + 10, BAR_TOP + 10, 24, "var(--text)"))
    nw = tw(name, 18, serif=True, weight="700")
    block = 30 + 6 + nw + 6 + 14
    x = W / 2 - block / 2
    o.append(avatar(x, BAR_TOP + 7, 30, kind, dot=True))
    o.append(text(x + 36, baseline(BAR_TOP + 11, 22, 18, True), name, 18, "var(--text)", "700", serif=True))
    o.append(sym("down", x + 36 + nw + 6, BAR_TOP + 15, 14, "var(--muted)"))
    return "".join(o)


APP_TABS = [("Agents", "person2"), ("Jobs", "jobs"), ("Marketplace", "basketfill"), ("Settings", "gear")]
# The bar inside an agent. Dashboard and Jobs are the desktop's words for the same tabs; the bar
# read Now and Work until 2026-09-21.
AGENT_TABS = [("Dashboard", "grid"), ("Chat", "bubble"), ("Skills", "sparkles"),
              ("Routines", "clockfill"), ("More", "morefill")]


def tab_bar(tabs, active, marked=None, under=None):
    """The tab bar as iOS 26 draws it (FloatingTabs): a 62 capsule of glass 21 off the bottom,
    a filled symbol over a 10 point word, the chosen tab in the accent over a gray lens and the
    rest in the ink. `marked` puts the green dot on a tab's symbol, which says something is in
    flight behind it. `under` is the id of what the bar lies over, when anything reaches it, and
    draws the bend at its rim (lens)."""
    x0, w = MARGIN, W - 2 * MARGIN
    cell = (w - 8) / len(tabs)
    at = [t for t, _ in tabs].index(active)
    o = [rect(x0, TABBAR_Y, w, TABBAR_H, TABBAR_H / 2, "var(--bg)",
              extra=' filter="url(#%s)"' % glass_shadow()),
         lens(under, x0, TABBAR_Y, w, TABBAR_H, TABBAR_H / 2) if under else "",
         rect(x0, TABBAR_Y, w, TABBAR_H, TABBAR_H / 2, "var(--glass)"),
         rect(x0 + 0.25, TABBAR_Y + 0.25, w - 0.5, TABBAR_H - 0.5, TABBAR_H / 2 - 0.25, "none", "var(--glass-rim)", 0.5),
         rect(x0 - 0.375, TABBAR_Y - 0.375, w + 0.75, TABBAR_H + 0.75, TABBAR_H / 2 + 0.375, "none", "var(--glass-edge)", 0.75),
         rect(x0 + 4 + at * cell, TABBAR_Y + 4, cell, 54, 27, "var(--lens)")]
    for i, (label, symbol) in enumerate(tabs):
        cx = x0 + 4 + cell * (i + 0.5)
        col = "var(--accent)" if label == active else "var(--text)"
        o.append(sym(symbol, cx - 12.5, TABBAR_Y + 11.5, 25, col))
        if label == marked:
            o.append(circle(cx + 3.2, TABBAR_Y + 15, 3.75, "var(--green)", "var(--card)", 1.5))
        o.append(text(cx, baseline(TABBAR_Y + 39.5, 12, 10), label, 10, col, "600", "middle"))
    return "".join(o)


def pill(x, y, label, tone):
    """A small state marker (Pill): `live` is green on its wash, `quiet` the second ink on gray."""
    fg, bg = {"live": ("var(--green)", "var(--green-sub)"), "quiet": ("var(--text2)", "var(--soft)")}[tone]
    w = tw(label, 12, weight="600") + 20
    return rect(x, y, w, 21, 10.5, bg) + text(x + 10, baseline(y + 3, 15, 12), label, 12, fg, "600"), w


def capsule_width(label):
    return 14 + 16 + 6 + tw(label, 15, weight="600") + 14


def capsule_button(right, y, label, glyph, fill):
    """A small capsule (IosButton small): 44 tall, a 16 symbol and 15 point words, white on its
    fill, standing with its right edge at `right`. No edge and nothing under it."""
    w = capsule_width(label)
    x = right - w
    return (rect(x, y, w, 44, 22, fill) + sym(glyph, x + 14, y + 14, 16, "var(--on-fill)")
            + text(x + 36, baseline(y + 12, 20, 15), label, 15, "var(--on-fill)", "600"))


# ── screen 1: the agents on your computer ────────────────────────────────────────────────
# Each card is the app's (AgentList in src/screens/Agents.tsx): the face and the name with Start
# or Stop beside them, the last thing the agent said, then whether it is running and how long
# ago that was. The times are in the app's own words (howLongAgo in src/when.ts), which says
# "40 minutes ago" and "1 day ago" where this drawing used to say "40m ago" and "Yesterday".
# None of these agents has a purpose written, so the line the app puts under a name for one is
# not drawn rather than made up.
AGENTS = [
    dict(name="Email Manager", kind="ember", running=True,
         said="\U0001F4E7 Twelve came in overnight. Two need you, and the other ten are filed.",
         when="40 minutes ago", routines=2),
    dict(name="Bookkeeper", kind="teal", running=False,
         said="Four receipts filed. One from the hardware shop has no total on it, so I left it alone.",
         when="1 day ago", skills=2, routines=1),
    dict(name="Leads", kind="gold", running=False,
         said="Two new leads overnight. Dana asked about gutters, and the reply is drafted.",
         when="9 hours ago", skills=1, routines=2),
]
# The list goes on past the bottom of the screen, the way a list of four does on a phone, so the
# fourth card runs under the tab bar and the bar has something to bend at its rim (lens). It is
# the only thing on the three screens that reaches the glass, and it is there for that reason.
UNDER_BAR = dict(name="Calendar", kind="plum", running=False,
                 said="Thursday is full. Friday at 10 is open for the Meyer estimate.",
                 when="2 days ago", skills=1, routines=1)


def count(n, word):
    return "%d %s%s" % (n, word, "" if n == 1 else "s")


def screen_agents():
    """The Agents tab: its large title, which computer this is all read from under it, and a
    card per agent, white on the cream with no outline. The line under the title said "Your Mac"
    until September 28, 2026; the kit says "Your computer", because Archie runs on Windows too
    and half the people looking at the picture are on the other one."""
    o = [status_bar(),
         text(MARGIN, baseline(TITLE_TOP, 41, 34, True), "Agents", 34, "var(--text)", "700", serif=True),
         text(MARGIN, baseline(TITLE_TOP + 41, 20, 15), "Your computer", 15, "var(--muted)")]
    y = TITLE_TOP + 41 + 20 + 16
    right = W - 2 * MARGIN
    inner = W - 4 * MARGIN
    name_x = 2 * MARGIN + 44 + 12
    for n, a in enumerate(AGENTS + [UNDER_BAR]):
        if n == len(AGENTS):
            # y is the last card's foot and the 12 after it, which is the least room left over the
            # bar: the three that are read end above it, and only the one after them runs under.
            assert y <= TABBAR_Y, "the agent cards run under the tab bar: drop a line from one"
        # The first agent is the one the next two screens are inside, so its count is read off
        # the skills screen rather than typed twice. A specialist counts as a skill, the way the
        # app counts one (madeOf in Agents.tsx), so Writer makes it five.
        skills = a.get("skills", len(SKILLS) + len(SPECIALISTS))
        meta = "%s \u00b7 %s, %s" % (a["when"], count(skills, "skill"), count(a["routines"], "routine"))
        label, glyph, fill = (("Stop", "stop", "var(--red-fill)") if a["running"]
                              else ("Start", "play", "var(--green-fill)"))
        # The name is not cut short: it wraps beside the button, as the app's heading does.
        name = wrap(a["name"], right - capsule_width(label) - 12 - name_x, 20, True, "700")
        row = max(44.0, 24.0 * len(name))
        said = clamp(wrap(a["said"], inner, 13), 2, inner, 13)
        ch = MARGIN + row + 8 + 20 * len(said) + 8 + 21 + MARGIN
        top = y + MARGIN
        c = [rect(MARGIN, y, W - 2 * MARGIN, ch, 26, "var(--card)"),
             avatar(2 * MARGIN, top + (row - 44) / 2, 44, a["kind"])]
        for i, ln in enumerate(name):
            c.append(text(name_x, baseline(top + (row - 24 * len(name)) / 2 + 24 * i, 24, 20, True),
                          ln, 20, "var(--text)", "700", serif=True))
        c.append(capsule_button(right, top + (row - 44) / 2, label, glyph, fill))
        ty = top + row + 8
        for i, ln in enumerate(said):
            c.append(text(2 * MARGIN, baseline(ty + 20 * i, 20, 13), ln, 13, "var(--text2)"))
        py = ty + 20 * len(said) + 8
        p, pw = pill(2 * MARGIN, py, "Running" if a["running"] else "Stopped",
                     "live" if a["running"] else "quiet")
        c.append(p)
        c.append(text(2 * MARGIN + pw + 8, baseline(py + 0.5, 20, 13), meta, 13, "var(--muted)"))
        o.append("".join(c))
        y += ch + 12
    under = uid("under")
    return ('<g id="%s">%s</g>' % (under, "".join(o))
            + tab_bar(APP_TABS, "Agents", under=under))


# ── screen 2: the conversation, and what a draft offers ──────────────────────────────────
# The three screens are one person's phone, so the agent you are talking to here and the
# agent whose skills the third screen lists is the one at the top of the first screen's list.
AGENT_NAME = AGENTS[0]["name"]

# The answers under a draft are the app's own labels, emoji and all, from the Archie repo's
# texts/replies/card.rs. They were line icons until 2026-09-18, which is not how the app draws
# them (Jett: the mockup should have emojis like it usually would). Each one takes its color
# from its words, the way the app reads them (toneOf in src/words.ts): a yes is green, a change
# is gold, the way out is gray, anything else the accent. Send later is a yes for a later time and
# wears the accent, since September 28, 2026, when green read as a second Send beside the first.
ACTIONS = ["\u2705 Send", "\u270f\ufe0f Edit it", "\u23f0 Send later", "\u2715 Dismiss"]

AFFIRM = re.compile(r"^(yes|confirm|approve|ok|okay|do it|go ahead|send|apply|keep it|looks good|sounds good)\b")
DECLINE = re.compile(r"^(no|not now|cancel|dismiss|stop|discard|drop it|never ?mind|don'?t|don\u2019t|skip)\b")
AMEND = re.compile(r"^(change|edit|adjust|something else|not quite|reschedule)\b")
LATER = re.compile(r"^(send|reply|post|do it) later\b")


def action_parts(label):
    """A label split the way labelParts splits it: the mark in front, and the words."""
    m = re.match(r"^([^\w]+)", label)
    return (m.group(1).strip(), label[m.end():].strip()) if m else ("", label)


def tone_of(label):
    if label.startswith("\u2705"):
        return "go"
    if label.startswith("\u270f"):
        return "amend"
    if label.startswith(("\u2715", "\u2717")):
        return "stop"
    if label.startswith(("\u270d", "\u23f0")):
        return "plain"
    words = action_parts(label)[1].lower()
    if LATER.match(words):
        return "plain"
    return ("go" if AFFIRM.match(words) else "stop" if DECLINE.match(words)
            else "amend" if AMEND.match(words) else "plain")


def action_columns(labels):
    """How many answers go across (actionColumns): the longest label decides, a mark counting
    about three characters, and the rows are evened out. Four answers, the longest Send later,
    make two rows of two."""
    longest = max((3 if action_parts(l)[0] else 0) + len(action_parts(l)[1]) for l in labels)
    most = 4 if longest <= 6 else 3 if longest <= 9 else 2 if longest <= 15 else 1
    across = min(len(labels), most)
    rows = -(-len(labels) // across)
    return -(-len(labels) // rows)


# The thread. Your message and the draft that answers it came minutes after the agent's report,
# so the report keeps its own time under it and the two after it share one, the kit's rule: a
# message says when unless the one after it says the same. It opened on a question about the
# accountant and its answer until September 28, 2026; set at the phone's own 17 point there was
# room for three messages and the draft, and the report is the one the Agents screen shows as
# this agent's last word, so the two screens are one conversation.
CHAT = [
    dict(mine=False, when="40 minutes ago",
         text="\U0001F4E7 Twelve came in overnight. Two need you, and the other ten are filed."),
    dict(mine=True, when="8 minutes ago", text="Tell the Hendersons Tuesday morning works."),
    dict(mine=False, when="8 minutes ago", lead="\u270d\ufe0f Here is what I would send:",
         quote="Tuesday morning works. I can be there at 9:00 to start.",
         actions=ACTIONS),
]
# The first message is the resting state; the next two land as beats on the stage, so the thread
# arrives the way a thread does.
CHAT_AT = [None, 0.1, 0.4]

BUB_W = 0.86 * (W - 2 * MARGIN)   # both sides get the same column, 86% of the transcript
BUB_PADX, BUB_PADY = 16.0, 12.0   # inside a bubble
BUB_FS, BUB_LH = 17.0, 24.0       # a message is set at 17 on 24, the size Messages sets one in
BUB_R, BUB_TAIL = 20.0, 6.0       # 20 round, and 6 at the tail that says who is speaking
BUB_GAP = 12.0                    # between one message and the next
QUOTE_IN = 15.0                   # a quote's 3 point rule and the 12 after it
ACT_H = 48.0                      # one answer in the bar
TRANSCRIPT_PAD = 24.0             # under the last message, above the message box


def bubble_path(x, y, w, h, mine):
    """A message's shape: every corner 20 round except the bottom one on the speaker's side."""
    r, t = BUB_R, BUB_TAIL
    bl, br = (r, t) if mine else (t, r)
    return ('<path d="M%s %sH%sA%s %s 0 0 1 %s %sV%sA%s %s 0 0 1 %s %sH%sA%s %s 0 0 1 %s %sV%sA%s %s 0 0 1 %s %sZ"'
            ' fill="%s"/>') % (
        f(x + r), f(y), f(x + w - r), f(r), f(r), f(x + w), f(y + r),
        f(y + h - br), f(br), f(br), f(x + w - br), f(y + h),
        f(x + bl), f(bl), f(bl), f(x), f(y + h - bl),
        f(y + r), f(r), f(r), f(x + r), f(y),
        "var(--accent-sub)" if mine else "var(--card)")


def answer_bar(x, y, w, labels):
    """The answers to a card (InlineActions) as a rounded bar inside the message, like an
    alert's buttons: 10 in from the message's sides and bottom, 14 round, a soft outline and soft
    rules between the cells, and each cell washed in the hue of what it answers."""
    cols = action_columns(labels)
    rows = [labels[i:i + cols] for i in range(0, len(labels), cols)]
    h = ACT_H * len(rows) + len(rows) + 1
    cid = uid("ab")
    o = ['<defs><clipPath id="%s">%s</clipPath></defs>' % (cid, rect(x, y, w, h, 14)),
         rect(x, y, w, h, 14, "var(--rule)"), '<g clip-path="url(#%s)">' % cid]
    for r, row in enumerate(rows):
        cw = (w - len(row) - 1) / len(row)
        cy = y + 1 + r * (ACT_H + 1)
        for c, label in enumerate(row):
            cx = x + 1 + c * (cw + 1)
            tone = tone_of(label)
            wash = {"go": "var(--opt-go)", "amend": "var(--opt-amend)", "stop": "var(--opt)",
                    "plain": "var(--opt-plain)"}[tone]
            ink = {"go": "var(--green)", "amend": "var(--gold)", "stop": "var(--text2)",
                   "plain": "var(--accent-strong)"}[tone]
            weight = "600" if tone == "go" else "500"
            mark, words = action_parts(label)
            mw = tw(mark, 17) if mark else 0
            lw = tw(words, 17, weight=weight)
            sx = cx + (cw - (mw + (6 if mark else 0) + lw)) / 2
            by = baseline(cy + (ACT_H - 22) / 2, 22, 17)
            o.append(rect(cx, cy, cw, ACT_H, 0, wash))
            if mark:
                o.append(text(sx, by, mark, 17, ink, "400"))
            o.append(text(sx + mw + (6 if mark else 0), by, words, 17, ink, weight))
    return "".join(o) + "</g>", h


def chat_item(m, measure_only=False, y=0.0):
    """One message laid out: its drawing and how tall it stands, the time under it included
    when it says one."""
    inner = BUB_W - 2 * BUB_PADX
    if "quote" in m:
        lead = wrap(m["lead"], inner, BUB_FS)
        quote = wrap(m["quote"], inner - QUOTE_IN, BUB_FS)
        body_h = BUB_LH * len(lead) + 8 + 4 + BUB_LH * len(quote)
        rows = -(-len(m["actions"]) // action_columns(m["actions"]))
        acts_h = ACT_H * rows + rows + 1
        w, h = BUB_W, BUB_PADY + body_h + 12 + acts_h + 10
        lines = None
    else:
        lines = wrap(m["text"], inner, BUB_FS)
        # A bubble that fits on one line hugs it; one that wraps takes the whole column, which is
        # what fit-content does with a max-width of 86%.
        w = BUB_W if len(lines) > 1 else min(BUB_W, tw(lines[0], BUB_FS) + 2 * BUB_PADX)
        h = 2 * BUB_PADY + BUB_LH * len(lines)
    if measure_only:
        return None, h
    x = (W - MARGIN - w) if m["mine"] else MARGIN
    o = [bubble_path(x, y, w, h, m["mine"])]
    tx = x + BUB_PADX
    if lines is not None:
        for i, ln in enumerate(lines):
            o.append(text(tx, baseline(y + BUB_PADY + BUB_LH * i, BUB_LH, BUB_FS), ln, BUB_FS))
    else:
        ty = y + BUB_PADY
        for i, ln in enumerate(lead):
            o.append(text(tx, baseline(ty + BUB_LH * i, BUB_LH, BUB_FS), ln, BUB_FS))
        # the quoted draft (.md .quote): the accent's 3 point rule, 12 in, 2 above and below
        qy = ty + BUB_LH * len(lead) + 8
        o.append(rect(tx, qy, 3, 4 + BUB_LH * len(quote), 0, "var(--accent)"))
        for i, ln in enumerate(quote):
            o.append(text(tx + QUOTE_IN, baseline(qy + 2 + BUB_LH * i, BUB_LH, BUB_FS), ln, BUB_FS))
        bar, _ = answer_bar(x + 10, qy + 4 + BUB_LH * len(quote) + 12, w - 20, m["actions"])
        o.append(bar)
    assert x >= MARGIN - 0.01 and x + w <= W - MARGIN + 0.01, "a bubble runs past the page's margin"
    return "".join(o), h


def screen_chat():
    # Measure first, because a short conversation sits on the message box the way every
    # conversation does, rather than hanging from the bar with the screen empty under it.
    times = [i == len(CHAT) - 1 or CHAT[i + 1]["when"] != m["when"] for i, m in enumerate(CHAT)]
    heights = [chat_item(m, True)[1] + ((4 if m["mine"] else 6) + 16 if t else 0)
               for m, t in zip(CHAT, times)]
    total = sum(heights) + BUB_GAP * (len(CHAT) - 1)
    y = max(PAGE_TOP, COMPOSER_Y - TRANSCRIPT_PAD - total)

    o = []
    for n, (m, t) in enumerate(zip(CHAT, times)):
        body, h = chat_item(m, y=y)
        if t:
            ty = y + h + (4 if m["mine"] else 6)
            body += text(W - MARGIN if m["mine"] else MARGIN, baseline(ty, 16, 12), m["when"], 12,
                         "var(--muted)", "400", "end" if m["mine"] else "start")
        o.append(body if CHAT_AT[n] is None else beat(body, CHAT_AT[n]))
        y += heights[n] + BUB_GAP
    y -= BUB_GAP

    # The thread is laid out by accumulation, so adding a message pushes everything below it
    # into the composer, which is drawn at a fixed y and would happily print over the top.
    # That happened once: the timestamp landed at 662 against a composer at 660 and the two
    # were each inside the screen, so a bounds check saw nothing wrong. Assert the gap. It is
    # the thread being taller than the room between the bar and the box that trips it now,
    # since a thread that fits is set down on the box.
    assert y + TRANSCRIPT_PAD <= COMPOSER_Y, (
        "chat thread runs to %.0f and the composer starts at %.0f: shorten a message "
        "or drop one" % (y + TRANSCRIPT_PAD, COMPOSER_Y))

    # the message bar, a shade off the page with a hairline along its top, running on down behind
    # the tab bar (bgBar in theme.ts, Chat.tsx, since 2026-10-05): a gray knob for attaching, the
    # box, then the microphone and Talk out loud, which is what an empty box ends in where the
    # computer can hear and speak. The arrow takes both their places once there is something typed.
    o.append(rect(0, COMPOSER_Y, W, H - COMPOSER_Y, 0, "var(--bar)"))
    o.append(rect(0, COMPOSER_Y, W, 0.5, 0, "var(--line)"))
    ky = COMPOSER_Y + 12
    o.append(circle(12 + 22, ky + 22, 22, "var(--soft)"))
    o.append(sym("plus", 12 + 11, ky + 11, 22, "var(--text2)"))
    bx = 12 + 44 + 8
    bw = W - bx - (8 + 44 + 8 + 44 + 12)
    o.append(rect(bx, ky, bw, 44, 20, "var(--card)"))
    o.append(text(bx + 16, baseline(ky + 11, 22, 17), "Message " + AGENT_NAME, 17, "var(--muted)"))
    for i, mark in enumerate(("mic", "talk")):
        kx = bx + bw + 8 + i * (44 + 8)
        o.append(circle(kx + 22, ky + 22, 22, "var(--soft)"))
        o.append(sym(mark, kx + 11, ky + 11, 22, "var(--muted)"))
    o.append(top_bar(AGENT_NAME, "ember"))
    o.append(status_bar())
    # The draft is a job waiting on you, which is something in flight, so Dashboard wears the dot.
    o.append(tab_bar(AGENT_TABS, "Chat", marked="Dashboard"))
    return "".join(o)


# ── screen 3: what an agent is made of ───────────────────────────────────────────────────
# Real add-ons, each under its catalog name. TRUST.md: never name an add-on that is not in the
# catalog. Until 2026-09-27 these five were invented ("Inbox triage", "Reply drafts",
# "Proofreader", "Calendar", "Receipts") on a screen that sits under Browse the marketplace,
# which read as five things you could find there.
#
# Since September 28, 2026 they are the iPhone's grid (SkillGrid in src/screens/Manage.tsx), a
# tile each: a symbol picked from the name, the name, and one line saying On or Off. The switch
# and the chevron that sat on every card are on a skill's own page on an iPhone, and the line of
# description each skill carried has no place on a tile, so both went. Inbox Rules was drawn off
# with a Needs a connection pill; a tile that is off says Off and nothing else, and Email Manager
# beside it reads the same inbox, so the connection was never the missing thing. A specialist is
# a tile in the same grid, after the skills, with its role from the catalog as its line
# (data/marketplace/subagents/writer.json in the Archie repo), cut to fit as the app cuts it.
# The way into the marketplace is the grid's last two tiles now, where it was a button over the
# list.
SKILLS = [
    dict(name="Email Manager", on=True),
    dict(name="Inbox Rules", on=False),
    dict(name="Calendar Manager", on=True),
    dict(name="Waiting On", on=True),
]
SPECIALISTS = [
    dict(name="Writer", role="Drafts emails, posts and summaries for you to send, and never sends anything itself."),
]

# The symbol a skill wears, from the words in its name (SKILL_SYMBOLS in Manage.tsx), first match
# winning. A rule whose symbol this file does not draw falls back to the sparkles, the Skills
# tab's own, the way the kit does.
SKILL_SYMBOLS = [
    (r"inbox|triage", "tray"), (r"repl(y|ies)|draft", "reply"), (r"e-?mail|mail", "envelope"),
    (r"proofread|writ|edit", "pencil"), (r"calendar|meeting|schedul", "calendar"),
    (r"task|to-?do|checklist", "checklist"), (r"habit|streak", "flame"),
    (r"reflect|journal|review", "book"), (r"workout|fitness|exercise", "walk"),
    (r"learn|course|study|coach|tutor", "cap"), (r"read|watch", "books"), (r"word", "abc"),
    (r"trivia|quiz", "question"), (r"medic|refill|pill", "pills"), (r"meal|recipe|food|cook", "fork"),
    (r"bill|subscription|payment", "card"), (r"receipt|invoice|expense|month.?end|bookkeep|account", "doc"),
]


def skill_symbol(name):
    for rule, symbol in SKILL_SYMBOLS:
        if re.search(rule, name, re.I):
            return symbol if symbol in SYMBOLS else "sparkles"
    return "sparkles"


TILE_W = (W - 2 * MARGIN - 12) / 2    # half the page, less the 12 between two tiles
TILE_PAD = 14.0


def screen_skills():
    tiles = [dict(symbol=skill_symbol(s["name"]), title=s["name"], note="On" if s["on"] else "Off",
                  off=not s["on"]) for s in SKILLS]
    tiles += [dict(symbol=skill_symbol(s["name"]), title=s["name"], note=s["role"], off=False)
              for s in SPECIALISTS]
    tiles += [dict(symbol="plus", title="Add a skill", note="From the Marketplace", add=True),
              dict(symbol="hammer", title="Build your own", note="Say what it should do", add=True)]
    tw_in = TILE_W - 2 * TILE_PAD
    for t in tiles:
        t["lines"] = clamp(wrap(t["title"], tw_in, 17, weight="600"), 2, tw_in, 17, weight="600")
        t["note"] = clamp(wrap(t["note"], tw_in, 13), 1, tw_in, 13)[0]
        t["h"] = max(124.0, TILE_PAD + 40 + 12 + 22 * len(t["lines"]) + 2 + 18 + TILE_PAD)

    o = []
    y = PAGE_TOP
    for r in range(0, len(tiles), 2):
        pair = tiles[r:r + 2]
        # a row of the grid is as tall as its tallest tile, and both tiles stand that tall
        rh = max(t["h"] for t in pair)
        for c, t in enumerate(pair):
            x = MARGIN + c * (TILE_W + 12)
            add = t.get("add")
            ink = "var(--accent-strong)" if add else "var(--text2)" if t["off"] else "var(--text)"
            g = [rect(x, y, TILE_W, rh, 22, "var(--accent-sub)" if add else "var(--card)")]
            if add:
                # a door at the end of the grid, in the tint's own wash so it is not mistaken for a skill
                g.append(circle(x + TILE_PAD + 20, y + TILE_PAD + 20, 20, "var(--card)"))
                g.append(sym(t["symbol"], x + TILE_PAD + 8, y + TILE_PAD + 8, 24, "var(--accent-strong)"))
            else:
                # a white symbol on a square of the skills' own color, gray when the skill is off
                g.append(rect(x + TILE_PAD, y + TILE_PAD, 40, 40, 11,
                              "var(--soft)" if t["off"] else "var(--t-skills)"))
                g.append(sym(t["symbol"], x + TILE_PAD + 6, y + TILE_PAD + 6, 28,
                             "var(--muted)" if t["off"] else "#FFFFFF"))
            note_top = y + rh - TILE_PAD - 18
            title_top = note_top - 2 - 22 * len(t["lines"])
            for i, ln in enumerate(t["lines"]):
                g.append(text(x + TILE_PAD, baseline(title_top + 22 * i, 22, 17), ln, 17, ink, "600"))
            g.append(text(x + TILE_PAD, baseline(note_top, 18, 13), t["note"], 13,
                          "var(--accent-strong)" if add else "var(--muted)"))
            # the tiles land one after another on the stage, a beat apart
            o.append(beat("".join(g), 0.06 + 0.09 * (r + c)))
        y += rh + 12
    assert y <= TABBAR_Y, "the skill tiles run under the tab bar: drop a tile"
    o.append(top_bar(AGENT_NAME, "ember"))
    o.append(status_bar())
    o.append(tab_bar(AGENT_TABS, "Skills", marked="Dashboard"))
    return "".join(o)


SCREENS = [
    (screen_agents, "Your agents, awake or asleep",
     "The agents on your computer, each with the last thing it said and a Start or Stop button."),
    (screen_chat, "The conversation, and its buttons",
     "A conversation with an agent, where a drafted reply offers Send, Edit it, Send later and Dismiss."),
    (screen_skills, "What an agent is made of",
     "The skills an agent is made of, a tile each, saying which are on, with a tile for adding another."),
]


# ── assembly ─────────────────────────────────────────────────────────────────────────────
# Two token sets, because these are drawings of an app that has both and the page is read in
# both: the kit's iosLight and iosDark (src/theme.ts in the app), under the kit's own names so a
# value can be searched for in both files. The answer bar's washes are mixed here the way the kit
# mixes them with color-mix, so each is written down once as the two colors it is made of.
def mix(a, b, t):
    """`t` of color a and the rest of color b, as color-mix(in srgb, a t, b) makes it."""
    pa = [int(a[i:i + 2], 16) for i in (1, 3, 5)]
    pb = [int(b[i:i + 2], 16) for i in (1, 3, 5)]
    return "#" + "".join("%02X" % round(x * t + y * (1 - t)) for x, y in zip(pa, pb))


def tokens(p, shell):
    t = dict(p)
    t["opt"] = mix(p["card"], p["text"], 0.95)              # the way out's gray
    t["opt-go"] = mix(p["card"], p["green-hue"], 0.86)      # a yes
    t["opt-amend"] = mix(p["card"], p["gold-hue"], 0.86)    # a change
    t["opt-plain"] = mix(p["card"], p["accent"], 0.86)      # anything else
    t["rule"] = mix(p["card"], p["text"], 0.78)             # between the answers
    del t["green-hue"], t["gold-hue"]
    t.update(shell)
    return ";".join("--%s:%s" % kv for kv in t.items())


LIGHT = {"bg": "#F5F1EB", "card": "#FFFFFF", "text": "#44403B", "text2": "#615C55", "muted": "#6C655E",
         "accent": "#A95425", "accent-sub": "#FBE4D3", "accent-strong": "#984C21",
         "green": "#416934", "green-sub": "rgba(103,155,85,0.16)", "green-hue": "#679B55",
         "green-fill": "#46723A", "red-fill": "#A8463B", "on-fill": "#FFFFFF",
         "gold": "#7D5C1B", "gold-hue": "#BB8C33", "soft": "rgba(120,112,100,0.13)",
         "lens": "rgba(68,64,59,0.08)", "glass": "rgba(252,250,246,0.5)",
         "glass-rim": "rgba(255,255,255,0.95)", "glass-edge": "rgba(68,64,59,0.24)",
         "glass-cast": "rgba(42,37,33,0.08)", "face-ground": "#FBE4D3", "t-skills": "#C0673A",
         "status-ink": "#000000", "bar": "#ECE6DC", "line": "rgba(68,64,59,0.16)"}
DARK = {"bg": "#1A1A19", "card": "#2B2B29", "text": "#F3F0ED", "text2": "#AEACA6", "muted": "#A6A29C",
        "accent": "#EDA277", "accent-sub": "#453629", "accent-strong": "#F0B18D",
        "green": "#8FBF7C", "green-sub": "rgba(143,191,124,0.16)", "green-hue": "#8FBF7C",
        "green-fill": "#4E7440", "red-fill": "#B0503F", "on-fill": "#FFFFFF",
        "gold": "#DCAF57", "gold-hue": "#DCAF57", "soft": "rgba(243,240,237,0.1)",
        "lens": "rgba(243,240,237,0.12)", "glass": "rgba(62,62,60,0.55)",
        "glass-rim": "rgba(255,255,255,0.16)", "glass-edge": "rgba(0,0,0,0.55)",
        "glass-cast": "rgba(0,0,0,0.45)", "face-ground": "#453629", "t-skills": "#C0673A",
        "status-ink": "#FFFFFF", "bar": "#242423", "line": "rgba(243,240,237,0.14)"}
# The metal around the stills' screens, which is the site's phone and not the app's.
SHELL_LIGHT = {"shell": "#2E2C29", "shell-hi": "#5A5753", "shell-lo": "#171614", "edge": "rgba(255,255,255,.18)"}
SHELL_DARK = {"shell": "#3A3936", "shell-hi": "#6E6B66", "shell-lo": "#1A1918", "edge": "rgba(255,255,255,.22)"}

THEME = ('<style>.mk{%s}:root[data-theme="dark"] .mk{%s}.mk .mk-ui{font-family:%s}</style>'
         % (tokens(LIGHT, SHELL_LIGHT), tokens(DARK, SHELL_DARK), SF))


def device(inner, ox, oy):
    """The phone around a screen. Until 2026-09-18 this was one dark rounded rectangle, which
    read as a card with a screen on it (Jett: "too bland"). What a phone has that a card does
    not: a body that is lit from one corner and darker toward the other, a bright line where
    the glass meets the metal, a black bezel between the two, the buttons on its sides, and the
    island at the top of the screen with the lens in it. None of it is Archie; it is what makes
    the rest read as a phone. The screen's corner is the kit's 54, and the island and its lens
    stand where the kit and the stage's device put them, 14 down and 96 by 30, so the status
    bar's row is on the island's middle in both renderings."""
    cid, gid = uid("sc"), uid("gs")
    P = SHELL_PAD
    return ('<g transform="translate(%s,%s)">' % (f(ox), f(oy))
            + '<defs><clipPath id="%s">%s</clipPath>' % (cid, rect(0, 0, W, H, SCREEN_R, "#000"))
            + '<linearGradient id="%s" x1="0" y1="0" x2="0.4" y2="1">' % gid
            + '<stop offset="0" style="stop-color:var(--shell-hi)"/>'
            + '<stop offset="0.45" style="stop-color:var(--shell)"/>'
            + '<stop offset="1" style="stop-color:var(--shell-lo)"/></linearGradient></defs>'
            # the buttons, on the metal behind the body: volume on the left, power on the right
            + rect(-P - 3, 118, 3.5, 34, 1.5, "var(--shell-lo)")
            + rect(-P - 3, 166, 3.5, 54, 1.5, "var(--shell-lo)")
            + rect(-P - 3, 232, 3.5, 54, 1.5, "var(--shell-lo)")
            + rect(W + P - 0.5, 186, 3.5, 84, 1.5, "var(--shell-lo)")
            # the body, its lit edge, and the bezel, each concentric with the screen's corner
            + rect(-P, -P, W + P * 2, H + P * 2, SCREEN_R + P, "url(#%s)" % gid)
            + rect(-P + 0.75, -P + 0.75, W + P * 2 - 1.5, H + P * 2 - 1.5, SCREEN_R + P - 0.75,
                   "none", "var(--edge)", 1)
            + rect(-4, -4, W + 8, H + 8, SCREEN_R + 4, "#0B0B0A")
            # the screen
            + '<g clip-path="url(#%s)">' % cid
            + rect(0, 0, W, H, 0, "var(--bg)") + '<g class="mk-ui">' + inner + "</g></g>"
            # the island and the lens, over the status bar's clear middle
            + rect(W / 2 - 48, 14, 96, 30, 15, "#000")
            + circle(W / 2 + 27, 29, 7, "#121820")
            + circle(W / 2 + 25.2, 27.2, 1.8, "rgba(130,170,225,.35)")
            + "</g>")


def phone(body, ox, oy):
    return device(body, ox, oy)


def build():
    """The two renderings: the stage phone, then the stills."""
    _n[0] = 0
    caption_y = 856.0

    # The stage: the shell once, the three screens inside it, screen i on act i. aria-hidden,
    # because the scene it stands in carries the accessible name for the whole drawing, the
    # way the homepage's does; the stills below are what a machine reads.
    new_doc()
    bodies = []
    for i, (fn, cap, desc) in enumerate(SCREENS):
        _beat["act"] = i
        bodies.append(fn())
    _beat["act"] = None
    # The screen alone, at the screen's own size: the device around it on the stage is the
    # homepage phone's, in HTML (styles.css section 49, the .dp-* classes), which is what gives
    # it a rim, a chamfer and light that moves with its angle. The stylesheet lights one
    # .mk-scr at a time and the rest are not painted.
    stage = ('<svg class="mk mk-stage" viewBox="0 0 %s %s" aria-hidden="true" focusable="false"'
             ' xmlns="http://www.w3.org/2000/svg" style="font-family:inherit">' % (f(W), f(H)) + THEME
             + doc_defs() + rect(0, 0, W, H, 0, "var(--bg)") + '<g class="mk-ui">'
             + "".join('<g class="mk-scr%s" data-scr="%d">%s</g>'
                       % (" is-on" if i == 0 else "", i, body) for i, body in enumerate(bodies))
             + "</g></svg>")

    # The stills: one drawing per screen, each named, in a row the stylesheet stacks narrow.
    # The caption under each phone is the site's, so it stays in the page's face; only the
    # screen is set in the phone's.
    items = []
    for i, (fn, cap, desc) in enumerate(SCREENS):
        tid = "mks%d" % (i + 1)
        new_doc()
        drawn = phone(fn(), 11.0, 11.0)
        svg = ('<svg class="mk" viewBox="0 0 412 874" role="img" aria-labelledby="%s"'
               ' xmlns="http://www.w3.org/2000/svg" style="font-family:inherit;overflow:visible">' % tid
               + THEME + '<title id="%s">%s</title>' % (tid, esc(desc)) + doc_defs() + drawn
               + text(206, caption_y, cap, 21, "currentColor", "500", "middle") + "</svg>")
        items.append('<div class="mb-still-item">%s</div>' % svg)
    stills = ('<div class="mb-still" aria-label="Three screens from Archie Mobile">'
              + "".join(items) + "</div>")

    return stage, stills


def main():
    check = "--check" in sys.argv
    html = open(PAGE, encoding="utf-8").read()
    stage, stills = build()
    new = html
    for begin, end, body in ((STAGE_BEGIN, STAGE_END, stage), (BEGIN, END, stills)):
        pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
        if not pat.search(new):
            print("gen-phone-mocks: cannot find %r in the page" % begin)
            return 1
        block = begin + "\n              " + body + "\n              " + end
        new = pat.sub(lambda _: block, new, count=1)

    if new == html:
        print("gen-phone-mocks: clean. 3 screens, 2 renderings.")
        return 0
    if check:
        print("gen-phone-mocks: archie/mobile/ is out of date. Run scripts/gen-phone-mocks.py")
        return 1
    open(PAGE, "w", encoding="utf-8").write(new)
    print("gen-phone-mocks: wrote 3 screens as the stage phone and the three stills.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
